"""Borel measures, Radon measures, regularity, and Riesz representation.

Key theorems implemented
------------------------
- A Borel measure on a topological space X is a measure defined on the Borel
  sigma-algebra B(X) generated by the open sets of X.
- A Radon measure is a Borel measure that is locally finite (every point has a
  neighbourhood of finite measure) and inner regular (mu(A) = sup{mu(K) : K compact, K subset A}).
- Riesz-Markov-Kakutani representation theorem: for a compact Hausdorff space X,
  every positive linear functional L on C(X) is represented by a unique regular
  Borel measure mu such that L(f) = integral f d-mu.
- Regularity: a Borel measure is outer regular if mu(A) = inf{mu(U) : U open, A subset U}
  and inner regular if mu(A) = sup{mu(K) : K compact, K subset A}.
- Haar measure: every locally compact topological group G admits a left-invariant
  Radon measure (Haar measure), unique up to a positive scalar multiple.
- On compact groups, the Haar measure can be normalised to a probability measure.
- The Lebesgue measure on R^n is translation-invariant, regular, non-atomic, and sigma-finite.
- The Dirac measure delta_x is a probability measure supported at {x}; it is atomic and Radon.
- The Cantor measure (Devil's staircase measure) is supported on the Cantor set,
  is non-atomic, and is singular with respect to the Lebesgue measure.
- On a locally compact Hausdorff space, every Radon measure is regular.
- The counting measure on an uncountable discrete space is NOT locally finite, hence not Radon.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from typing import Any

from .result import Result


@dataclass(frozen=True)
class BorelMeasureProfile:
    """A curated Borel measure example."""

    key: str
    display_name: str
    measure_type: str
    is_radon: bool
    is_regular: bool
    is_atomic: bool
    is_sigma_finite: bool
    support_type: str
    presentation_layer: str
    focus: str
    chapter_targets: tuple[str, ...]


# ---------------------------------------------------------------------------
# Tag constants
# ---------------------------------------------------------------------------

RADON_MEASURE_TAGS: set[str] = {
    "radon_measure", "radon",
    "dirac_measure", "dirac",
    "haar_measure", "lebesgue_measure",
    "gaussian_measure", "cantor_measure",
    "probability_measure", "finite_measure",
    "locally_finite_inner_regular",
}
REGULAR_MEASURE_TAGS: set[str] = {
    "regular_measure", "outer_regular", "inner_regular",
    "radon_measure", "radon",
    "lebesgue_measure", "haar_measure",
    "gaussian_measure", "dirac_measure",
    "borel_regular",
}
COMPACT_HAUSDORFF_SPACE_TAGS: set[str] = {
    "compact_hausdorff", "compact_t2",
    "compact_metrizable", "compact_metric",
    "profinite", "cantor_set", "cantor_space",
    "closed_interval", "torus", "sphere",
}
LOCALLY_COMPACT_HAUSDORFF_TAGS: set[str] = {
    "locally_compact_hausdorff", "locally_compact_t2",
    "locally_compact_metrizable",
    "real_line", "reals", "euclidean",
    "compact_hausdorff", "compact_t2",
    "locally_compact_group",
}
HAAR_MEASURE_TAGS: set[str] = {
    "locally_compact_group", "topological_group",
    "compact_group", "abelian_group",
    "lie_group", "discrete_group",
    "real_line", "reals",
    "torus", "circle",
    "p_adic_integers",
}
ATOMIC_MEASURE_TAGS: set[str] = {
    "atomic_measure", "point_mass",
    "dirac_measure", "dirac",
    "counting_measure",
    "discrete_measure",
}
NON_ATOMIC_TAGS: set[str] = {
    "non_atomic", "diffuse",
    "lebesgue_measure", "gaussian_measure",
    "cantor_measure", "haar_measure_continuous",
    "absolute_continuous_lebesgue",
}
COMPACT_SUPPORT_TAGS: set[str] = {
    "compact_support", "compactly_supported",
    "dirac_measure", "dirac",
    "finite_measure_compact_space",
    "measure_on_compact",
}
NOT_RADON_TAGS: set[str] = {
    "counting_measure_uncountable",
    "non_locally_finite",
    "not_inner_regular",
    "not_radon",
}
NOT_HAAR_TAGS: set[str] = {
    "not_locally_compact",
    "infinite_dimensional_banach",
    "hilbert_space_infinite_dim",
    "frechet_space_non_lc",
}
SIGMA_FINITE_TAGS: set[str] = {
    "sigma_finite", "finite_measure",
    "probability_measure",
    "lebesgue_measure", "gaussian_measure",
    "haar_measure", "radon_measure", "radon",
    "dirac_measure",
}


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _extract_tags(space: Any) -> set[str]:
    raw = getattr(space, "tags", None) or getattr(space, "_tags", None)
    if isinstance(raw, (set, list, tuple, frozenset)):
        return {str(t).strip().lower() for t in raw}
    return set()


def _representation_of(space: Any) -> str:
    metadata = getattr(space, "metadata", {}) or {}
    if isinstance(metadata, dict) and "representation" in metadata:
        return str(metadata["representation"]).strip().lower()
    rep = getattr(space, "representation", None)
    if rep:
        return str(rep).strip().lower()
    return "symbolic_general"


def _matches_any(tags: set[str], candidates: set[str]) -> bool:
    return bool(tags & candidates)


# ---------------------------------------------------------------------------
# Named example registry
# ---------------------------------------------------------------------------

def get_named_borel_measure_profiles() -> tuple[BorelMeasureProfile, ...]:
    """Return the registry of canonical Borel measure examples."""
    return (
        BorelMeasureProfile(
            key="lebesgue_measure",
            display_name="lambda^n — Lebesgue measure on R^n",
            measure_type="translation_invariant",
            is_radon=True,
            is_regular=True,
            is_atomic=False,
            is_sigma_finite=True,
            support_type="whole_space",
            presentation_layer="main_text",
            focus=(
                "The Lebesgue measure lambda^n on R^n is the unique (up to scalar) "
                "translation-invariant Radon measure on R^n. It is sigma-finite "
                "(R^n = union of [-k,k]^n, each of finite measure), regular (outer "
                "and inner regular), and non-atomic (every singleton has measure zero). "
                "It is the Haar measure of the locally compact abelian group (R^n, +). "
                "The Lebesgue measure is absolutely continuous with respect to itself, "
                "and the Radon-Nikodym theorem applies: every measure absolutely "
                "continuous w.r.t. lambda^n has a density (Radon-Nikodym derivative)."
            ),
            chapter_targets=("5", "17", "52"),
        ),
        BorelMeasureProfile(
            key="dirac_measure",
            display_name="delta_x — Dirac measure at x",
            measure_type="point_mass",
            is_radon=True,
            is_regular=True,
            is_atomic=True,
            is_sigma_finite=True,
            support_type="singleton",
            presentation_layer="main_text",
            focus=(
                "The Dirac measure delta_x at a point x is defined by "
                "delta_x(A) = 1 if x in A, 0 otherwise. "
                "It is a probability measure (delta_x(X) = 1), atomic (the atom is {x}), "
                "Radon (finite and inner regular — {x} is compact), and regular. "
                "The support of delta_x is the singleton {x}. "
                "In the Riesz representation, delta_x corresponds to the evaluation "
                "functional L(f) = f(x) on C(X). "
                "Finite linear combinations of Dirac measures are called discrete measures."
            ),
            chapter_targets=("5", "17"),
        ),
        BorelMeasureProfile(
            key="haar_measure_compact",
            display_name="mu_G — Haar measure on a compact group",
            measure_type="haar_probability",
            is_radon=True,
            is_regular=True,
            is_atomic=False,
            is_sigma_finite=True,
            support_type="whole_group",
            presentation_layer="main_text",
            focus=(
                "Every compact topological group G admits a unique left-invariant "
                "probability measure mu_G (Haar measure, normalised so mu_G(G) = 1). "
                "It is also right-invariant (compact groups are unimodular). "
                "mu_G is Radon and regular. Examples: the normalised Lebesgue measure "
                "on the circle S^1 or torus T^n, the Haar measure on the Cantor group "
                "{0,1}^omega (product of counting measures on {0,1}), and the "
                "normalised Haar measure on any profinite group. "
                "The Haar measure enables harmonic analysis on compact groups "
                "(Peter-Weyl theorem)."
            ),
            chapter_targets=("5", "17", "46"),
        ),
        BorelMeasureProfile(
            key="haar_measure_lc",
            display_name="mu_G — Haar measure on a locally compact group",
            measure_type="haar_radon",
            is_radon=True,
            is_regular=True,
            is_atomic=False,
            is_sigma_finite=False,
            support_type="whole_group",
            presentation_layer="selected_block",
            focus=(
                "Every locally compact topological group G admits a left Haar measure: "
                "a non-zero left-invariant Radon measure, unique up to a positive "
                "scalar multiple. Examples: Lebesgue measure on R (additive group), "
                "counting measure on a discrete group (e.g., Z), and the p-adic "
                "Haar measure on Qp. "
                "The modular function Delta: G -> R_{>0} measures the failure of "
                "left-invariant measures to be right-invariant. "
                "When Delta = 1 identically, G is called unimodular "
                "(e.g., abelian groups, compact groups, discrete groups)."
            ),
            chapter_targets=("5", "17", "46"),
        ),
        BorelMeasureProfile(
            key="counting_measure",
            display_name="# — counting measure on a discrete space",
            measure_type="counting",
            is_radon=False,
            is_regular=False,
            is_atomic=True,
            is_sigma_finite=False,
            support_type="whole_space",
            presentation_layer="main_text",
            focus=(
                "The counting measure on a set X is defined by #(A) = |A| "
                "(cardinality of A). On a countable discrete space (e.g., N or Z), "
                "it is sigma-finite and serves as the Haar measure of the discrete group. "
                "On an uncountable discrete space, it is NOT locally finite "
                "(every open set {x} has measure 1, so the whole space has infinite "
                "measure with no locally finite cover), hence NOT a Radon measure. "
                "The counting measure is atomic: every singleton {x} is an atom. "
                "Summation integrals: integral f d-# = sum_{x in X} f(x)."
            ),
            chapter_targets=("5", "17"),
        ),
        BorelMeasureProfile(
            key="cantor_measure",
            display_name="mu_C — Cantor measure (Devil's staircase)",
            measure_type="singular_continuous",
            is_radon=True,
            is_regular=True,
            is_atomic=False,
            is_sigma_finite=True,
            support_type="cantor_set",
            presentation_layer="selected_block",
            focus=(
                "The Cantor measure mu_C is the Lebesgue-Stieltjes measure associated "
                "with the Cantor function (Devil's staircase) F: [0,1] -> [0,1]. "
                "mu_C is a probability measure supported on the Cantor set C "
                "(mu_C(C) = 1, mu_C([0,1] \\ C) = 0). "
                "It is non-atomic: mu_C({x}) = 0 for every x (the Cantor function "
                "is constant on each removed interval). "
                "It is singular with respect to the Lebesgue measure: there exists "
                "a set of Lebesgue measure 1 on which mu_C = 0. "
                "mu_C is Radon and regular (as a finite Borel measure on a compact metric space)."
            ),
            chapter_targets=("5", "17", "29"),
        ),
        BorelMeasureProfile(
            key="gaussian_measure",
            display_name="gamma_n — standard Gaussian measure on R^n",
            measure_type="absolutely_continuous",
            is_radon=True,
            is_regular=True,
            is_atomic=False,
            is_sigma_finite=True,
            support_type="whole_space",
            presentation_layer="selected_block",
            focus=(
                "The standard Gaussian measure gamma_n on R^n has density "
                "(2*pi)^{-n/2} exp(-|x|^2/2) with respect to the Lebesgue measure. "
                "It is a probability measure, non-atomic, Radon, and regular. "
                "gamma_n is absolutely continuous with respect to lambda^n "
                "(Radon-Nikodym derivative is the Gaussian density). "
                "Unlike the Lebesgue measure, gamma_n is NOT translation-invariant. "
                "The Cameron-Martin theorem describes how gamma_n transforms under "
                "shifts: it is quasi-invariant under shifts in the Cameron-Martin space H^1."
            ),
            chapter_targets=("5", "17", "52"),
        ),
    )


def borel_measure_layer_summary() -> dict[str, int]:
    """Return a count of profiles by presentation_layer."""
    return dict(Counter(p.presentation_layer for p in get_named_borel_measure_profiles()))


def borel_measure_chapter_index() -> dict[str, tuple[str, ...]]:
    """Return a mapping from chapter number to profile keys."""
    chapter_map: dict[str, list[str]] = {}
    for p in get_named_borel_measure_profiles():
        for chapter in p.chapter_targets:
            chapter_map.setdefault(chapter, []).append(p.key)
    return {chapter: tuple(keys) for chapter, keys in sorted(chapter_map.items())}


def borel_measure_type_index() -> dict[str, tuple[str, ...]]:
    """Return a mapping from measure_type to profile keys."""
    index: dict[str, list[str]] = {}
    for p in get_named_borel_measure_profiles():
        index.setdefault(p.measure_type, []).append(p.key)
    return {k: tuple(v) for k, v in sorted(index.items())}


# ---------------------------------------------------------------------------
# Core analysis functions
# ---------------------------------------------------------------------------

def is_radon_measure(space: Any) -> Result:
    """Check whether the measure on space is a Radon measure.

    A Radon measure on a topological space X is a Borel measure mu that is:
    (i)  locally finite: every point x has a neighbourhood U with mu(U) < inf,
    (ii) inner regular: mu(A) = sup{mu(K) : K subset A, K compact} for all Borel A.
    Key facts:
    - On a compact Hausdorff space, every finite Borel measure is Radon.
    - On a locally compact Hausdorff space, every regular Borel measure is Radon.
    - The Lebesgue, Dirac, Haar, and Gaussian measures are all Radon.
    - The counting measure on an uncountable discrete space is NOT Radon
      (fails local finiteness: every open set {x} has measure 1, but R is uncountable).

    Decision layers
    ---------------
    1. Explicit Radon / Dirac / Lebesgue / Haar / Gaussian tag -> true.
    2. Compact Hausdorff space (finite Borel measures are Radon) -> true.
    3. Locally compact Hausdorff + regular Borel measure -> true.
    4. Counting measure on uncountable space -> false.
    5. Explicit not-Radon tag -> false.
    6. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, RADON_MEASURE_TAGS):
        witness = next(t for t in tags if t in RADON_MEASURE_TAGS)
        return Result.true(
            mode="theorem",
            value="radon_measure",
            justification=[
                f"Tag {witness!r}: this is a Radon measure — locally finite and "
                "inner regular. Examples include Lebesgue, Dirac, Haar, and Gaussian measures.",
            ],
            metadata={**base, "criterion": "radon_tag", "witness": witness},
        )

    if _matches_any(tags, COMPACT_HAUSDORFF_SPACE_TAGS):
        witness = next(t for t in tags if t in COMPACT_HAUSDORFF_SPACE_TAGS)
        return Result.true(
            mode="theorem",
            value="radon_measure",
            justification=[
                f"Tag {witness!r}: on a compact Hausdorff space, every finite Borel "
                "measure is Radon. The space is compact, so local finiteness is automatic, "
                "and inner regularity follows from regularity of Borel measures.",
            ],
            metadata={**base, "criterion": "compact_hausdorff_radon", "witness": witness},
        )

    if (_matches_any(tags, LOCALLY_COMPACT_HAUSDORFF_TAGS) and
            _matches_any(tags, REGULAR_MEASURE_TAGS)):
        witness = next(t for t in tags if t in LOCALLY_COMPACT_HAUSDORFF_TAGS)
        return Result.true(
            mode="theorem",
            value="radon_measure",
            justification=[
                f"Tag {witness!r}: on a locally compact Hausdorff space, regular Borel "
                "measures are Radon. Local finiteness holds because compact neighbourhoods "
                "have finite measure.",
            ],
            metadata={**base, "criterion": "lc_hausdorff_regular_radon", "witness": witness},
        )

    if _matches_any(tags, NOT_RADON_TAGS | {"counting_measure_uncountable"}):
        blocking = next(t for t in tags if t in (NOT_RADON_TAGS |
                                                   {"counting_measure_uncountable"}))
        return Result.false(
            mode="theorem",
            value="radon_measure",
            justification=[
                f"Tag {blocking!r}: the counting measure on an uncountable space is not "
                "locally finite — every open set {x} has measure 1, but there is no "
                "neighbourhood of finite measure. Hence it is not a Radon measure.",
            ],
            metadata={**base, "criterion": "not_radon"},
        )

    return Result.unknown(
        mode="symbolic",
        value="radon_measure",
        justification=[
            "Insufficient tags to determine whether the measure is Radon. "
            "Supply tags such as 'radon_measure', 'lebesgue_measure', 'dirac_measure', "
            "'compact_hausdorff', 'locally_compact_hausdorff', or 'counting_measure_uncountable'.",
        ],
        metadata={**base, "criterion": None},
    )


def is_regular_measure(space: Any) -> Result:
    """Check whether the measure on space is regular (outer and inner regular).

    A Borel measure mu on a topological space X is:
    - Outer regular: mu(A) = inf{mu(U) : U open, A subset U} for all Borel A.
    - Inner regular: mu(A) = sup{mu(K) : K compact, K subset A} for all Borel A.
    - Regular: both outer and inner regular.
    Key facts:
    - On a locally compact Hausdorff space, every Radon measure is regular.
    - The Lebesgue, Dirac, Haar, and Gaussian measures are all regular.
    - On a compact metric space, every Borel probability measure is regular
      (Prokhorov / Ulam's theorem).

    Decision layers
    ---------------
    1. Explicit regular measure tags -> true.
    2. Radon measure on locally compact Hausdorff space -> true.
    3. Compact metric space (Ulam's theorem) -> true.
    4. Explicit not-regular tag -> false.
    5. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, REGULAR_MEASURE_TAGS):
        witness = next(t for t in tags if t in REGULAR_MEASURE_TAGS)
        return Result.true(
            mode="theorem",
            value="regular_measure",
            justification=[
                f"Tag {witness!r}: the measure is regular — both outer regular "
                "(approximated from outside by open sets) and inner regular "
                "(approximated from inside by compact sets).",
            ],
            metadata={**base, "criterion": "regular_tag", "witness": witness},
        )

    if (_matches_any(tags, RADON_MEASURE_TAGS) and
            _matches_any(tags, LOCALLY_COMPACT_HAUSDORFF_TAGS)):
        witness = next(t for t in tags if t in RADON_MEASURE_TAGS)
        return Result.true(
            mode="theorem",
            value="regular_measure",
            justification=[
                f"Tag {witness!r}: Radon measures on locally compact Hausdorff spaces "
                "are regular. Inner regularity and outer regularity both hold.",
            ],
            metadata={**base, "criterion": "radon_lc_hausdorff_regular", "witness": witness},
        )

    if (_matches_any(tags, {"compact_metrizable", "compact_metric"}) and
            _matches_any(tags, {"probability_measure", "finite_measure",
                                 "borel_measure", "radon_measure"})):
        witness = next(t for t in tags if t in {"compact_metrizable", "compact_metric"})
        return Result.true(
            mode="theorem",
            value="regular_measure",
            justification=[
                f"Tag {witness!r}: by Ulam's theorem (Prokhorov's theorem), every Borel "
                "probability measure on a compact metric space is regular (tight).",
            ],
            metadata={**base, "criterion": "ulam_theorem", "witness": witness},
        )

    if _matches_any(tags, {"not_regular", "not_regular_measure",
                            "outer_regular_not_inner", "inner_regular_not_outer"}):
        blocking = next(t for t in tags if t in {"not_regular", "not_regular_measure",
                                                    "outer_regular_not_inner",
                                                    "inner_regular_not_outer"})
        return Result.false(
            mode="theorem",
            value="regular_measure",
            justification=[
                f"Tag {blocking!r}: the measure fails full regularity — "
                "it is not simultaneously outer and inner regular.",
            ],
            metadata={**base, "criterion": "not_regular"},
        )

    return Result.unknown(
        mode="symbolic",
        value="regular_measure",
        justification=[
            "Insufficient tags to determine regularity. "
            "Supply tags such as 'regular_measure', 'radon_measure', 'lebesgue_measure', "
            "'compact_metrizable', or 'locally_compact_hausdorff'.",
        ],
        metadata={**base, "criterion": None},
    )


def riesz_representation_applies(space: Any) -> Result:
    """Check whether the Riesz-Markov-Kakutani representation theorem applies.

    The Riesz-Markov-Kakutani theorem: for a locally compact Hausdorff space X,
    every positive linear functional L on C_c(X) (continuous functions with compact
    support) is represented by a unique regular Borel measure mu such that
    L(f) = integral f d-mu for all f in C_c(X).
    For compact Hausdorff X: C_c(X) = C(X) and the dual C(X)* is exactly the
    space of signed regular Borel measures (by the full Riesz theorem).
    Key facts:
    - Compact Hausdorff: C(X)* cong M(X) (regular Borel measures).
    - Locally compact Hausdorff: C_c(X) functionals <- regular Borel measures.
    - Non-Hausdorff spaces: the theorem fails in general.

    Decision layers
    ---------------
    1. Compact Hausdorff -> true (full Riesz theorem for C(X)*).
    2. Locally compact Hausdorff -> true (Riesz for C_c(X)).
    3. Non-Hausdorff / not T2 -> false.
    4. Infinite-dimensional without local compactness -> false.
    5. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, COMPACT_HAUSDORFF_SPACE_TAGS):
        witness = next(t for t in tags if t in COMPACT_HAUSDORFF_SPACE_TAGS)
        return Result.true(
            mode="theorem",
            value="riesz_representation",
            justification=[
                f"Tag {witness!r}: compact Hausdorff space. The Riesz-Markov-Kakutani "
                "theorem applies in its strongest form: C(X)* is isometrically isomorphic "
                "to the space M(X) of signed regular Borel measures on X.",
            ],
            metadata={**base, "criterion": "compact_hausdorff_riesz", "witness": witness},
        )

    if _matches_any(tags, LOCALLY_COMPACT_HAUSDORFF_TAGS):
        witness = next(t for t in tags if t in LOCALLY_COMPACT_HAUSDORFF_TAGS)
        return Result.true(
            mode="theorem",
            value="riesz_representation",
            justification=[
                f"Tag {witness!r}: locally compact Hausdorff space. The Riesz-Markov-Kakutani "
                "theorem applies: every positive linear functional on C_c(X) (compactly "
                "supported continuous functions) is represented by a unique regular Borel measure.",
            ],
            metadata={**base, "criterion": "lc_hausdorff_riesz", "witness": witness},
        )

    if _matches_any(tags, {"not_hausdorff", "non_hausdorff",
                            "t0_not_t1", "not_t2"}):
        blocking = next(t for t in tags if t in {"not_hausdorff", "non_hausdorff",
                                                    "t0_not_t1", "not_t2"})
        return Result.false(
            mode="theorem",
            value="riesz_representation",
            justification=[
                f"Tag {blocking!r}: the Riesz-Markov-Kakutani theorem requires the "
                "Hausdorff (T2) separation axiom. Non-Hausdorff spaces do not generally "
                "admit a representation by regular Borel measures.",
            ],
            metadata={**base, "criterion": "not_hausdorff"},
        )

    if _matches_any(tags, NOT_HAAR_TAGS):
        blocking = next(t for t in tags if t in NOT_HAAR_TAGS)
        return Result.false(
            mode="theorem",
            value="riesz_representation",
            justification=[
                f"Tag {blocking!r}: infinite-dimensional spaces without local compactness "
                "(e.g., infinite-dimensional Banach or Hilbert spaces) do not satisfy "
                "the hypotheses of the Riesz theorem. The C_c(X) duality requires "
                "local compactness.",
            ],
            metadata={**base, "criterion": "not_locally_compact_riesz"},
        )

    return Result.unknown(
        mode="symbolic",
        value="riesz_representation",
        justification=[
            "Insufficient tags to determine Riesz representation applicability. "
            "Supply tags such as 'compact_hausdorff', 'locally_compact_hausdorff', "
            "'real_line', 'not_hausdorff', or 'infinite_dimensional_banach'.",
        ],
        metadata={**base, "criterion": None},
    )


def has_haar_measure(space: Any) -> Result:
    """Check whether space (as a topological group) admits a Haar measure.

    Every locally compact topological group G admits a left Haar measure: a
    non-zero left-invariant Radon measure, unique up to a positive scalar multiple.
    Key facts:
    - Compact groups: normalised Haar measure is also a probability measure.
    - Discrete groups: Haar measure is the counting measure.
    - R^n (additive): Haar measure is the Lebesgue measure.
    - Infinite-dimensional topological groups (e.g., Hilbert spaces) generally
      do NOT admit a Haar measure (no sigma-finite translation-invariant measure
      exists on infinite-dimensional Banach spaces).

    Decision layers
    ---------------
    1. Explicit Haar measure tag -> true.
    2. Locally compact topological group (including compact groups) -> true.
    3. Discrete group (counting measure is Haar) -> true.
    4. Locally compact abelian group -> true.
    5. Infinite-dimensional Banach / Hilbert / Frechet (not locally compact) -> false.
    6. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, {"haar_measure"}):
        return Result.true(
            mode="theorem",
            value="haar_measure",
            justification=[
                "Tag 'haar_measure': the space is equipped with an explicit Haar measure "
                "— a left-invariant Radon measure, unique up to positive scalar multiple.",
            ],
            metadata={**base, "criterion": "explicit_haar"},
        )

    if _matches_any(tags, HAAR_MEASURE_TAGS):
        witness = next(t for t in tags if t in HAAR_MEASURE_TAGS)
        return Result.true(
            mode="theorem",
            value="haar_measure",
            justification=[
                f"Tag {witness!r}: locally compact topological group. "
                "By the Haar measure theorem, every locally compact group admits "
                "a left-invariant Radon measure, unique up to a positive scalar. "
                "For compact groups it can be normalised to a probability measure.",
            ],
            metadata={**base, "criterion": "locally_compact_group_haar", "witness": witness},
        )

    if _matches_any(tags, {"discrete_group", "discrete", "countable_discrete"}):
        witness = next(t for t in tags if t in {"discrete_group", "discrete",
                                                   "countable_discrete"})
        return Result.true(
            mode="theorem",
            value="haar_measure",
            justification=[
                f"Tag {witness!r}: discrete groups are locally compact. "
                "The counting measure is the Haar measure for any discrete group. "
                "It is left-invariant (translations are bijections on the group).",
            ],
            metadata={**base, "criterion": "discrete_group_counting_haar", "witness": witness},
        )

    if _matches_any(tags, NOT_HAAR_TAGS):
        blocking = next(t for t in tags if t in NOT_HAAR_TAGS)
        return Result.false(
            mode="theorem",
            value="haar_measure",
            justification=[
                f"Tag {blocking!r}: infinite-dimensional Banach and Hilbert spaces are "
                "NOT locally compact. No sigma-finite translation-invariant Borel measure "
                "exists on an infinite-dimensional locally convex space "
                "(Weil's theorem / non-existence result).",
            ],
            metadata={**base, "criterion": "no_haar_infinite_dim"},
        )

    return Result.unknown(
        mode="symbolic",
        value="haar_measure",
        justification=[
            "Insufficient tags to determine Haar measure existence. "
            "Supply tags such as 'topological_group', 'locally_compact_group', "
            "'compact_group', 'discrete_group', 'real_line', "
            "or 'infinite_dimensional_banach'.",
        ],
        metadata={**base, "criterion": None},
    )


def measure_support_is_compact(space: Any) -> Result:
    """Check whether the support of the measure is compact.

    The support of a Borel measure mu on X is the smallest closed set F such that
    mu(X \\ F) = 0. Equivalently, x is in supp(mu) iff every open neighbourhood
    of x has positive measure. Key facts:
    - Dirac measure delta_x: support = {x} (compact).
    - Measure on a compact space: support subset of compact space -> compact.
    - Lebesgue measure on R: support = R (not compact).
    - Gaussian measure on R^n: support = R^n (not compact).
    - Cantor measure: support = Cantor set C (compact).
    - Counting measure on Z: support = Z (not compact).

    Decision layers
    ---------------
    1. Dirac measure (support = singleton) -> true.
    2. Measure on compact space (support subset compact) -> true.
    3. Compactly supported measure tag -> true.
    4. Cantor measure (support = Cantor set, compact) -> true.
    5. Lebesgue / Gaussian / Haar on R^n (support = R^n, not compact) -> false.
    6. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, {"dirac_measure", "dirac", "point_mass"}):
        witness = next(t for t in tags if t in {"dirac_measure", "dirac", "point_mass"})
        return Result.true(
            mode="theorem",
            value="support_compact",
            justification=[
                f"Tag {witness!r}: the Dirac measure delta_x has support = {{x}}, "
                "a singleton — which is compact in any Hausdorff space.",
            ],
            metadata={**base, "criterion": "dirac_singleton_support", "witness": witness},
        )

    if _matches_any(tags, COMPACT_SUPPORT_TAGS):
        witness = next(t for t in tags if t in COMPACT_SUPPORT_TAGS)
        return Result.true(
            mode="theorem",
            value="support_compact",
            justification=[
                f"Tag {witness!r}: the measure has compact support. "
                "Any closed subset of a compact space is compact.",
            ],
            metadata={**base, "criterion": "compact_support_tag", "witness": witness},
        )

    if _matches_any(tags, COMPACT_HAUSDORFF_SPACE_TAGS):
        witness = next(t for t in tags if t in COMPACT_HAUSDORFF_SPACE_TAGS)
        return Result.true(
            mode="theorem",
            value="support_compact",
            justification=[
                f"Tag {witness!r}: the underlying space is compact. "
                "The support of any Borel measure on a compact space is a closed subset "
                "of a compact space, hence compact.",
            ],
            metadata={**base, "criterion": "compact_space_support_compact", "witness": witness},
        )

    if _matches_any(tags, {"cantor_measure"}):
        return Result.true(
            mode="theorem",
            value="support_compact",
            justification=[
                "Tag 'cantor_measure': the Cantor measure is supported on the Cantor set C, "
                "which is compact (closed and bounded in [0,1]).",
            ],
            metadata={**base, "criterion": "cantor_measure_compact_support"},
        )

    if _matches_any(tags, {"lebesgue_measure", "gaussian_measure",
                            "haar_measure_lc", "counting_measure"}):
        blocking = next(t for t in tags if t in {"lebesgue_measure", "gaussian_measure",
                                                    "haar_measure_lc", "counting_measure"})
        return Result.false(
            mode="theorem",
            value="support_compact",
            justification=[
                f"Tag {blocking!r}: the Lebesgue measure on R^n, Gaussian measure, "
                "and Haar measure on non-compact groups have support equal to the whole "
                "space (or a non-compact closed subset), which is not compact.",
            ],
            metadata={**base, "criterion": "non_compact_support"},
        )

    return Result.unknown(
        mode="symbolic",
        value="support_compact",
        justification=[
            "Insufficient tags to determine compactness of the measure support. "
            "Supply tags such as 'dirac_measure', 'compact_hausdorff', "
            "'cantor_measure', 'lebesgue_measure', or 'compact_support'.",
        ],
        metadata={**base, "criterion": None},
    )


def classify_borel_measure(space: Any) -> dict[str, Any]:
    """Classify the Borel measure properties of space.

    Keys
    ----
    measure_class : str
        One of ``"radon_regular"``, ``"radon"``, ``"regular"``,
        ``"finite_borel"``, ``"borel"``, ``"not_radon"``, ``"unknown"``.
    is_radon : Result
    is_regular : Result
    riesz_applicable : Result
    has_haar : Result
    support_compact : Result
    key_properties : list[str]
    representation : str
    tags : list[str]
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)

    radon_r = is_radon_measure(space)
    reg_r = is_regular_measure(space)
    riesz_r = riesz_representation_applies(space)
    haar_r = has_haar_measure(space)
    supp_r = measure_support_is_compact(space)

    if radon_r.is_true and reg_r.is_true:
        measure_class = "radon_regular"
    elif radon_r.is_true:
        measure_class = "radon"
    elif reg_r.is_true:
        measure_class = "regular"
    elif _matches_any(tags, {"finite_measure", "probability_measure"}):
        measure_class = "finite_borel"
    elif radon_r.is_false:
        measure_class = "not_radon"
    else:
        measure_class = "unknown"

    key_properties: list[str] = []
    if radon_r.is_true:
        key_properties.append("radon")
    if reg_r.is_true:
        key_properties.append("regular")
    if riesz_r.is_true:
        key_properties.append("riesz_applicable")
    if haar_r.is_true:
        key_properties.append("haar_measure")
    if supp_r.is_true:
        key_properties.append("compact_support")
    if supp_r.is_false:
        key_properties.append("non_compact_support")
    if _matches_any(tags, ATOMIC_MEASURE_TAGS):
        key_properties.append("atomic")
    if _matches_any(tags, NON_ATOMIC_TAGS):
        key_properties.append("non_atomic")
    if radon_r.is_false:
        key_properties.append("not_radon")

    return {
        "measure_class": measure_class,
        "is_radon": radon_r,
        "is_regular": reg_r,
        "riesz_applicable": riesz_r,
        "has_haar": haar_r,
        "support_compact": supp_r,
        "key_properties": key_properties,
        "representation": representation,
        "tags": sorted(tags),
    }


def borel_measure_profile(space: Any) -> dict[str, Any]:
    """Full Borel measure profile combining classification and named examples.

    Keys
    ----
    classification : dict
        Output of :func:`classify_borel_measure`.
    named_profiles : tuple[BorelMeasureProfile, ...]
        Registry of canonical Borel measure examples.
    layer_summary : dict[str, int]
        Profile count by presentation_layer.
    """
    return {
        "classification": classify_borel_measure(space),
        "named_profiles": get_named_borel_measure_profiles(),
        "layer_summary": borel_measure_layer_summary(),
    }


__all__ = [
    "BorelMeasureProfile",
    "RADON_MEASURE_TAGS",
    "REGULAR_MEASURE_TAGS",
    "COMPACT_HAUSDORFF_SPACE_TAGS",
    "LOCALLY_COMPACT_HAUSDORFF_TAGS",
    "HAAR_MEASURE_TAGS",
    "ATOMIC_MEASURE_TAGS",
    "NON_ATOMIC_TAGS",
    "COMPACT_SUPPORT_TAGS",
    "NOT_RADON_TAGS",
    "NOT_HAAR_TAGS",
    "SIGMA_FINITE_TAGS",
    "get_named_borel_measure_profiles",
    "borel_measure_layer_summary",
    "borel_measure_chapter_index",
    "borel_measure_type_index",
    "is_radon_measure",
    "is_regular_measure",
    "riesz_representation_applies",
    "has_haar_measure",
    "measure_support_is_compact",
    "classify_borel_measure",
    "borel_measure_profile",
]
