"""First homology of Dehn surgery on a framed link (rational coefficients).

Given a link ``L = L₁ ∪ … ∪ Lₙ`` and a surgery coefficient ``pᵢ/qᵢ`` on each
component, the surgered 3-manifold ``M`` has

    H₁(M; ℤ) = coker(A),    A_{ii} = pᵢ,   A_{ij} = qᵢ · lk(Lᵢ, Lⱼ)  (i ≠ j),

because ``H₁`` of the link complement is freely generated by the meridians
``μ₁, …, μₙ``, the longitude ``λᵢ = Σ_{j≠i} lk(Lᵢ, Lⱼ) μⱼ``, and each surgery
kills the curve ``pᵢ μᵢ + qᵢ λᵢ``.  The cokernel is read off the Smith normal
form of ``A`` (reused from :mod:`pytop.homology`).

For **integral** surgery (``qᵢ = 1``) this is the symmetric linking matrix with
the framings on the diagonal, and ``|H₁| = |det A|`` whenever ``A`` is
non-singular.

This module also classifies **lens spaces** ``L(p, q) = (p/q)``-surgery on the
unknot: homeomorphism (``q' ≡ ±q^{±1} mod p``) and homotopy equivalence
(``q q' ≡ ±n² mod p``) — both elementary, exact computations.

Pure Python, exact integer arithmetic, no dependencies.

Worked checks
-------------
* ``(p/q)`` surgery on the unknot → ``L(p, q)``, ``H₁ = ℤ/p``.
* ``0``-surgery on the unknot → ``S¹ × S²``, ``H₁ = ℤ``.
* ``±1``-surgery on any knot → integral homology sphere, ``H₁ = 0``.
* ``0``-surgery on the Borromean rings → ``T³``, ``H₁ = ℤ³``.
* ``E₈`` plumbing (eight ``−2``-framed unknots) → Poincaré homology sphere,
  ``H₁ = 0``.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import gcd
from typing import Any

from .exact_linalg import cokernel as _abelian_cokernel

__all__ = [
    "FirstHomology",
    "first_homology_of_surgery",
    "first_homology_of_link_surgery",
    "lens_space_first_homology",
    "are_lens_spaces_homeomorphic",
    "are_lens_spaces_homotopy_equivalent",
]


# ---------------------------------------------------------------------------
# Result type
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class FirstHomology:
    """The first homology group ``H₁ = ℤ^{free_rank} ⊕ ⊕ ℤ/dᵢ``.

    ``torsion`` lists the invariant factors ``dᵢ > 1`` with ``d₁ | d₂ | …``.
    """

    free_rank: int
    torsion: tuple[int, ...] = ()

    @property
    def order(self) -> int | None:
        """``|H₁|`` if finite, else ``None`` (infinite, i.e. positive rank)."""
        if self.free_rank > 0:
            return None
        product = 1
        for d in self.torsion:
            product *= d
        return product

    @property
    def is_homology_sphere(self) -> bool:
        """Whether ``H₁ = 0`` (an integral homology sphere when ``M`` is closed)."""
        return self.free_rank == 0 and not self.torsion

    @property
    def is_rational_homology_sphere(self) -> bool:
        """Whether ``H₁`` is finite (``b₁ = 0``)."""
        return self.free_rank == 0

    def __str__(self) -> str:
        parts: list[str] = []
        if self.free_rank == 1:
            parts.append("Z")
        elif self.free_rank > 1:
            parts.append(f"Z^{self.free_rank}")
        parts.extend(f"Z/{d}" for d in self.torsion)
        return " + ".join(parts) if parts else "0"


# ---------------------------------------------------------------------------
# Cokernel of an integer matrix via Smith normal form
# ---------------------------------------------------------------------------


def _cokernel(matrix: list[list[int]]) -> FirstHomology:
    """Return ``coker(matrix) = ℤ^{cols} / (row lattice)`` as a :class:`FirstHomology`.

    Delegates the exact computation to :func:`pytop.exact_linalg.cokernel` and
    wraps the resulting abelian group in the surgery-specific result type.
    """

    group = _abelian_cokernel(matrix)
    return FirstHomology(free_rank=group.free_rank, torsion=group.torsion)


# ---------------------------------------------------------------------------
# Surgery coefficients → first homology
# ---------------------------------------------------------------------------


def _as_fraction(coefficient: Any) -> tuple[int, int]:
    """Normalise a surgery coefficient to a ``(p, q)`` pair with ``q > 0``.

    Accepts an integer ``f`` (integral framing ``f/1``) or a ``(p, q)`` pair.
    """
    if isinstance(coefficient, int):
        return coefficient, 1
    p, q = coefficient
    p, q = int(p), int(q)
    if q == 0:
        raise ValueError("A surgery coefficient p/q must have q ≠ 0.")
    if q < 0:
        p, q = -p, -q
    return p, q


def first_homology_of_surgery(
    coefficients: list[Any],
    linking_numbers: list[list[int]] | None = None,
) -> FirstHomology:
    """Return ``H₁`` of the manifold obtained by surgery on a framed link.

    Parameters
    ----------
    coefficients:
        One surgery coefficient per component: an integer framing ``f``
        (meaning ``f/1``) or a pair ``(p, q)`` for rational ``p/q`` surgery.
    linking_numbers:
        The ``n × n`` matrix of pairwise linking numbers ``lk(Lᵢ, Lⱼ)``; the
        diagonal is ignored (the framing comes from ``coefficients``).  Defaults
        to all zeros (an unlink), so single-component surgery needs no matrix.

    Returns
    -------
    FirstHomology
    """

    n = len(coefficients)
    fractions = [_as_fraction(c) for c in coefficients]

    if linking_numbers is None:
        linking_numbers = [[0] * n for _ in range(n)]
    elif len(linking_numbers) != n or any(len(row) != n for row in linking_numbers):
        raise ValueError(
            f"linking_numbers must be {n}×{n} to match the {n} surgery coefficients."
        )

    matrix = [[0] * n for _ in range(n)]
    for i in range(n):
        p_i, q_i = fractions[i]
        for j in range(n):
            matrix[i][j] = p_i if i == j else q_i * int(linking_numbers[i][j])

    return _cokernel(matrix)


def first_homology_of_link_surgery(
    link: Any,
    coefficients: list[Any],
) -> FirstHomology:
    """Return ``H₁`` of surgery on a :class:`~pytop.knot_invariants.LinkDiagram`.

    The pairwise linking numbers are read from the diagram via
    :func:`pytop.knot_invariants.linking_matrix`; the diagonal (which that
    function sets to ``0``) is replaced by the supplied framings.
    """

    from .knot_invariants import linking_matrix

    matrix = linking_matrix(link)
    if len(coefficients) != len(matrix):
        raise ValueError(
            f"expected {len(matrix)} coefficients for an "
            f"{len(matrix)}-component link; got {len(coefficients)}."
        )
    return first_homology_of_surgery(coefficients, linking_numbers=matrix)


# ---------------------------------------------------------------------------
# Lens spaces
# ---------------------------------------------------------------------------


def lens_space_first_homology(p: int, q: int = 1) -> FirstHomology:
    """Return ``H₁(L(p, q)) = ℤ/p`` (``ℤ`` when ``p = 0``: ``S¹ × S²``).

    ``L(p, q)`` is ``(p/q)``-surgery on the unknot.
    """
    return first_homology_of_surgery([(p, q)])


def _lens_residue(p: int, q: int) -> int:
    p = abs(p)
    if p == 0:
        raise ValueError("Lens space classification needs p ≠ 0.")
    q %= p
    if gcd(q, p) != 1:
        raise ValueError(f"L({p}, {q}) is undefined: q must be coprime to p.")
    return q


def are_lens_spaces_homeomorphic(p: int, q1: int, q2: int) -> bool:
    """Whether ``L(p, q₁) ≅ L(p, q₂)`` (orientation-preservingly).

    Reidemeister's classification: a homeomorphism exists iff
    ``q₂ ≡ ±q₁^{±1} (mod p)``.
    """
    p = abs(p)
    q1, q2 = _lens_residue(p, q1), _lens_residue(p, q2)
    inverse = pow(q1, -1, p)
    candidates = {q1 % p, (-q1) % p, inverse % p, (-inverse) % p}
    return q2 in candidates


def are_lens_spaces_homotopy_equivalent(p: int, q1: int, q2: int) -> bool:
    """Whether ``L(p, q₁) ≃ L(p, q₂)`` (homotopy equivalence).

    Classification: ``L(p, q₁) ≃ L(p, q₂)`` iff ``q₁ q₂ ≡ ±n² (mod p)`` for some
    ``n``.  (``L(7, 1)`` and ``L(7, 2)`` are homotopy equivalent but not
    homeomorphic — the standard example.)
    """
    p = abs(p)
    q1, q2 = _lens_residue(p, q1), _lens_residue(p, q2)
    target = (q1 * q2) % p
    squares = {(n * n) % p for n in range(p)}
    return target in squares or (-target) % p in squares
