"""Derived categories: triangulated structure, t-structures, semiorthogonal decompositions,
derived functors, dg-enhancements, and the geometry of D^b(Coh(X)).

Key theorems and constructions implemented
------------------------------------------
- Derived category D(A) (Grothendieck-Verdier 1963): for an abelian category A, the
  derived category D(A) is the localization of the homotopy category K(A) at the
  multiplicative system of quasi-isomorphisms (morphisms inducing isomorphisms on all
  cohomology groups). Objects of D(A) are cochain complexes of objects in A; morphisms
  are equivalence classes of roofs A <- C -> B where C -> A is a quasi-isomorphism.
  Variants: D^+(A), D^-(A), D^b(A) for complexes bounded below, above, or on both sides.
  The natural functor A -> D(A) embeds A as the full subcategory of complexes concentrated
  in degree 0. Ext^n_A(M, N) = Hom_{D(A)}(M, N[n]) for all n >= 0.
- Triangulated categories (Verdier 1963, Puppe 1962): an additive category T with an
  autoequivalence [1]: T -> T (the shift or translation functor, with inverse [-1]) and
  a class of distinguished triangles A -> B -> C -> A[1] satisfying:
  (TR1) Every morphism f: A -> B embeds in a distinguished triangle A -> B -> C -> A[1].
  (TR2) Rotation: if A -> B -> C -> A[1] is distinguished, so is B -> C -> A[1] -> B[1].
  (TR3) Morphism of triangles: any commuting square A -> B extends to a morphism of
        distinguished triangles (not necessarily uniquely).
  (TR4) Octahedral axiom: for A -> B -> C' -> A[1] and B -> C -> A' -> B[1], there exists
        a triangle C' -> D -> A' -> C'[1] compatible with both.
  The homotopy category K(A) and the derived category D(A) are the canonical examples.
  The long exact sequence in cohomology arises from a distinguished triangle:
  H^n(A) -> H^n(B) -> H^n(C) -> H^{n+1}(A) -> ... for A -> B -> C -> A[1].
- t-structures (Beilinson-Bernstein-Deligne 1982): a t-structure on a triangulated category
  T is a pair (T^{<=0}, T^{>=0}) of full subcategories satisfying:
  (i) T^{<=0}[1] ⊂ T^{<=0} and T^{>=0}[-1] ⊂ T^{>=0}.
  (ii) Hom(X, Y) = 0 for X ∈ T^{<=0} and Y ∈ T^{>=1} = T^{>=0}[-1].
  (iii) For every A ∈ T there is a distinguished triangle tau^{<=0}A -> A -> tau^{>=1}A -> ...
        (the truncation triangle).
  The heart C = T^{<=0} ∩ T^{>=0} is an abelian category; the cohomology objects H^n(A) =
  tau^{>=0}tau^{<=0}(A[-n]) ∈ C. The standard t-structure on D(A) has heart ≅ A.
  Perverse t-structure (BBD 1982): on D^b_c(X) for a stratified space X, the perverse
  t-structure has heart = perverse sheaves. The middle extension IC(L) of a local system L
  on a locally closed stratum is the perverse sheaf of intersection cohomology.
- Derived functors (Grothendieck 1957, Verdier): for a left exact functor F: A -> B between
  abelian categories (with enough injectives in A), the right derived functors R^nF: A -> B
  are defined by R^nF(M) = H^n(F(I^bullet)) where I^bullet is an injective resolution of M.
  In derived category language: RF: D^+(A) -> D^+(B) is the total right derived functor,
  a triangulated functor satisfying RF(M) ≅ F(I^bullet) for any injective resolution.
  Similarly, LF: D^-(A) -> D^-(B) for the left derived functor of a right exact F.
  Key examples: RHom(M, -), - ⊗^L N (derived tensor product), Rf_*(F) (direct image),
  f^!(F) (exceptional inverse image), R Gamma(X, F) (derived global sections).
- Semiorthogonal decomposition (Bondal 1990): a semiorthogonal decomposition of a
  triangulated category T is a sequence of full triangulated subcategories A_1,...,A_n
  such that: (i) Hom(A_i, A_j) = 0 for i > j (semiorthogonality);
  (ii) T is generated by A_1,...,A_n (every object admits a filtration with associated
  graded pieces in A_1,...,A_n via iterated distinguished triangles).
  Written T = ⟨A_1,...,A_n⟩. The categories A_i are called admissible subcategories
  (their inclusion functors have left and right adjoints).
  Exceptional collections: an object E in T is exceptional if Hom(E, E) = k (the base
  field) and Ext^i(E, E) = 0 for i ≠ 0. A sequence E_1,...,E_n is exceptional if each
  E_i is exceptional and Ext^i(E_p, E_q) = 0 for all i and p > q. The subcategory
  generated by E_1,...,E_n is then semiorthogonal.
  Beilinson's collection (1978): D^b(Coh(P^n)) = ⟨O, O(1), ..., O(n)⟩ — the line bundles
  O(0), O(1), ..., O(n) form a full exceptional collection on P^n.
- Fourier-Mukai transforms (Mukai 1981): for smooth proper varieties X, Y over k and
  an object P ∈ D^b(Coh(X × Y)) (the 'kernel'), the Fourier-Mukai functor is
  Phi_P: D^b(Coh(X)) -> D^b(Coh(Y)), Phi_P(F) = Rp_{Y*}(P ⊗^L p_X^*(F)).
  Every exact functor between derived categories of smooth proper varieties is a
  Fourier-Mukai functor (Orlov representability theorem 1996).
  Fourier-Mukai equivalences (derived equivalences): Phi_P is an equivalence iff the
  kernel P satisfies certain spanning and orthogonality conditions (Bondal-Orlov criterion).
  Mukai's original example: the Poincaré bundle on A × A^vee (abelian variety and its dual)
  gives an equivalence D^b(Coh(A)) ≅ D^b(Coh(A^vee)) — the 'Fourier transform' on A.
- dg-enhancements (Bondal-Kapranov 1990): a dg-enhancement of a triangulated category T
  is a pre-triangulated dg-category A with H^0(A) ≅ T. Every algebraic triangulated
  category (triangulated category arising as the homotopy category of a stable model
  category) admits a dg-enhancement (uniqueness: Lunts-Orlov 2010 for D^b(Coh(X)) and
  K^b(A-mod) for smooth proper X). The dg-structure captures the higher Ext groups and
  the A∞-structure of compositions, making the category 'linear' over a dg-algebra.
- Bondal-Orlov reconstruction (1997): a smooth projective variety X is uniquely
  determined (up to isomorphism) by its derived category D^b(Coh(X)) when the canonical
  bundle omega_X is ample or anti-ample. More precisely: if Phi_P: D^b(Coh(X)) -> D^b(Coh(Y))
  is an equivalence and X has ample (anti-)canonical bundle, then X ≅ Y. For K3 surfaces
  and abelian varieties (where omega ≅ O), derived equivalence does NOT imply isomorphism
  (Mukai pairs: D^b(A) ≅ D^b(A^vee) for dual abelian varieties).
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from typing import Any

from .result import Result


@dataclass(frozen=True)
class DerivedCategoryProfile:
    """A curated derived category theory example."""

    key: str
    display_name: str
    category_type: str
    base_category: str
    has_t_structure: bool
    is_enhanced: bool
    has_semiorthogonal_decomp: bool
    presentation_layer: str
    focus: str
    chapter_targets: tuple[str, ...]


# ---------------------------------------------------------------------------
# Tag constants
# ---------------------------------------------------------------------------

DERIVED_CATEGORY_TAGS: set[str] = {
    "derived_category",
    "homotopy_category",
    "quasi_isomorphism_localization",
    "db_coh",
    "bounded_derived",
    "unbounded_derived",
    "derived_functor_category",
}

TRIANGULATED_STRUCTURE_TAGS: set[str] = {
    "triangulated_category",
    "shift_functor",
    "distinguished_triangle",
    "octahedral_axiom",
    "rotation_axiom",
    "triangulated_functor",
    "exact_triangle",
}

T_STRUCTURE_TAGS: set[str] = {
    "t_structure",
    "heart_of_t_structure",
    "truncation_functor",
    "perverse_t_structure",
    "standard_t_structure",
    "cohomological_functor",
    "bbd_t_structure",
}

DERIVED_FUNCTOR_TAGS: set[str] = {
    "right_derived_functor",
    "left_derived_functor",
    "derived_tensor_product",
    "rhom",
    "ext_derived",
    "tor_derived",
    "direct_image_derived",
    "exceptional_inverse_image",
}

SEMIORTHOGONAL_TAGS: set[str] = {
    "semiorthogonal_decomposition",
    "exceptional_collection",
    "exceptional_object",
    "full_exceptional_collection",
    "admissible_subcategory",
    "mutation_exceptional",
    "beilinson_collection",
}

DG_ENHANCEMENT_TAGS: set[str] = {
    "dg_enhancement",
    "dg_category",
    "a_infinity_category",
    "pretriangulated_dg",
    "lunts_orlov",
    "dg_algebra",
    "stable_infinity_category",
}

BONDAL_ORLOV_TAGS: set[str] = {
    "bondal_orlov",
    "tilting_generator",
    "tilting_object",
    "derived_equivalence",
    "fourier_mukai",
    "fourier_mukai_kernel",
    "orlov_representability",
}

PERVERSE_SHEAF_TAGS: set[str] = {
    "perverse_sheaves",
    "intersection_cohomology",
    "middle_extension",
    "ic_sheaf",
    "bbd",
    "perverse_heart",
    "nearby_cycles",
    "vanishing_cycles",
}


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _extract_tags(space: Any) -> set[str]:
    raw = getattr(space, "tags", None) or getattr(space, "_tags", None)
    if isinstance(raw, (set, list, tuple, frozenset)):
        return {str(t).strip().lower() for t in raw}
    return set()


def _representation_of(space: Any) -> str:
    metadata = getattr(space, "metadata", {}) or {}
    if isinstance(metadata, dict) and "representation" in metadata:
        return str(metadata["representation"]).strip().lower()
    rep = getattr(space, "representation", None)
    if rep:
        return str(rep).strip().lower()
    return "symbolic_general"


def _matches_any(tags: set[str], candidates: set[str]) -> bool:
    return bool(tags & candidates)


# ---------------------------------------------------------------------------
# Named example registry
# ---------------------------------------------------------------------------

def get_named_derived_category_profiles() -> tuple[DerivedCategoryProfile, ...]:
    """Return the registry of canonical derived category theory examples."""
    return (
        DerivedCategoryProfile(
            key="derived_category_abelian",
            display_name="D(A) — derived category of an abelian category",
            category_type="derived_category",
            base_category="abelian",
            has_t_structure=True,
            is_enhanced=False,
            has_semiorthogonal_decomp=False,
            presentation_layer="main_text",
            focus=(
                "The derived category D(A) of an abelian category A is the universal "
                "triangulated category associated to A, constructed by inverting quasi-isomorphisms. "
                "Construction: start with the category Kom(A) of cochain complexes in A. "
                "Pass to the homotopy category K(A) by identifying chain-homotopic maps. "
                "Then localize K(A) at the class of quasi-isomorphisms: a morphism f: A -> B "
                "in K(A) is a quasi-isomorphism iff H^n(f): H^n(A) -> H^n(B) is an isomorphism "
                "for all n. The derived category D(A) = K(A)[W^{-1}] has the same objects as "
                "Kom(A) (complexes) but morphisms are equivalence classes of roofs "
                "A <-qis- C -> B (a quasi-isomorphism followed by a chain map). "
                "Triangulated structure: D(A) is triangulated with shift [1] (the degree-shift "
                "functor (A[1])^n = A^{n+1}, d_{A[1]} = -d_A) and distinguished triangles arising "
                "from short exact sequences 0 -> A -> B -> C -> 0 in A: "
                "A -> B -> C -> A[1] is a distinguished triangle in D(A). "
                "Standard t-structure: (D^{<=0}(A), D^{>=0}(A)) where D^{<=n}(A) = complexes "
                "with H^k = 0 for k > n, D^{>=n}(A) = complexes with H^k = 0 for k < n. "
                "Heart = D^{<=0} ∩ D^{>=0} ≅ A (via A -> concentrated-in-degree-0 complex). "
                "Ext groups: Ext^n_A(M, N) = Hom_{D(A)}(M, N[n]) for objects M, N ∈ A ⊂ D(A). "
                "The derived category 'upgrades' classical homological algebra: injective "
                "resolutions compute Hom_{D(A)} via the formula Hom_{D(A)}(M, N) = "
                "Hom_{K(A)}(M, I^bullet) where M -> I^bullet is an injective resolution."
            ),
            chapter_targets=("13", "23", "36"),
        ),
        DerivedCategoryProfile(
            key="bounded_derived_coherent",
            display_name="D^b(Coh(X)) — bounded derived category of coherent sheaves",
            category_type="derived_category",
            base_category="coherent_sheaves",
            has_t_structure=True,
            is_enhanced=True,
            has_semiorthogonal_decomp=True,
            presentation_layer="main_text",
            focus=(
                "D^b(Coh(X)) for a smooth proper variety X over a field k is the central "
                "object of derived algebraic geometry and homological mirror symmetry. "
                "Objects: bounded complexes ... -> F^{n-1} -> F^n -> F^{n+1} -> ... "
                "of coherent sheaves on X with F^n = 0 for |n| >> 0. "
                "Morphisms: Hom_{D^b(Coh)}(F, G) = colim_n Hom_{K^b(Coh)}(F', G) over all "
                "quasi-isomorphisms F' -> F (localization). "
                "For smooth X: every object of D^b(Coh(X)) is quasi-isomorphic to a bounded "
                "complex of locally free sheaves (vector bundles). "
                "Serre duality in D^b(Coh): Hom(F, G) ≅ Hom(G, F ⊗ omega_X[dim X])^* "
                "(derived Serre duality, Verdier duality for the structure sheaf). "
                "Serre functor: S_X = (- ⊗ omega_X)[dim X] is a Serre functor for D^b(Coh(X)) "
                "when X is smooth proper: Hom(F, G) ≅ Hom(G, S_X F)^* functorially. "
                "Bondal-Van den Bergh theorem (2003): D^b(Coh(X)) for smooth proper X is "
                "equivalent (as a triangulated category) to the derived category D^b(A-mod) "
                "for a finite-dimensional algebra A (a 'tilting generator'). "
                "dg-enhancement: D^b(Coh(X)) has a unique dg-enhancement (Lunts-Orlov 2010) "
                "for smooth proper X, given by the dg-category of bounded complexes of "
                "locally free sheaves with dg-Hom complexes. "
                "Orlov's formula: for a projective bundle P(E) -> X, "
                "D^b(Coh(P(E))) = ⟨p^*(D^b(Coh(X))) ⊗ O(i) : 0 <= i <= rank(E)-1⟩. "
                "Homological mirror symmetry (Kontsevich 1994): for mirror pairs (X, X^vee), "
                "D^b(Coh(X)) ≅ D^b(Fuk(X^vee)) (derived category of coherent sheaves = "
                "derived Fukaya category of the mirror)."
            ),
            chapter_targets=("13", "23", "36"),
        ),
        DerivedCategoryProfile(
            key="perverse_sheaves_bbd",
            display_name="Perv(X) — perverse sheaves as heart of BBD t-structure",
            category_type="perverse",
            base_category="constructible_sheaves",
            has_t_structure=True,
            is_enhanced=False,
            has_semiorthogonal_decomp=False,
            presentation_layer="main_text",
            focus=(
                "Perverse sheaves (Beilinson-Bernstein-Deligne 1982) are objects of the derived "
                "category D^b_c(X) (constructible complexes on a stratified space X) lying in "
                "the heart of a non-standard t-structure — the perverse t-structure. "
                "Setup: let X be a complex algebraic variety with a stratification X = ⊔ S_alpha "
                "by smooth locally closed strata, each of complex dimension d_alpha. "
                "Perverse t-structure (middle perversity): "
                "D^{p,<=0} = {F : H^k(i_{S_alpha}^* F) = 0 for k > -d_alpha for all alpha} "
                "D^{p,>=0} = {F : H^k(i_{S_alpha}^! F) = 0 for k < -d_alpha for all alpha} "
                "The heart Perv(X) = D^{p,<=0} ∩ D^{p,>=0} is the abelian category of perverse "
                "sheaves. Simple perverse sheaves: IC(S, L) = j_{!*}(L[d_S]) for an irreducible "
                "stratum S with local system L (the intermediate or middle extension). "
                "Decomposition theorem (BBD 1982, de Cataldo-Migliorini): for a proper morphism "
                "f: X -> Y of complex algebraic varieties, Rf_*(IC_X) decomposes as a direct "
                "sum of shifts of IC sheaves: Rf_*(IC_X) ≅ ⊕_i ^pH^i(Rf_*(IC_X))[-i] "
                "(the BBD decomposition theorem). This is the derived category formulation "
                "of the decomposition of the cohomology of a fibration. "
                "Intersection cohomology: IH^k(X; L) = H^k(X; IC(X,L)) — the intersection "
                "cohomology of X with coefficients in L. For X smooth: IC(X, Q_X) = Q_X[dim X] "
                "and IH^k(X) = H^k(X). "
                "Nearby/vanishing cycles: for f: X -> A^1, the nearby cycle functor Psi_f and "
                "vanishing cycle functor Phi_f are perverse-t-exact: they send perverse sheaves "
                "to perverse sheaves (after a shift adjustment). "
                "Kazhdan-Lusztig conjecture (proved by BBD): multiplicities of simple modules "
                "in Verma modules equal values of Kazhdan-Lusztig polynomials, computed via "
                "intersection cohomology of Schubert varieties."
            ),
            chapter_targets=("23", "36"),
        ),
        DerivedCategoryProfile(
            key="exceptional_collection_projective_space",
            display_name="Beilinson's exceptional collection on P^n — full SOD",
            category_type="derived_category",
            base_category="coherent_sheaves",
            has_t_structure=True,
            is_enhanced=True,
            has_semiorthogonal_decomp=True,
            presentation_layer="main_text",
            focus=(
                "Beilinson's exceptional collection (1978) is the foundational result in the "
                "semiorthogonal decomposition (SOD) of derived categories of smooth varieties. "
                "Theorem (Beilinson 1978): D^b(Coh(P^n)) = ⟨O, O(1), O(2), ..., O(n)⟩ "
                "is a full strong exceptional collection. "
                "Exceptionality: Hom(O(i), O(j)[k]) = H^k(P^n, O(j-i)). "
                "By Kodaira vanishing and the cohomology of projective space: "
                "H^k(P^n, O(m)) = 0 for k ≠ 0, n unless m ∈ [-n-1+k·0, ..], so "
                "Hom(O(i), O(j)[k]) = 0 for k ≠ 0 and all i <= j, and "
                "Hom(O(i), O(i)) = k (the base field), confirming exceptionality. "
                "Semiorthogonality: Hom(O(j), O(i)[k]) = H^k(P^n, O(i-j)) = 0 for j > i "
                "and all k (by Serre duality + Kodaira vanishing: for i < j, H^k(O(i-j)) = 0). "
                "Fullness: O(0), ..., O(n) generate D^b(Coh(P^n)) — proved via the Beilinson "
                "spectral sequence, which resolves every coherent sheaf F using the complex "
                "H^k(F(-k)) ⊗ O(k) -> H^k(F(k-n)) ⊗ O(n-k). "
                "Tilting generator: T = O ⊕ O(1) ⊕ ... ⊕ O(n) is a tilting generator with "
                "End(T) = A_n (the Beilinson quiver algebra). D^b(Coh(P^n)) ≅ D^b(A_n-mod). "
                "Mutations: the braid group B_{n+1} acts on the set of full exceptional "
                "collections by mutations L_i (left mutation) and R_i (right mutation). "
                "Alternative collections: ⟨Omega^k(k) : 0 <= k <= n⟩ (Kapranov's collection "
                "using tautological bundles on Grassmannians generalizes Beilinson). "
                "Generalization: Orlov's projective bundle formula extends SOD to P(E) -> X "
                "for any vector bundle E on X."
            ),
            chapter_targets=("13", "23", "36"),
        ),
        DerivedCategoryProfile(
            key="fourier_mukai_transform",
            display_name="Fourier-Mukai transform — integral functor between derived categories",
            category_type="derived_category",
            base_category="coherent_sheaves",
            has_t_structure=False,
            is_enhanced=True,
            has_semiorthogonal_decomp=False,
            presentation_layer="selected_block",
            focus=(
                "The Fourier-Mukai transform (Mukai 1981) is a derived categorical analogue of "
                "the classical Fourier transform, providing equivalences between derived categories "
                "of non-isomorphic varieties. "
                "Construction: for smooth proper varieties X, Y over k and a 'kernel' object "
                "P ∈ D^b(Coh(X × Y)), the Fourier-Mukai functor is "
                "Phi_P: D^b(Coh(X)) -> D^b(Coh(Y)), "
                "Phi_P(F) = Rp_{Y*}(P ⊗^L p_X^*(F)) "
                "where p_X: X × Y -> X and p_Y: X × Y -> Y are projections. "
                "Orlov representability (1996): every fully faithful exact functor between "
                "D^b(Coh(X)) and D^b(Coh(Y)) (for smooth proper X, Y with derived-equivalent "
                "categories) is isomorphic to Phi_P for a unique P ∈ D^b(Coh(X × Y)). "
                "Mukai's abelian variety example: for an abelian variety A over k, let L "
                "be the Poincaré line bundle on A × A^vee. Then Phi_L: D^b(Coh(A)) -> "
                "D^b(Coh(A^vee)) is an equivalence of triangulated categories. This is the "
                "derived Fourier transform; it exchanges the structure sheaf O_A with the "
                "skyscraper sheaf k(0) at the origin: Phi_L(O_A) = k(0)[g] (g = dim A). "
                "Bondal-Orlov criterion for equivalence: Phi_P is an equivalence iff "
                "(i) P has a right adjoint Phi_{P^R} and (ii) the 'spanning' and "
                "'orthogonality' conditions: "
                "Hom(Phi_P(k(x)), Phi_P(k(y))[n]) = delta_{x,y}·delta_{n,0}·k for points x,y. "
                "K3 surfaces: for K3 surfaces X, Y, D^b(Coh(X)) ≅ D^b(Coh(Y)) iff X and Y are "
                "Fourier-Mukai partners (in the same Mukai lattice orbit). The number of FM "
                "partners of a K3 surface is finite and controlled by the Picard number. "
                "Applications: moduli of sheaves, mirror symmetry, autoequivalences of D^b(X) "
                "(e.g., the spherical twist T_E for a spherical object E ∈ D^b(X))."
            ),
            chapter_targets=("23", "36"),
        ),
        DerivedCategoryProfile(
            key="semiorthogonal_decomposition",
            display_name="SOD: D^b(X) = ⟨A_1,...,A_n⟩ — semiorthogonal decomposition",
            category_type="derived_category",
            base_category="triangulated",
            has_t_structure=False,
            is_enhanced=True,
            has_semiorthogonal_decomp=True,
            presentation_layer="selected_block",
            focus=(
                "A semiorthogonal decomposition (SOD) of a triangulated category T is a "
                "filtration of T into 'orthogonal pieces', generalizing direct sum decompositions. "
                "Definition: T = ⟨A_1,...,A_n⟩ is a SOD if: "
                "(i) Hom_{T}(a_i, a_j) = 0 for all a_i ∈ A_i, a_j ∈ A_j with i > j; "
                "(ii) for every object X ∈ T there is a filtration (the 'canonical filtration') "
                "0 = X_0 -> X_1 -> ... -> X_n = X with cone(X_{k-1} -> X_k) ∈ A_k. "
                "The components A_i are admissible subcategories: their inclusion i_k: A_k -> T "
                "has both a left adjoint i_k^! and a right adjoint i_k^* (projections). "
                "The projection X |-> i_k^*(X) extracts the 'A_k-component' of X. "
                "Exceptional collection SOD: ⟨E_1,...,E_m⟩ for a full exceptional collection "
                "{E_i} generates a SOD with A_i = ⟨E_i⟩ ≅ D^b(Vect_k) (k-linear). "
                "Orlov's formula for blowups: if X~ -> X is the blowup of X along a smooth "
                "center Z of codimension c, then "
                "D^b(Coh(X~)) = ⟨i_*(D^b(Coh(Z))), i_*(D^b(Coh(Z))) ⊗ O(-1), ..., "
                "                 i_*(D^b(Coh(Z))) ⊗ O(-(c-2)), p^*(D^b(Coh(X)))⟩ "
                "(Orlov 1993 — the blowup formula). "
                "Kuznetsov's HPD: homological projective duality (Kuznetsov 2007) provides "
                "SODs for linear sections of homogeneous spaces. For the Pfaffian-Grassmannian "
                "duality: a SOD of D^b(Gr(2,n)) and D^b(Pf(2,n)) have equivalent 'primitive' "
                "components (Rennemo-Segal). "
                "Non-existence of SOD: for a variety with trivial canonical bundle (e.g., K3, "
                "CY3, abelian variety), a full exceptional collection cannot exist (the Serre "
                "functor S = [dim X] would have finite order, contradicting Ext finiteness). "
                "Instead, D^b(K3) = ⟨A_K3⟩ is indecomposable as a category."
            ),
            chapter_targets=("13", "23"),
        ),
        DerivedCategoryProfile(
            key="dg_enhancement_uniqueness",
            display_name="dg-enhancement — pre-triangulated dg-category enhancing D^b(Coh(X))",
            category_type="triangulated",
            base_category="dg_category",
            has_t_structure=False,
            is_enhanced=True,
            has_semiorthogonal_decomp=False,
            presentation_layer="selected_block",
            focus=(
                "A dg-enhancement of a k-linear triangulated category T is a pre-triangulated "
                "dg-category A (a dg-category where the homotopy category H^0(A) carries a "
                "canonical triangulated structure) together with a triangulated equivalence "
                "H^0(A) ≅ T. The dg-structure upgrades the triangulated structure to one "
                "with coherent homotopies, enabling the use of dg-algebra techniques. "
                "dg-category A: a k-linear category where Hom_A(X, Y) is a cochain complex "
                "of k-modules, composition is a chain map Hom(Y,Z) ⊗ Hom(X,Y) -> Hom(X,Z), "
                "and associativity/unitality hold strictly. "
                "Pre-triangulated dg-category: A has 'twisted complexes' — formal mapping cones "
                "and shifts, making H^0(A) triangulated. "
                "Canonical dg-enhancement of D^b(Coh(X)): for a smooth algebraic variety X, "
                "take A = the dg-category of bounded complexes of locally free sheaves on X "
                "with dg-Hom complexes Hom^bullet(E, F) = Gamma(X, RHom^bullet(E, F)). "
                "The cohomology H^0(A) ≅ D^b(Coh(X)) as triangulated categories. "
                "Uniqueness theorem (Lunts-Orlov 2010): for smooth proper X over a perfect "
                "field, the dg-enhancement of D^b(Coh(X)) is unique up to quasi-equivalence. "
                "Similarly, Perf(X) (perfect complexes) has a unique dg-enhancement. "
                "A∞-categories: a generalization of dg-categories where composition is "
                "associative only up to a coherent sequence of higher homotopies (A∞-structure "
                "maps m_n: Hom^⊗n -> Hom[2-n] with the A∞-relations). Every dg-category "
                "is an A∞-category with m_n = 0 for n >= 3. "
                "Stable ∞-categories (Lurie): the ∞-categorical enhancement of triangulated "
                "categories. Every stable ∞-category has a natural triangulated structure on "
                "its homotopy category. The ∞-category of spectra is the universal stable "
                "∞-category (Blumberg-Gepner-Tabuada 2013)."
            ),
            chapter_targets=("13", "23", "36"),
        ),
    )


def derived_category_layer_summary() -> dict[str, int]:
    """Return a count of profiles by presentation_layer."""
    return dict(Counter(
        p.presentation_layer for p in get_named_derived_category_profiles()
    ))


def derived_category_chapter_index() -> dict[str, tuple[str, ...]]:
    """Return a mapping from chapter number to profile keys."""
    chapter_map: dict[str, list[str]] = {}
    for p in get_named_derived_category_profiles():
        for chapter in p.chapter_targets:
            chapter_map.setdefault(chapter, []).append(p.key)
    return {chapter: tuple(keys) for chapter, keys in sorted(chapter_map.items())}


def derived_category_type_index() -> dict[str, tuple[str, ...]]:
    """Return a mapping from category_type to profile keys."""
    index: dict[str, list[str]] = {}
    for p in get_named_derived_category_profiles():
        index.setdefault(p.category_type, []).append(p.key)
    return {k: tuple(v) for k, v in sorted(index.items())}


# ---------------------------------------------------------------------------
# Core analysis functions
# ---------------------------------------------------------------------------

def is_triangulated(space: Any) -> Result:
    """Check whether the category is triangulated.

    A triangulated category has a shift functor [1] and distinguished triangles
    A -> B -> C -> A[1] satisfying axioms TR1-TR4 (rotation, mapping cone existence,
    morphism of triangles, octahedral axiom). Every derived category D(A) and homotopy
    category K(A) is triangulated.

    Decision layers
    ---------------
    1. Explicit 'triangulated_category' or 'distinguished_triangle' tag -> true.
    2. Derived category or homotopy category tags -> true.
    3. Non-triangulated (plain abelian, plain additive) tags -> false.
    4. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, TRIANGULATED_STRUCTURE_TAGS):
        witness = next(t for t in tags if t in TRIANGULATED_STRUCTURE_TAGS)
        return Result.true(
            mode="theorem",
            value="triangulated",
            justification=[
                f"Tag {witness!r}: the category is triangulated — it has a shift functor [1] "
                "and a class of distinguished triangles A -> B -> C -> A[1] satisfying "
                "TR1-TR4 (rotation, morphism extension, octahedral axiom).",
            ],
            metadata={**base, "criterion": "explicit_triangulated", "witness": witness},
        )

    derived_and_homotopy = {
        "derived_category", "homotopy_category", "db_coh", "bounded_derived",
        "unbounded_derived", "stable_model_category", "stable_infinity_category",
        "chain_complexes", "derived_functor_category",
    }
    if _matches_any(tags, derived_and_homotopy):
        witness = next(t for t in tags if t in derived_and_homotopy)
        return Result.true(
            mode="theorem",
            value="triangulated",
            justification=[
                f"Tag {witness!r}: derived/homotopy categories are canonically triangulated. "
                "D(A) and K(A) carry the triangulated structure with shift = degree shift [1] "
                "and distinguished triangles from mapping cones.",
            ],
            metadata={**base, "criterion": "derived_implies_triangulated", "witness": witness},
        )

    not_triangulated = {
        "abelian_category", "not_triangulated", "additive_only",
        "plain_module_category",
    }
    if _matches_any(tags, not_triangulated):
        blocking = next(t for t in tags if t in not_triangulated)
        return Result.false(
            mode="theorem",
            value="triangulated",
            justification=[
                f"Tag {blocking!r}: plain abelian and additive categories are not triangulated. "
                "An abelian category A embeds into D(A) but is not itself triangulated — "
                "it lacks the shift functor and distinguished triangles.",
            ],
            metadata={**base, "criterion": "not_triangulated"},
        )

    return Result.unknown(
        mode="symbolic",
        value="triangulated",
        justification=[
            "Insufficient tags to determine triangulated structure. "
            "Supply tags such as 'triangulated_category', 'distinguished_triangle', "
            "'derived_category', 'homotopy_category', or 'abelian_category'.",
        ],
        metadata={**base, "criterion": None},
    )


def has_t_structure(space: Any) -> Result:
    """Check whether the triangulated category carries a t-structure.

    A t-structure (BBD 1982) on a triangulated category T is a pair of full subcategories
    (T^{<=0}, T^{>=0}) with: (i) T^{<=0}[1] ⊂ T^{<=0}; (ii) Hom(T^{<=0}, T^{>=1}) = 0;
    (iii) every object fits in a truncation triangle tau^{<=0}A -> A -> tau^{>=1}A.
    The heart C = T^{<=0} ∩ T^{>=0} is an abelian category.

    Decision layers
    ---------------
    1. Explicit 't_structure' or 'heart_of_t_structure' tag -> true.
    2. Derived category tags (always have standard t-structure) -> true.
    3. Perverse sheaves tags -> true (perverse t-structure).
    4. Triangulated-only without t-structure tags -> unknown.
    5. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, T_STRUCTURE_TAGS):
        witness = next(t for t in tags if t in T_STRUCTURE_TAGS)
        return Result.true(
            mode="theorem",
            value="t_structure",
            justification=[
                f"Tag {witness!r}: a t-structure is present. The heart C = T^{{<=0}} ∩ T^{{>=0}} "
                "is an abelian category; the cohomology objects H^n(A) = tau^{{>=0}}tau^{{<=0}}(A[-n]) "
                "lie in C.",
            ],
            metadata={**base, "criterion": "explicit_t_structure", "witness": witness},
        )

    if _matches_any(tags, PERVERSE_SHEAF_TAGS):
        witness = next(t for t in tags if t in PERVERSE_SHEAF_TAGS)
        return Result.true(
            mode="theorem",
            value="t_structure",
            justification=[
                f"Tag {witness!r}: perverse sheaves are defined as the heart of the BBD "
                "perverse t-structure on D^b_c(X). The perverse t-structure is the non-standard "
                "t-structure with truncation defined by half-perversity conditions on strata.",
            ],
            metadata={**base, "criterion": "perverse_t_structure", "witness": witness},
        )

    if _matches_any(tags, DERIVED_CATEGORY_TAGS):
        witness = next(t for t in tags if t in DERIVED_CATEGORY_TAGS)
        return Result.true(
            mode="theorem",
            value="t_structure",
            justification=[
                f"Tag {witness!r}: every derived category D(A) carries the standard t-structure "
                "with D^{{<=0}} = complexes with H^k = 0 for k > 0, D^{{>=0}} = complexes with "
                "H^k = 0 for k < 0. Heart ≅ A (the original abelian category).",
            ],
            metadata={**base, "criterion": "standard_t_structure", "witness": witness},
        )

    no_t_structure = {
        "no_t_structure", "homotopy_category_only",
        "k_theory_category", "spectral_category",
    }
    if _matches_any(tags, no_t_structure):
        blocking = next(t for t in tags if t in no_t_structure)
        return Result.false(
            mode="theorem",
            value="t_structure",
            justification=[
                f"Tag {blocking!r}: no t-structure is present or known. "
                "The homotopy category K(A) (before deriving) is triangulated but does NOT "
                "have a natural t-structure with heart A (only D(A) does).",
            ],
            metadata={**base, "criterion": "no_t_structure"},
        )

    return Result.unknown(
        mode="symbolic",
        value="t_structure",
        justification=[
            "Insufficient tags to determine t-structure. "
            "Supply tags such as 't_structure', 'heart_of_t_structure', "
            "'derived_category', 'perverse_sheaves', or 'no_t_structure'.",
        ],
        metadata={**base, "criterion": None},
    )


def has_semiorthogonal_decomposition(space: Any) -> Result:
    """Check whether the derived category admits a semiorthogonal decomposition.

    A SOD T = ⟨A_1,...,A_n⟩ requires semiorthogonality (Hom(A_i, A_j) = 0 for i > j)
    and generation. Smooth varieties with ample or anti-ample canonical bundle often admit
    SODs via exceptional collections. Varieties with trivial canonical bundle (CY, K3,
    abelian) do NOT admit full exceptional collections (by Serre functor rigidity).

    Decision layers
    ---------------
    1. Explicit 'semiorthogonal_decomposition' or 'exceptional_collection' tag -> true.
    2. Projective space / Beilinson collection tags -> true.
    3. Trivial canonical bundle (CY, K3, abelian variety) -> false (no full SOD).
    4. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, SEMIORTHOGONAL_TAGS):
        witness = next(t for t in tags if t in SEMIORTHOGONAL_TAGS)
        return Result.true(
            mode="theorem",
            value="semiorthogonal_decomposition",
            justification=[
                f"Tag {witness!r}: a semiorthogonal decomposition exists. "
                "The category T = ⟨A_1,...,A_n⟩ with Hom(A_i, A_j) = 0 for i > j "
                "and each A_i an admissible subcategory.",
            ],
            metadata={**base, "criterion": "explicit_sod", "witness": witness},
        )

    projective_space = {
        "projective_space", "beilinson_collection", "line_bundle_collection",
        "fano_variety", "del_pezzo_surface",
    }
    if _matches_any(tags, projective_space):
        witness = next(t for t in tags if t in projective_space)
        return Result.true(
            mode="theorem",
            value="semiorthogonal_decomposition",
            justification=[
                f"Tag {witness!r}: Fano varieties and projective spaces admit full exceptional "
                "collections — Beilinson (P^n: O, O(1), ..., O(n)), Kapranov (Grassmannians), "
                "and many del Pezzo surfaces. The SOD T = ⟨E_1,...,E_n⟩ follows.",
            ],
            metadata={**base, "criterion": "fano_exceptional_collection", "witness": witness},
        )

    no_sod = {
        "trivial_canonical_bundle", "k3_surface", "calabi_yau",
        "abelian_variety_sheaves", "no_exceptional_objects",
    }
    if _matches_any(tags, no_sod):
        blocking = next(t for t in tags if t in no_sod)
        return Result.false(
            mode="theorem",
            value="semiorthogonal_decomposition",
            justification=[
                f"Tag {blocking!r}: varieties with trivial canonical bundle do NOT admit "
                "full exceptional collections. The Serre functor S = [dim X] acts trivially "
                "on any exceptional object E: Hom(E, E[dim X]) = Hom(E, E)^* ≠ 0, "
                "contradicting the vanishing required for an exceptional collection.",
            ],
            metadata={**base, "criterion": "no_sod_trivial_canonical"},
        )

    return Result.unknown(
        mode="symbolic",
        value="semiorthogonal_decomposition",
        justification=[
            "Insufficient tags to determine semiorthogonal decomposition. "
            "Supply tags such as 'semiorthogonal_decomposition', 'exceptional_collection', "
            "'projective_space', 'beilinson_collection', 'k3_surface', or 'calabi_yau'.",
        ],
        metadata={**base, "criterion": None},
    )


def is_dg_enhanced(space: Any) -> Result:
    """Check whether the triangulated category admits a dg-enhancement.

    A dg-enhancement is a pre-triangulated dg-category A with H^0(A) ≅ T. Every
    algebraic triangulated category (arising from a stable model category) admits a
    dg-enhancement. Lunts-Orlov (2010): D^b(Coh(X)) for smooth proper X has a unique
    dg-enhancement. The topological stable homotopy category SH does NOT admit a dg-
    enhancement (it is not algebraic in the sense of Schwede).

    Decision layers
    ---------------
    1. Explicit 'dg_enhancement' or 'dg_category' tag -> true.
    2. Derived category of coherent sheaves or modules (algebraic) -> true.
    3. Topological stable homotopy category -> false.
    4. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, DG_ENHANCEMENT_TAGS):
        witness = next(t for t in tags if t in DG_ENHANCEMENT_TAGS)
        return Result.true(
            mode="theorem",
            value="dg_enhanced",
            justification=[
                f"Tag {witness!r}: the category has a dg-enhancement — a pre-triangulated "
                "dg-category A with H^0(A) ≅ T. For smooth proper varieties, uniqueness "
                "holds by Lunts-Orlov 2010.",
            ],
            metadata={**base, "criterion": "explicit_dg_enhancement", "witness": witness},
        )

    algebraic = {
        "derived_category", "db_coh", "bounded_derived",
        "derived_module_category", "chain_complexes",
    }
    if _matches_any(tags, algebraic):
        witness = next(t for t in tags if t in algebraic)
        return Result.true(
            mode="theorem",
            value="dg_enhanced",
            justification=[
                f"Tag {witness!r}: algebraic triangulated categories (arising from abelian "
                "categories via derived construction) admit dg-enhancements. "
                "D(A) for any abelian A has the dg-enhancement given by the dg-category of "
                "complexes with dg-Hom complexes.",
            ],
            metadata={**base, "criterion": "algebraic_dg_enhancement", "witness": witness},
        )

    no_dg = {
        "stable_homotopy_category", "topological_sh",
        "no_dg_enhancement", "not_algebraic_triangulated",
    }
    if _matches_any(tags, no_dg):
        blocking = next(t for t in tags if t in no_dg)
        return Result.false(
            mode="theorem",
            value="dg_enhanced",
            justification=[
                f"Tag {blocking!r}: the topological stable homotopy category SH does NOT "
                "admit a dg-enhancement (Schwede 2004): it is not 'algebraic' in the sense "
                "that it cannot be the homotopy category of a stable dg-category. "
                "The obstruction is the non-triviality of Toda brackets in SH.",
            ],
            metadata={**base, "criterion": "no_dg_enhancement"},
        )

    return Result.unknown(
        mode="symbolic",
        value="dg_enhanced",
        justification=[
            "Insufficient tags to determine dg-enhancement. "
            "Supply tags such as 'dg_enhancement', 'dg_category', 'derived_category', "
            "'db_coh', 'stable_homotopy_category', or 'no_dg_enhancement'.",
        ],
        metadata={**base, "criterion": None},
    )


def classify_derived_category(space: Any) -> dict[str, Any]:
    """Classify the derived category by its structural features.

    Keys
    ----
    derived_class : str
        One of ``"full_geometric"``, ``"algebraic_enhanced"``, ``"perverse_t"``,
        ``"triangulated_basic"``, ``"general"``, ``"unknown"``.
    is_triangulated : Result
    has_t_structure : Result
    has_semiorthogonal_decomposition : Result
    is_dg_enhanced : Result
    key_properties : list[str]
    representation : str
    tags : list[str]
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)

    triang_r = is_triangulated(space)
    t_str_r = has_t_structure(space)
    sod_r = has_semiorthogonal_decomposition(space)
    dg_r = is_dg_enhanced(space)

    if sod_r.is_true and dg_r.is_true and t_str_r.is_true:
        derived_class = "full_geometric"
    elif dg_r.is_true and t_str_r.is_true:
        derived_class = "algebraic_enhanced"
    elif _matches_any(tags, PERVERSE_SHEAF_TAGS):
        derived_class = "perverse_t"
    elif triang_r.is_true and t_str_r.is_true:
        derived_class = "triangulated_basic"
    elif triang_r.is_true:
        derived_class = "general"
    else:
        derived_class = "unknown"

    key_properties: list[str] = []
    if triang_r.is_true:
        key_properties.append("triangulated")
    if t_str_r.is_true:
        key_properties.append("t_structure")
    if t_str_r.is_false:
        key_properties.append("no_t_structure")
    if sod_r.is_true:
        key_properties.append("semiorthogonal_decomposition")
    if sod_r.is_false:
        key_properties.append("no_full_exceptional_collection")
    if dg_r.is_true:
        key_properties.append("dg_enhanced")
    if dg_r.is_false:
        key_properties.append("not_dg_enhanceable")
    if _matches_any(tags, PERVERSE_SHEAF_TAGS):
        key_properties.append("perverse_sheaves")
    if _matches_any(tags, DERIVED_FUNCTOR_TAGS):
        key_properties.append("derived_functors")
    if _matches_any(tags, BONDAL_ORLOV_TAGS):
        key_properties.append("fourier_mukai_equivalence")
    if _matches_any(tags, SEMIORTHOGONAL_TAGS):
        key_properties.append("exceptional_collection")

    return {
        "derived_class": derived_class,
        "is_triangulated": triang_r,
        "has_t_structure": t_str_r,
        "has_semiorthogonal_decomposition": sod_r,
        "is_dg_enhanced": dg_r,
        "key_properties": key_properties,
        "representation": representation,
        "tags": sorted(tags),
    }


def derived_category_profile(space: Any) -> dict[str, Any]:
    """Full derived category profile combining classification and named examples.

    Keys
    ----
    classification : dict
        Output of :func:`classify_derived_category`.
    named_profiles : tuple[DerivedCategoryProfile, ...]
        Registry of canonical derived category theory examples.
    layer_summary : dict[str, int]
        Profile count by presentation_layer.
    """
    return {
        "classification": classify_derived_category(space),
        "named_profiles": get_named_derived_category_profiles(),
        "layer_summary": derived_category_layer_summary(),
    }


__all__ = [
    "DerivedCategoryProfile",
    "DERIVED_CATEGORY_TAGS",
    "TRIANGULATED_STRUCTURE_TAGS",
    "T_STRUCTURE_TAGS",
    "DERIVED_FUNCTOR_TAGS",
    "SEMIORTHOGONAL_TAGS",
    "DG_ENHANCEMENT_TAGS",
    "BONDAL_ORLOV_TAGS",
    "PERVERSE_SHEAF_TAGS",
    "get_named_derived_category_profiles",
    "derived_category_layer_summary",
    "derived_category_chapter_index",
    "derived_category_type_index",
    "is_triangulated",
    "has_t_structure",
    "has_semiorthogonal_decomposition",
    "is_dg_enhanced",
    "classify_derived_category",
    "derived_category_profile",
]
