"""Small ready-to-use examples for finite and infinite topology.

The examples in this module are deliberately modest. They are designed to be
useful for notebooks, classroom experiments, and quick internal tests.
"""

from __future__ import annotations

from collections.abc import Iterable
from itertools import combinations
from typing import Any

from .finite_spaces import FiniteTopologicalSpace
from .infinite_examples import (
    basis_defined_second_countable,
    closed_unit_interval_metric,
    infinite_examples_catalog,
    integers_discrete,
    lower_limit_line_like,
    naturals_cofinite,
    naturals_discrete,
    rationals_metric,
    real_line_metric,
    real_line_order_topology,
    real_plane_metric,
    reals_cocountable,
    reals_indiscrete,
    sorgenfrey_line_like,
    upper_limit_line_like,
)


def empty_space() -> FiniteTopologicalSpace:
    return FiniteTopologicalSpace(
        carrier=(),
        topology=[set()],
        metadata={'description': 'The empty topological space.'},
    )


def singleton_space(label: Any = 'x') -> FiniteTopologicalSpace:
    return FiniteTopologicalSpace(
        carrier=(label,),
        topology=[set(), {label}],
        metadata={'description': 'A one-point space.'},
    )


def two_point_discrete_space() -> FiniteTopologicalSpace:
    return FiniteTopologicalSpace(
        carrier=('a', 'b'),
        topology=[set(), {'a'}, {'b'}, {'a', 'b'}],
        metadata={'description': 'The two-point discrete space.'},
    )


def two_point_indiscrete_space() -> FiniteTopologicalSpace:
    return FiniteTopologicalSpace(
        carrier=('a', 'b'),
        topology=[set(), {'a', 'b'}],
        metadata={'description': 'The two-point indiscrete space.'},
    )


def sierpinski_space() -> FiniteTopologicalSpace:
    return FiniteTopologicalSpace(
        carrier=(0, 1),
        topology=[set(), {1}, {0, 1}],
        metadata={'description': 'The Sierpiński space.'},
    )


def finite_chain_space(n: int = 3) -> FiniteTopologicalSpace:
    if n <= 0:
        raise ValueError('n must be positive.')
    points = tuple(range(1, n + 1))
    topology = [set()]
    for k in range(1, n + 1):
        topology.append(set(points[:k]))
    topology.append(set(points))
    normalized = []
    seen = set()
    for open_set in topology:
        frozen = frozenset(open_set)
        if frozen not in seen:
            seen.add(frozen)
            normalized.append(set(open_set))
    return FiniteTopologicalSpace(
        carrier=points,
        topology=normalized,
        metadata={'description': f'A finite Alexandrov chain space on {n} points.'},
    )


def partition_space(blocks: Iterable[Iterable[Any]]) -> FiniteTopologicalSpace:
    block_sets = tuple(frozenset(block) for block in blocks)
    points = tuple(sorted(set().union(*block_sets), key=repr))
    topology = [set()]
    for r in range(1, len(block_sets) + 1):
        for family in combinations(block_sets, r):
            topology.append(set().union(*family))
    topology.append(set(points))
    normalized = []
    seen = set()
    for open_set in topology:
        frozen = frozenset(open_set)
        if frozen not in seen:
            seen.add(frozen)
            normalized.append(set(open_set))
    return FiniteTopologicalSpace(
        carrier=points,
        topology=normalized,
        metadata={'description': 'A finite partition-topology space.'},
    )


def finite_examples_catalog() -> dict[str, dict[str, object]]:
    return {
        'empty_space': {'constructor': empty_space, 'description': 'The empty space.'},
        'singleton_space': {'constructor': singleton_space, 'description': 'A one-point space.'},
        'two_point_discrete_space': {'constructor': two_point_discrete_space, 'description': 'A finite Hausdorff discrete space.'},
        'two_point_indiscrete_space': {'constructor': two_point_indiscrete_space, 'description': 'A finite indiscrete connected compact space.'},
        'sierpinski_space': {'constructor': sierpinski_space, 'description': 'The standard two-point T0 non-T1 example.'},
        'finite_chain_space': {'constructor': finite_chain_space, 'description': 'A finite Alexandrov-chain style example.'},
        'partition_space': {'constructor': partition_space, 'description': 'A topology generated by partition blocks.'},
    }


def examples_catalog() -> dict[str, dict[str, dict[str, object]]]:
    return {
        'finite': finite_examples_catalog(),
        'infinite': infinite_examples_catalog(),
    }


__all__ = [
    'empty_space',
    'singleton_space',
    'two_point_discrete_space',
    'two_point_indiscrete_space',
    'sierpinski_space',
    'finite_chain_space',
    'partition_space',
    'finite_examples_catalog',
    'examples_catalog',
    'naturals_discrete',
    'integers_discrete',
    'naturals_cofinite',
    'reals_indiscrete',
    'reals_cocountable',
    'real_line_metric',
    'real_line_order_topology',
    'rationals_metric',
    'closed_unit_interval_metric',
    'real_plane_metric',
    'lower_limit_line_like',
    'upper_limit_line_like',
    'sorgenfrey_line_like',
    'basis_defined_second_countable',
]
