"""Finite filter and filter-base helpers for the topology book ecosystem.

The module is intentionally small: it gives Chapter 20 a testable finite
bridge without pretending to solve arbitrary symbolic filter problems.

A filter base is a non-empty family closed under finite intersections in
the sense that for any two base elements B1, B2 there exists B3 in the base
with B3 ⊆ B1 ∩ B2.  The generated filter consists of all supersets of
base elements.

Filter convergence: a filter F converges to x if every neighborhood of x
belongs to F (i.e. the neighborhood filter of x is a subset of F).

This module provides:
  - ``is_filter_base``       -- check the filter-base axioms on a finite family
  - ``generated_filter``     -- build the upward-closure filter from a base
  - ``is_filter``            -- verify the filter axioms directly
  - ``neighborhood_filter_base`` -- extract the open-neighborhood base at a point
  - ``filter_converges_to``  -- check finite filter convergence
  - ``is_finer_filter``      -- compare filters by refinement
  - ``filter_clusters_at``   -- test whether a filter clusters at a point
  - ``filter_cluster_points`` -- compute finite filter cluster/adherent points
  - ``analyze_filter``       -- gather validity, convergence, and cluster data
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any

from .result import Result


class FilterError(ValueError):
    """Raised when a finite filter request has a malformed input shape."""


# ---------------------------------------------------------------------------
# Type aliases
# ---------------------------------------------------------------------------

_Family = tuple[frozenset[Any], ...]


def _normalize_family(sets: Iterable[Iterable[Any]]) -> _Family:
    seen: list[frozenset[Any]] = []
    for s in sets:
        fs = frozenset(s)
        if fs not in seen:
            seen.append(fs)
    return tuple(seen)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def is_filter_base(
    carrier: Iterable[Any],
    family: Iterable[Iterable[Any]],
) -> Result:
    """Check whether *family* is a filter base on *carrier*.

    A family B is a filter base when:
      (B1)  B is non-empty and does not contain the empty set.
      (B2)  For every B1, B2 in B there exists B3 in B with B3 ⊆ B1 ∩ B2.
    """
    carrier_set = frozenset(carrier)
    base = _normalize_family(family)

    metadata: dict[str, Any] = {
        "operator": "is_filter_base",
        "carrier_size": len(carrier_set),
        "family_size": len(base),
    }

    if not base:
        return Result.false(
            mode="exact",
            value=False,
            justification=["A filter base must be non-empty."],
            metadata=metadata,
        )

    if frozenset() in base:
        return Result.false(
            mode="exact",
            value=False,
            justification=["A filter base must not contain the empty set."],
            metadata=metadata,
        )

    failed_outside: list[frozenset[Any]] = [b for b in base if not b.issubset(carrier_set)]
    if failed_outside:
        metadata["elements_outside_carrier"] = [sorted(map(repr, b)) for b in failed_outside]
        return Result.false(
            mode="exact",
            value=False,
            justification=["At least one base element contains points outside the carrier."],
            metadata=metadata,
        )

    failed_pairs: list[tuple[frozenset[Any], frozenset[Any]]] = []
    for b1 in base:
        for b2 in base:
            intersection = b1 & b2
            if not any(b3.issubset(intersection) for b3 in base):
                failed_pairs.append((b1, b2))

    metadata["failed_intersection_pairs"] = len(failed_pairs)

    if failed_pairs:
        return Result.false(
            mode="exact",
            value=False,
            justification=[
                "For at least one pair of base elements the intersection has no base element below it."
            ],
            metadata=metadata,
        )

    return Result.true(
        mode="exact",
        value=True,
        justification=["The family satisfies both filter-base axioms (B1) and (B2)."],
        proof_outline=[
            "Non-emptiness, no-empty-set, and the finite intersection refinement condition"
            " were checked by enumeration."
        ],
        metadata=metadata,
    )


def generated_filter(
    carrier: Iterable[Any],
    base: Iterable[Iterable[Any]],
) -> Result:
    """Build the filter generated by *base* on *carrier*.

    The generated filter is {A ⊆ carrier : ∃ B ∈ base, B ⊆ A}.
    Returns the family as a sorted tuple of frozensets in the result value.
    """
    carrier_set = frozenset(carrier)
    base_family = _normalize_family(base)

    base_check = is_filter_base(carrier_set, base_family)
    if not base_check.is_true:
        return Result.false(
            mode="exact",
            value=False,
            justification=["Cannot generate a filter from an invalid filter base."],
            metadata={"operator": "generated_filter", "base_check": base_check.status},
        )

    # All subsets of the carrier that contain at least one base element
    all_subsets = _powerset(carrier_set)
    filter_sets = tuple(
        s for s in all_subsets
        if s and any(b.issubset(s) for b in base_family)
    )

    return Result.true(
        mode="exact",
        value=filter_sets,
        justification=["The generated filter consists of all carrier subsets that contain at least one base element."],
        proof_outline=[
            "Computed as upward closure of the base within the powerset of the carrier."
        ],
        metadata={
            "operator": "generated_filter",
            "carrier_size": len(carrier_set),
            "base_size": len(base_family),
            "filter_size": len(filter_sets),
        },
    )


def is_filter(
    carrier: Iterable[Any],
    family: Iterable[Iterable[Any]],
) -> Result:
    """Check whether *family* is a filter on *carrier*.

    A filter F satisfies:
      (F1)  ∅ ∉ F.
      (F2)  A, B ∈ F  ⟹  A ∩ B ∈ F.
      (F3)  A ∈ F and A ⊆ B ⊆ carrier  ⟹  B ∈ F.
    """
    carrier_set = frozenset(carrier)
    fam = _normalize_family(family)

    metadata: dict[str, Any] = {
        "operator": "is_filter",
        "carrier_size": len(carrier_set),
        "family_size": len(fam),
    }

    if not fam:
        return Result.false(
            mode="exact",
            value=False,
            justification=["A filter must be non-empty."],
            metadata=metadata,
        )

    # (F1)
    if frozenset() in fam:
        return Result.false(
            mode="exact",
            value=False,
            justification=["(F1) fails: the empty set is in the family."],
            metadata=metadata,
        )

    fam_set = set(fam)

    # (F2) closed under finite intersections
    failed_f2: list[tuple[frozenset[Any], frozenset[Any]]] = []
    for a in fam:
        for b in fam:
            inter = a & b
            if inter not in fam_set:
                failed_f2.append((a, b))

    # (F3) upward closed within carrier
    failed_f3: list[tuple[frozenset[Any], frozenset[Any]]] = []
    for a in fam:
        for s in _powerset(carrier_set):
            if a.issubset(s) and s and s not in fam_set:
                failed_f3.append((a, s))

    metadata["failed_f2_pairs"] = len(failed_f2)
    metadata["failed_f3_pairs"] = len(failed_f3)

    if failed_f2:
        return Result.false(
            mode="exact",
            value=False,
            justification=["(F2) fails: the family is not closed under finite intersections."],
            metadata=metadata,
        )

    if failed_f3:
        return Result.false(
            mode="exact",
            value=False,
            justification=["(F3) fails: the family is not upward closed within the carrier."],
            metadata=metadata,
        )

    return Result.true(
        mode="exact",
        value=True,
        justification=["The family satisfies all three filter axioms (F1), (F2), and (F3)."],
        proof_outline=[
            "Non-empty-set, finite-intersection closure, and upward closure were"
            " verified by finite enumeration over the carrier powerset."
        ],
        metadata=metadata,
    )


def neighborhood_filter_base(
    space: Any,
    point: Any,
) -> Result:
    """Return the open-neighborhood filter base at *point* in a finite space.

    For a finite topological space the open sets that contain *point* form a
    filter base; their intersection (the minimal open neighborhood) is the
    smallest base element.
    """
    try:
        carrier = tuple(getattr(space, "carrier"))
        topology = getattr(space, "topology")
    except Exception:
        return Result.unknown(
            mode="symbolic",
            value="neighborhood_filter_base",
            justification=[
                "Exact neighborhood filter extraction is implemented only"
                " for explicit finite topological spaces."
            ],
            metadata={"operator": "neighborhood_filter_base"},
        )

    carrier_set = frozenset(carrier)
    if point not in carrier_set:
        return Result.false(
            mode="exact",
            value=False,
            justification=["The point is not in the finite carrier."],
            metadata={"operator": "neighborhood_filter_base", "point": point},
        )

    open_nbhds = tuple(
        frozenset(s) for s in topology if point in frozenset(s) and frozenset(s)
    )

    if not open_nbhds:
        return Result.false(
            mode="exact",
            value=False,
            justification=["No open set contains the point (the space has no open neighborhood for it)."],
            metadata={"operator": "neighborhood_filter_base", "point": point},
        )

    return Result.true(
        mode="exact",
        value=open_nbhds,
        justification=[
            "The open sets containing the point form a filter base:"
            " they are non-empty, exclude the empty set, and any two have an intersection"
            " containing a smaller open set (their intersection, which is open in a topology)."
        ],
        proof_outline=[
            "Extracted all open sets that contain the point.",
            "Intersection of any two open neighborhoods is open and still contains the point,"
            " so condition (B2) holds by taking the intersection itself as B3.",
        ],
        metadata={
            "operator": "neighborhood_filter_base",
            "point": point,
            "open_neighborhood_count": len(open_nbhds),
        },
    )


def filter_converges_to(
    space: Any,
    family: Iterable[Iterable[Any]],
    point: Any,
) -> Result:
    """Check whether a filter *family* converges to *point* in a finite space.

    A filter F converges to x if every open neighborhood of x belongs to F.
    For finite spaces checking open neighborhoods is equivalent to checking
    all neighborhoods (since the minimal open neighborhood is the smallest
    neighborhood).
    """
    try:
        carrier = tuple(getattr(space, "carrier"))
        topology = getattr(space, "topology")
    except Exception:
        return Result.unknown(
            mode="symbolic",
            value="filter_converges_to",
            justification=[
                "Exact filter convergence is implemented only"
                " for explicit finite topological spaces."
            ],
            metadata={"operator": "filter_converges_to"},
        )

    carrier_set = frozenset(carrier)
    if point not in carrier_set:
        return Result.false(
            mode="exact",
            value=False,
            justification=["The proposed limit point is not in the finite carrier."],
            metadata={"operator": "filter_converges_to", "point": point},
        )

    fam = _normalize_family(family)
    fam_set = set(fam)

    open_nbhds = tuple(
        frozenset(s) for s in topology if point in frozenset(s) and frozenset(s)
    )

    missing: list[frozenset[Any]] = [n for n in open_nbhds if n not in fam_set]

    metadata: dict[str, Any] = {
        "operator": "filter_converges_to",
        "point": point,
        "open_neighborhood_count": len(open_nbhds),
        "open_neighborhoods_in_filter": len(open_nbhds) - len(missing),
        "missing_open_neighborhoods": len(missing),
    }

    if missing:
        return Result.false(
            mode="exact",
            value=False,
            justification=[
                "At least one open neighborhood of the proposed limit is not in the filter."
            ],
            metadata=metadata,
        )

    return Result.true(
        mode="exact",
        value=True,
        justification=[
            "Every open neighborhood of the proposed limit belongs to the filter."
        ],
        proof_outline=[
            "For a finite topology, filter convergence was checked by verifying"
            " that every open set containing the point is a member of the filter."
        ],
        metadata=metadata,
    )



def is_finer_filter(
    carrier: Iterable[Any],
    finer: Iterable[Iterable[Any]],
    coarser: Iterable[Iterable[Any]],
) -> Result:
    """Check whether one finite filter is finer than another.

    With the usual order convention, ``finer`` is finer than ``coarser`` when
    every member of ``coarser`` also belongs to ``finer``.  Equivalently,
    ``coarser ⊆ finer`` as families of subsets of the carrier.
    """
    carrier_set = frozenset(carrier)
    finer_family = _normalize_family(finer)
    coarser_family = _normalize_family(coarser)
    finer_check = is_filter(carrier_set, finer_family)
    coarser_check = is_filter(carrier_set, coarser_family)
    metadata: dict[str, Any] = {
        "operator": "is_finer_filter",
        "carrier_size": len(carrier_set),
        "finer_size": len(finer_family),
        "coarser_size": len(coarser_family),
        "finer_filter_status": finer_check.status,
        "coarser_filter_status": coarser_check.status,
    }
    if not finer_check.is_true or not coarser_check.is_true:
        return Result.false(
            mode="exact",
            value=False,
            justification=["Both inputs must be valid filters before refinement can be checked."],
            metadata=metadata,
        )
    finer_set = set(finer_family)
    missing = tuple(s for s in coarser_family if s not in finer_set)
    metadata["missing_coarser_members"] = len(missing)
    if missing:
        return Result.false(
            mode="exact",
            value=False,
            justification=["The proposed finer filter does not contain every set of the proposed coarser filter."],
            metadata=metadata,
        )
    return Result.true(
        mode="exact",
        value=True,
        justification=["Every member of the coarser filter belongs to the finer filter."],
        proof_outline=["Refinement was checked by the inclusion test coarser_family ⊆ finer_family."],
        metadata=metadata,
    )


def filter_clusters_at(space: Any, family: Iterable[Iterable[Any]], point: Any) -> Result:
    """Check whether a finite filter clusters at ``point``."""
    space_data = _finite_space_data(space, "filter_clusters_at")
    if isinstance(space_data, Result):
        return space_data
    carrier_set, topology = space_data
    if point not in carrier_set:
        return Result.false(
            mode="exact",
            value=False,
            justification=["The proposed cluster point is not in the finite carrier."],
            metadata={"operator": "filter_clusters_at", "point": point},
        )
    fam = _normalize_family(family)
    filter_check = is_filter(carrier_set, fam)
    metadata: dict[str, Any] = {
        "operator": "filter_clusters_at",
        "point": point,
        "family_size": len(fam),
        "filter_status": filter_check.status,
    }
    if not filter_check.is_true:
        return Result.false(
            mode="exact",
            value=False,
            justification=["Cluster-point diagnostics require a valid filter."],
            metadata=metadata,
        )
    open_nbhds = tuple(frozenset(s) for s in topology if point in frozenset(s) and frozenset(s))
    failed_pairs: list[tuple[frozenset[Any], frozenset[Any]]] = []
    for neighborhood in open_nbhds:
        for member in fam:
            if not (neighborhood & member):
                failed_pairs.append((neighborhood, member))
    metadata["open_neighborhood_count"] = len(open_nbhds)
    metadata["failed_neighborhood_member_pairs"] = len(failed_pairs)
    if failed_pairs:
        return Result.false(
            mode="exact",
            value=False,
            justification=["At least one open neighborhood of the point is disjoint from a filter member."],
            metadata=metadata,
        )
    return Result.true(
        mode="exact",
        value=True,
        justification=["Every open neighborhood of the point meets every member of the filter."],
        proof_outline=["The finite cluster/adherence condition was checked by enumerating open neighborhoods and filter members."],
        metadata=metadata,
    )


def filter_cluster_points(space: Any, family: Iterable[Iterable[Any]]) -> Result:
    """Compute the finite cluster/adherent points of a filter."""
    space_data = _finite_space_data(space, "filter_cluster_points")
    if isinstance(space_data, Result):
        return space_data
    carrier_set, _topology = space_data
    fam = _normalize_family(family)
    filter_check = is_filter(carrier_set, fam)
    metadata: dict[str, Any] = {
        "operator": "filter_cluster_points",
        "carrier_size": len(carrier_set),
        "family_size": len(fam),
        "filter_status": filter_check.status,
    }
    if not filter_check.is_true:
        return Result.false(
            mode="exact",
            value=False,
            justification=["Cluster-point computation requires a valid filter."],
            metadata=metadata,
        )
    cluster_points = tuple(
        point for point in sorted(carrier_set, key=repr)
        if filter_clusters_at(space, fam, point).is_true
    )
    return Result.true(
        mode="exact",
        value=cluster_points,
        justification=["Finite filter cluster/adherent points were computed by direct enumeration."],
        proof_outline=["For each carrier point, every open neighborhood was tested against every filter member."],
        metadata={**metadata, "cluster_point_count": len(cluster_points)},
    )


def analyze_filter(
    space: Any,
    family: Iterable[Iterable[Any]],
    *,
    point: Any | None = None,
    coarser: Iterable[Iterable[Any]] | None = None,
) -> Result:
    """Return a structured finite filter analysis record."""
    space_data = _finite_space_data(space, "analyze_filter")
    if isinstance(space_data, Result):
        return space_data
    carrier_set, _topology = space_data
    fam = _normalize_family(family)
    filter_check = is_filter(carrier_set, fam)
    payload: dict[str, Any] = {"filter_check": filter_check}
    metadata: dict[str, Any] = {
        "operator": "analyze_filter",
        "carrier_size": len(carrier_set),
        "family_size": len(fam),
        "filter_status": filter_check.status,
        "point_requested": point is not None,
        "refinement_requested": coarser is not None,
    }
    if not filter_check.is_true:
        return Result.false(
            mode="exact",
            value=payload,
            justification=["The supplied family is not a valid filter, so convergence and cluster diagnostics are not computed."],
            metadata=metadata,
        )
    clusters = filter_cluster_points(space, fam)
    payload["cluster_points"] = clusters
    if point is not None:
        payload["converges_to_point"] = filter_converges_to(space, fam, point)
        payload["clusters_at_point"] = filter_clusters_at(space, fam, point)
    if coarser is not None:
        payload["is_finer_than_coarser"] = is_finer_filter(carrier_set, fam, coarser)
    return Result.true(
        mode="exact",
        value=payload,
        justification=["The supplied family is a valid filter and the requested finite diagnostics were computed."],
        proof_outline=["The facade delegates to the finite filter, convergence, refinement, and cluster-point helpers."],
        metadata={**metadata, "cluster_point_count": len(clusters.value) if clusters.is_true else 0},
    )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _finite_space_data(space: Any, operator: str) -> tuple[frozenset[Any], tuple[frozenset[Any], ...]] | Result:
    """Extract carrier and topology from an explicit finite topological space."""
    try:
        carrier = tuple(getattr(space, "carrier"))
        topology = tuple(frozenset(s) for s in getattr(space, "topology"))
    except Exception:
        return Result.unknown(
            mode="symbolic",
            value=operator,
            justification=["Exact filter diagnostics are implemented only for explicit finite topological spaces."],
            metadata={"operator": operator},
        )
    return frozenset(carrier), topology


def _powerset(s: frozenset[Any]) -> tuple[frozenset[Any], ...]:
    """Return all subsets of *s* as frozensets, including the empty set."""
    elements = list(s)
    n = len(elements)
    result: list[frozenset[Any]] = []
    for mask in range(1 << n):
        subset = frozenset(elements[i] for i in range(n) if mask & (1 << i))
        result.append(subset)
    return tuple(sorted(result, key=lambda x: (len(x), tuple(sorted(map(repr, x))))))


__all__ = [
    "FilterError",
    "is_filter_base",
    "generated_filter",
    "is_filter",
    "neighborhood_filter_base",
    "filter_converges_to",
    "is_finer_filter",
    "filter_clusters_at",
    "filter_cluster_points",
    "analyze_filter",
]
