"""Hopf invariant and related homotopy invariants (Phase 13.4).

The Hopf invariant of a map f: S^{2n-1} → S^n is an integer H(f) ∈ ℤ
that measures the linking of the preimages of two regular values.

Algebraic definition (via mapping cone):
  Let C(f) = S^n ∪_f e^{2n} be the mapping cone of f.
  H*(C(f); ℤ) has generators ι_n ∈ H^n and ι_{2n} ∈ H^{2n}.
  The cup product ι_n ∪ ι_n = H(f) · ι_{2n}.
  The Hopf invariant is the coefficient H(f) ∈ ℤ.

Key results
-----------
Hopf fibrations (maps of Hopf invariant 1):
  η₁: S¹ → S¹   (n=1, H=1)  — identity / degree 1
  η₂: S³ → S²   (n=2, H=1)  — classical Hopf fibration, C(η₂) = CP²
  η₄: S⁷ → S⁴   (n=4, H=1)  — quaternionic Hopf fibration, C(η₄) = HP²
  η₈: S¹⁵ → S⁸  (n=8, H=1)  — octonionic Hopf fibration, C(η₈) = OP²

Adams theorem (1960): Maps of Hopf invariant 1 exist only for n = 1, 2, 4, 8.

Composition:
  H(f ∘ g) = deg(g)² · H(f)    (when g: S^{4n-1} → S^{2n-1})
  H(f₁ + f₂) = H(f₁) + H(f₂)  (in the stable range)

Linking number formula (n = 2):
  For f: S³ → S², H(f) = lk(f^{-1}(p), f^{-1}(q)) for regular values p, q.
  This is the preimage-linking-number interpretation.

π₃(S²) = ℤ, generated by the Hopf fibration η₂ with H(η₂) = 1.
"""

from __future__ import annotations

from dataclasses import dataclass

__all__ = [
    "HopfInvariant",
    "hopf_invariant_from_linking",
    "hopf_invariant_from_cup",
    "hopf_fibration",
    "all_hopf_fibrations",
    "adams_hopf_invariant_one",
    "pi3_s2",
    "hopf_invariant_composition",
]


# ---------------------------------------------------------------------------
# Data structure
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class HopfInvariant:
    """The Hopf invariant of a map f: S^{2n-1} → S^n.

    Attributes
    ----------
    source_sphere : int
        2n-1 (source sphere dimension).
    target_sphere : int
        n (target sphere dimension).
    hopf_invariant : int
        H(f) ∈ ℤ.
    name : str
        Human-readable name (e.g. ``"Hopf fibration η₂"``).
    mapping_cone : str
        Description of the mapping cone C(f).
    cup_product : str
        How the cup product ι_n ∪ ι_n relates to ι_{2n}.
    """

    source_sphere: int
    target_sphere: int
    hopf_invariant: int
    name: str
    mapping_cone: str
    cup_product: str

    @property
    def n(self) -> int:
        return self.target_sphere

    @property
    def is_hopf_invariant_one(self) -> bool:
        return abs(self.hopf_invariant) == 1

    def describe(self) -> str:
        return (
            f"f: S^{self.source_sphere} → S^{self.target_sphere}, "
            f"H(f) = {self.hopf_invariant}, "
            f"C(f) ≃ {self.mapping_cone}"
        )


# ---------------------------------------------------------------------------
# Hopf fibrations
# ---------------------------------------------------------------------------


def hopf_fibration(n: int) -> HopfInvariant:
    """Return the classical Hopf fibration data for target sphere S^n.

    Valid for n = 1, 2, 4, 8 (Adams theorem).

    Parameters
    ----------
    n : int
        Target sphere dimension: 1, 2, 4, or 8.

    Raises
    ------
    ValueError
        If n is not 1, 2, 4, or 8.
    """
    _data: dict[int, tuple[str, str, str]] = {
        1: (
            "η₁: identity S¹ → S¹",
            "S² (join S⁰ * S¹)",
            "ι₁ ∪ ι₁ = 1 · ι₂",
        ),
        2: (
            "η₂: Hopf fibration S³ → S² (complex, fibers S¹)",
            "CP² (complex projective plane)",
            "ι₂ ∪ ι₂ = 1 · ι₄",
        ),
        4: (
            "η₄: quaternionic Hopf fibration S⁷ → S⁴ (fibers S³)",
            "HP² (quaternionic projective plane)",
            "ι₄ ∪ ι₄ = 1 · ι₈",
        ),
        8: (
            "η₈: octonionic Hopf fibration S¹⁵ → S⁸ (fibers S⁷)",
            "OP² (octonionic projective plane, Cayley plane)",
            "ι₈ ∪ ι₈ = 1 · ι₁₆",
        ),
    }
    if n not in _data:
        raise ValueError(
            f"Hopf fibration with Hopf invariant 1 exists only for n=1,2,4,8 "
            f"(Adams 1960); got n={n}."
        )
    name, cone, cup = _data[n]
    return HopfInvariant(
        source_sphere=2 * n - 1,
        target_sphere=n,
        hopf_invariant=1,
        name=name,
        mapping_cone=cone,
        cup_product=cup,
    )


def all_hopf_fibrations() -> list[HopfInvariant]:
    """Return all four classical Hopf fibrations (n = 1, 2, 4, 8)."""
    return [hopf_fibration(n) for n in (1, 2, 4, 8)]


def adams_hopf_invariant_one(n: int) -> bool:
    """Adams theorem: does there exist a map S^{2n-1} → S^n with H(f) = 1?

    Returns True iff n ∈ {1, 2, 4, 8} (the only dimensions admitting
    maps of Hopf invariant one, by J.F. Adams 1960 using secondary
    cohomology operations / K-theory).
    """
    return n in {1, 2, 4, 8}


# ---------------------------------------------------------------------------
# Computational Hopf invariant
# ---------------------------------------------------------------------------


def hopf_invariant_from_linking(
    linking_number: int,
    n: int = 2,
) -> HopfInvariant:
    """Compute the Hopf invariant of a map S³ → S² from the linking number.

    For n = 2 and f: S³ → S², the Hopf invariant equals the linking
    number of f^{-1}(p) and f^{-1}(q) for generic regular values p, q.

    Parameters
    ----------
    linking_number : int
        The linking number lk(f^{-1}(p), f^{-1}(q)).
    n : int
        Must be 2 for this formula.
    """
    if n != 2:
        raise ValueError("Linking-number formula for Hopf invariant is only implemented for n=2.")
    return HopfInvariant(
        source_sphere=2 * n - 1,
        target_sphere=n,
        hopf_invariant=linking_number,
        name=f"Map S³ → S² with lk(f⁻¹(p),f⁻¹(q)) = {linking_number}",
        mapping_cone=f"S² ∪_f e⁴ (homotopy type depends on H(f)={linking_number})",
        cup_product=f"ι₂ ∪ ι₂ = {linking_number} · ι₄",
    )


def hopf_invariant_from_cup(
    cup_coefficient: int,
    n: int = 2,
) -> int:
    """Compute the Hopf invariant from the cup product structure in C(f).

    Given H*(C(f); ℤ) = ℤ[ι_n, ι_{2n}]/(ι_n² = H(f)·ι_{2n}, ι_{2n}² = 0),
    the Hopf invariant H(f) is exactly the coefficient of ι_{2n} in ι_n ∪ ι_n.

    Parameters
    ----------
    cup_coefficient : int
        The integer k such that ι_n ∪ ι_n = k · ι_{2n}.
    n : int
        Target sphere dimension (unused; kept for API symmetry).

    Returns
    -------
    int
        The Hopf invariant H(f) = ``cup_coefficient``.
    """
    return cup_coefficient


# ---------------------------------------------------------------------------
# π₃(S²)
# ---------------------------------------------------------------------------


def pi3_s2() -> dict[str, object]:
    """Return the computation of π₃(S²) = ℤ.

    The third homotopy group of S² is generated by the Hopf fibration
    η₂: S³ → S² with Hopf invariant H(η₂) = 1.

    Every element of π₃(S²) is of the form n·[η₂] with Hopf invariant n².

    Wait: actually π₃(S²) ≅ ℤ and the Hopf invariant H: π₃(S²) → ℤ is an
    isomorphism.  If [f] = n·[η₂] in π₃(S²), then H(f) = n.
    """
    eta2 = hopf_fibration(2)
    return {
        "group": "ℤ",
        "generator": eta2,
        "hopf_invariant_isomorphism": "H: π₃(S²) → ℤ is an isomorphism",
        "generator_name": "η₂ (Hopf fibration)",
        "hopf_invariant_of_generator": 1,
        "description": (
            "π₃(S²) = ℤ generated by the Hopf fibration η₂: S³ → S². "
            "The Hopf invariant gives a bijection π₃(S²) ≅ ℤ. "
            "Discovered by Hopf (1931), this was the first example of a "
            "non-trivial map between spheres of the same homotopy-theoretic type "
            "S^{2n-1} → S^n for n ≥ 2."
        ),
    }


# ---------------------------------------------------------------------------
# Composition formula
# ---------------------------------------------------------------------------


def hopf_invariant_composition(
    hopf_f: int,
    degree_g: int,
) -> int:
    """Hopf invariant of f ∘ g under suitable conditions.

    If f: S^{2n-1} → S^n has Hopf invariant H(f) and
    g: S^{4n-1} → S^{2n-1} has degree deg(g), then
    H(f ∘ g) = deg(g)² · H(f).

    Parameters
    ----------
    hopf_f : int
        Hopf invariant of f.
    degree_g : int
        Degree of g (viewed as a self-map of a sphere).
    """
    return degree_g * degree_g * hopf_f


def hopf_invariant_sum(hopf_f1: int, hopf_f2: int) -> int:
    """Hopf invariant of the sum f₁ + f₂ (in the stable range).

    In π^s_{4n-1}(S^{2n}) the Hopf invariant is additive:
    H(f₁ + f₂) = H(f₁) + H(f₂).
    """
    return hopf_f1 + hopf_f2


def hopf_invariant_degree_map(n: int, degree: int) -> int:
    """Hopf invariant of the degree-k map S^{2n-1} → S^{2n-1} → S^n.

    For f = η_n (Hopf fibration) and g = [k] (degree-k map of S^{2n-1}):
    H(η_n ∘ [k]) = k² · H(η_n) = k².

    Parameters
    ----------
    n : int
        Dimension of target sphere (must be 1, 2, 4, or 8 for η_n).
    degree : int
        Degree of the pre-composed map.
    """
    if not adams_hopf_invariant_one(n):
        raise ValueError(
            f"Hopf fibration η_n exists only for n=1,2,4,8; got n={n}."
        )
    return degree * degree
