"""Unified map support — backward-compatible re-export.

The implementation is split across two modules:

- :mod:`pytop.finite_map_analysis` — core types, property analysis engine,
  map-algebra helpers, builder functions, taxonomy utilities, all private helpers
- :mod:`pytop.map_continuity` — pointwise continuity, basis/subbasis criteria,
  closure-image inclusion, initial topology construction

Import from those modules directly for a finer-grained dependency, or continue
importing from this module for full backward compatibility.
"""

from .finite_map_analysis import (  # noqa: F401
    MAP_PROPERTIES,
    ConstantMap,
    ContinuousMap,
    EmbeddingMap,
    FiniteMap,
    HomeomorphismMap,
    MapBuilderError,
    QuotientMap,
    SymbolicMap,
    # private helpers — re-exported for backward compatibility with existing tests
    _analyze_finite_map_property,
    _can_do_exact_finite_map_analysis,
    _closed_sets,
    _exact_result,
    _graph_dict,
    _image,
    _is_quotient_via_open_set_criterion,
    _normalize_family,
    _preimage,
    _space_is_finite,
    _subspace_topology,
    analyze_map_property,
    compose_finite_maps,
    compose_maps,
    constant_function,
    fixed_points_of_map,
    identity_function,
    identity_map,
    image_of_subset,
    inverse_map,
    is_bijective_map,
    is_closed_map,
    is_continuous_map,
    is_embedding_map,
    is_homeomorphism_map,
    is_injective_map,
    is_open_map,
    is_quotient_map,
    is_surjective_map,
    make_function,
    map_report,
    map_taxonomy_profile,
    normalize_map_property,
    preimage_of_subset,
    render_map_taxonomy_report,
    restriction_of_map,
)
from .map_continuity import (  # noqa: F401
    continuity_via_codomain_basis,
    continuity_via_codomain_subbasis,
    initial_topology_from_maps,
    is_continuous_at_point,
    is_sequentially_continuous_at_point,
    satisfies_closure_image_inclusion,
)

__all__ = [
    "MAP_PROPERTIES",
    "SymbolicMap",
    "ContinuousMap",
    "EmbeddingMap",
    "QuotientMap",
    "HomeomorphismMap",
    "ConstantMap",
    "FiniteMap",
    "normalize_map_property",
    "analyze_map_property",
    "is_continuous_map",
    "is_open_map",
    "is_closed_map",
    "is_injective_map",
    "is_surjective_map",
    "is_bijective_map",
    "is_embedding_map",
    "is_quotient_map",
    "is_homeomorphism_map",
    "map_report",
    "identity_map",
    "compose_maps",
    "compose_finite_maps",
    "preimage_of_subset",
    "image_of_subset",
    "restriction_of_map",
    "fixed_points_of_map",
    "inverse_map",
    "is_continuous_at_point",
    "is_sequentially_continuous_at_point",
    "continuity_via_codomain_basis",
    "continuity_via_codomain_subbasis",
    "satisfies_closure_image_inclusion",
    "initial_topology_from_maps",
    "map_taxonomy_profile",
    "render_map_taxonomy_report",
    "MapBuilderError",
    "make_function",
    "identity_function",
    "constant_function",
]
