"""Noncommutative topology: C*-algebras, Gelfand duality, K-theory, spectral triples,
and the noncommutative geometry programme of Connes.

Key theorems implemented
------------------------
- Gelfand duality (1943): there is a contravariant equivalence of categories between
  compact Hausdorff spaces and commutative unital C*-algebras, given by X |-> C(X)
  (continuous complex-valued functions) and A |-> Spec(A) (maximal ideal space /
  character space). Under this duality: points of X <-> characters chi: A -> C;
  open sets of X <-> closed ideals of C(X); continuous maps f: X -> Y <->
  *-homomorphisms f*: C(Y) -> C(X). A noncommutative C*-algebra is thus a
  'noncommutative topological space'. Key examples: C(S^1) = commutative (S^1 is
  classical); M_n(C) = noncommutative (n x n matrices, no classical Gelfand dual).
- Gelfand-Naimark theorem (1943): every C*-algebra A is isometrically *-isomorphic
  to a closed *-subalgebra of B(H), the bounded operators on some Hilbert space H.
  Commutative case: A ≅ C_0(X) for locally compact Hausdorff X = Spec(A). This
  justifies calling noncommutative C*-algebras 'noncommutative spaces'.
- K-theory for C*-algebras (Atiyah 1964 / Hirzebruch): for a C*-algebra A, K_0(A)
  is the Grothendieck group of Murray-von Neumann equivalence classes of projections
  in M_infty(A). K_1(A) = K_0(SA) where SA = C_0((0,1)) tensor A is the suspension.
  The six-term exact sequence and Bott periodicity K_{n+2}(A) ≅ K_n(A) are the
  main computational tools. For commutative A = C(X): K_0(C(X)) = K^0(X) (topological
  K-theory), K_1(C(X)) = K^1(X) (Atiyah-Hirzebruch). Key example: K_0(M_n(C)) = Z,
  K_1(M_n(C)) = 0 (matrix algebras).
- Connes' spectral triple (A, H, D) (1994): a spectral triple (also called an
  unbounded Fredholm module) consists of a *-algebra A represented on a Hilbert space
  H, and a self-adjoint operator D ('Dirac operator') with compact resolvent, such
  that [D, a] is bounded for all a in A. The spectral triple encodes a noncommutative
  Riemannian geometry: the metric on the state space S(A) is d(phi, psi) =
  sup{|phi(a) - psi(a)| : ||[D,a]|| <= 1}. For commutative A = C^infty(M): take
  H = L^2(M, S) (spinor bundle), D = Dirac operator — recovers classical Riemannian
  geometry. The spectral triple is even (graded) if H has a Z/2Z grading chi with
  chi·D = -D·chi, modelling the chirality of the Dirac operator.
- Morita equivalence: two C*-algebras A and B are Morita equivalent if there is an
  A-B imprimitivity bimodule — a full Hilbert bimodule. Morita equivalent algebras
  have the same K-theory and representation theory. Key fact: M_n(A) is Morita
  equivalent to A for all n >= 1 (the Morita invariance of K-theory). The
  noncommutative torus A_theta is Morita equivalent to A_{theta'} when theta and
  theta' are related by a modular transformation in PSL(2,Z).
- Noncommutative torus A_theta (Rieffel 1981): for theta in [0,1], the noncommutative
  torus A_theta is the universal C*-algebra generated by unitaries U, V with
  VU = e^{2 pi i theta} UV. For theta = 0: A_0 = C(T^2) (commutative). For theta
  irrational: A_theta is a simple C*-algebra. K_0(A_theta) = Z^2, K_1(A_theta) = Z^2
  (same as C(T^2) by Pimsner-Voiculescu). The noncommutative torus is the paradigm
  example of a noncommutative manifold and models the quantum Hall effect.
- Nuclear C*-algebras: A is nuclear if there is a unique C*-cross-norm on A tensor B
  for every C*-algebra B (equivalently, the minimal and maximal tensor products agree).
  Commutative C*-algebras, AF-algebras, and the CAR algebra are nuclear. The Connes
  embedding problem (resolved negatively, Ji-Natarajan-Vidick-Wright-Yuen 2020):
  not every II_1 factor embeds in the ultrapower of the hyperfinite II_1 factor R.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from typing import Any

from .result import Result


@dataclass(frozen=True)
class NoncommutativeProfile:
    """A curated noncommutative topology / geometry example."""

    key: str
    display_name: str
    algebra_type: str
    is_commutative: bool
    is_nuclear: bool
    is_simple: bool
    has_classical_gelfand_dual: bool
    has_spectral_triple: bool
    k0_group: str
    k1_group: str
    presentation_layer: str
    focus: str
    chapter_targets: tuple[str, ...]


# ---------------------------------------------------------------------------
# Tag constants
# ---------------------------------------------------------------------------

COMMUTATIVE_CSTAR_TAGS: frozenset[str] = frozenset({
    "commutative_cstar",
    "function_algebra",
    "c_of_x",
    "gelfand_dual",
    "locally_compact_hausdorff_algebra",
    "abelian_cstar",
    "c_of_compact_space",
    "c0_of_lc_space",
})

NONCOMMUTATIVE_CSTAR_TAGS: frozenset[str] = frozenset({
    "noncommutative_cstar",
    "matrix_algebra",
    "noncommutative_torus",
    "group_cstar_algebra",
    "reduced_group_cstar",
    "irrational_rotation_algebra",
    "cuntz_algebra",
    "caf_algebra",
    "car_algebra",
    "von_neumann_algebra",
    "b_of_h",
    "compact_operators",
    "toeplitz_algebra",
    "crossed_product",
})

NUCLEAR_CSTAR_TAGS: frozenset[str] = frozenset({
    "nuclear_cstar",
    "commutative_cstar",
    "af_algebra",
    "car_algebra",
    "cuntz_algebra",
    "abelian_cstar",
    "amenable_group_cstar",
    "inductive_limit",
    "approximately_finite",
})

SIMPLE_CSTAR_TAGS: frozenset[str] = frozenset({
    "simple_cstar",
    "irrational_rotation_algebra",
    "cuntz_algebra",
    "car_algebra",
    "purely_infinite_simple",
    "noncommutative_torus_irrational",
})

SPECTRAL_TRIPLE_TAGS: frozenset[str] = frozenset({
    "spectral_triple",
    "dirac_operator",
    "noncommutative_manifold",
    "spinc_manifold",
    "connes_spectral_triple",
    "finitely_summable_triple",
    "theta_summable_triple",
})

GELFAND_DUAL_TAGS: frozenset[str] = frozenset({
    "gelfand_dual",
    "commutative_cstar",
    "c_of_x",
    "character_space",
    "maximal_ideal_space",
    "abelian_cstar",
})

NOT_GELFAND_TAGS: frozenset[str] = frozenset({
    "no_gelfand_dual",
    "noncommutative_cstar",
    "matrix_algebra",
    "irrational_rotation_algebra",
    "cuntz_algebra",
    "b_of_h",
    "compact_operators",
    "car_algebra",
    "von_neumann_algebra",
})

MORITA_EQUIVALENCE_TAGS: frozenset[str] = frozenset({
    "morita_equivalent",
    "imprimitivity_bimodule",
    "morita_invariant",
    "stabilization",
    "full_hilbert_bimodule",
})

KTHEORY_TAGS: frozenset[str] = frozenset({
    "k0_nontrivial",
    "k1_nontrivial",
    "bott_periodicity",
    "six_term_exact_sequence",
    "pimsner_voiculescu",
    "atiyah_hirzebruch",
    "elliott_invariant",
})


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _extract_tags(space: Any) -> set[str]:
    raw = getattr(space, "tags", None) or getattr(space, "_tags", None)
    if isinstance(raw, (set, list, tuple, frozenset)):
        return {str(t).strip().lower() for t in raw}
    return set()


def _representation_of(space: Any) -> str:
    metadata = getattr(space, "metadata", {}) or {}
    if isinstance(metadata, dict) and "representation" in metadata:
        return str(metadata["representation"]).strip().lower()
    rep = getattr(space, "representation", None)
    if rep:
        return str(rep).strip().lower()
    return "symbolic_general"


def _matches_any(tags: set[str], candidates: set[str] | frozenset[str]) -> bool:
    return bool(tags & candidates)


# ---------------------------------------------------------------------------
# Named example registry
# ---------------------------------------------------------------------------

def get_named_noncommutative_profiles() -> tuple[NoncommutativeProfile, ...]:
    """Return the registry of canonical noncommutative topology examples."""
    return (
        NoncommutativeProfile(
            key="c_of_compact_space",
            display_name="C(X) — algebra of continuous functions on a compact Hausdorff space",
            algebra_type="commutative_cstar",
            is_commutative=True,
            is_nuclear=True,
            is_simple=False,
            has_classical_gelfand_dual=True,
            has_spectral_triple=False,
            k0_group="K^0(X)",
            k1_group="K^1(X)",
            presentation_layer="main_text",
            focus=(
                "C(X) is the commutative unital C*-algebra of continuous complex-valued "
                "functions on a compact Hausdorff space X, with pointwise operations and "
                "supremum norm ||f|| = sup_{x in X} |f(x)|. "
                "Gelfand duality: the Gelfand transform Gamma: C(X) -> C(Spec(C(X))) is an "
                "isometric *-isomorphism onto C(X) itself (since X is already the character "
                "space of C(X) via point evaluations delta_x: f |-> f(x)). Under Gelfand "
                "duality, compact Hausdorff spaces <-> commutative unital C*-algebras: "
                "  - Points x in X <-> characters chi: A -> C (unital *-homomorphisms) "
                "  - Continuous f: X -> Y <-> *-homomorphisms f*: C(Y) -> C(X), f*(g) = g circ f "
                "  - Closed sets F ⊆ X <-> closed ideals I_F = {f : f|_F = 0} ⊆ C(X) "
                "  - Open U ⊆ X <-> open projections (approximate units in I_U) "
                "The algebra C(X) is nuclear for all compact Hausdorff X (commutative "
                "C*-algebras are always nuclear). K-theory: K_0(C(X)) = K^0(X) "
                "(topological K-theory, Atiyah-Hirzebruch), K_1(C(X)) = K^1(X). "
                "For X = S^{2n}: K^0(S^{2n}) = Z^2, K^1(S^{2n}) = 0. "
                "For X = S^{2n+1}: K^0(S^{2n+1}) = Z, K^1(S^{2n+1}) = Z. "
                "The algebra C([0,1]) ≅ C([0,1]) is simple-connected (Spec = [0,1] is "
                "contractible), giving K_0 = Z, K_1 = 0."
            ),
            chapter_targets=("12", "30", "54"),
        ),
        NoncommutativeProfile(
            key="matrix_algebra",
            display_name="M_n(C) — n×n complex matrix algebra",
            algebra_type="matrix_algebra",
            is_commutative=False,
            is_nuclear=True,
            is_simple=True,
            has_classical_gelfand_dual=False,
            has_spectral_triple=True,
            k0_group="Z",
            k1_group="0",
            presentation_layer="main_text",
            focus=(
                "The matrix algebra M_n(C) of n×n complex matrices is the simplest "
                "noncommutative C*-algebra. It is a finite-dimensional C*-algebra: every "
                "finite-dimensional C*-algebra is a direct sum of matrix algebras "
                "M_{n_1}(C) ⊕ ... ⊕ M_{n_k}(C) (Artin-Wedderburn theorem). "
                "M_n(C) has NO classical Gelfand dual: it has no characters (the only "
                "unital *-homomorphism M_n(C) -> C is the zero map for n >= 2). The "
                "Gelfand-Naimark theorem instead embeds M_n(C) in B(C^n) = M_n(C) itself. "
                "M_n(C) is simple: the only two-sided closed ideals are {0} and M_n(C). "
                "M_n(C) is nuclear: all finite-dimensional C*-algebras are nuclear. "
                "K-theory: K_0(M_n(C)) = Z (generated by rank-1 projections; all rank-r "
                "projections are Murray-von Neumann equivalent). K_1(M_n(C)) = 0 "
                "(every invertible matrix is connected to the identity via GL_n(C), which "
                "is path-connected). Bott periodicity: K_0(S(M_n(C))) = 0, K_1(M_n(C)) = 0 "
                "consistent with K_0(C) = Z, K_1(C) = 0. "
                "Spectral triple: (M_n(C), C^n, D) with D any self-adjoint matrix gives "
                "a finite-dimensional spectral triple encoding a metric on the n-point space. "
                "Morita equivalence: M_n(C) is Morita equivalent to C (imprimitivity bimodule "
                "= C^n as a C-M_n(C) bimodule). Hence K_0(M_n(C)) = K_0(C) = Z."
            ),
            chapter_targets=("12", "30", "54"),
        ),
        NoncommutativeProfile(
            key="noncommutative_torus",
            display_name="A_θ — irrational rotation algebra (noncommutative torus)",
            algebra_type="irrational_rotation_algebra",
            is_commutative=False,
            is_nuclear=True,
            is_simple=True,
            has_classical_gelfand_dual=False,
            has_spectral_triple=True,
            k0_group="Z^2",
            k1_group="Z^2",
            presentation_layer="main_text",
            focus=(
                "The noncommutative torus A_theta (Rieffel 1981) is the universal C*-algebra "
                "generated by unitaries U and V satisfying VU = e^{2 pi i theta} UV, for "
                "theta in [0,1]. "
                "For theta = 0: A_0 = C(T^2) — commutative, the algebra of the 2-torus. "
                "For theta irrational: A_theta is simple (no proper ideals) and nuclear. "
                "It is the 'noncommutative T^2': T^2 is replaced by a quantum space "
                "where the two circle directions satisfy a canonical commutation relation. "
                "K-theory (Pimsner-Voiculescu, 1980): K_0(A_theta) = Z^2, K_1(A_theta) = Z^2 "
                "for all theta — the same as K*(C(T^2)). The generators of K_0 are [1] and "
                "[P_theta] where P_theta is the Powers-Rieffel projection of trace theta. "
                "Spectral triple: A_theta acts on L^2(A_theta) ⊕ L^2(A_theta) with the "
                "Dirac-like operator D = [[0, delta_1 - i delta_2], [delta_1 + i delta_2, 0]] "
                "where delta_1, delta_2 are the canonical derivations (partial derivatives in "
                "each 'direction'). This gives a 2-dimensional spectral triple. "
                "Morita equivalence: A_theta is Morita equivalent to A_{theta'} when "
                "theta' = (a theta + b)/(c theta + d) for [[a,b],[c,d]] in SL_2(Z). "
                "This is the noncommutative analogue of the modular group action on tori. "
                "Applications: models the quantum Hall effect (theta = B/h, the magnetic flux "
                "ratio), the gap-labeling theorem (K_0 labels spectral gaps of Hamiltonians "
                "in quasi-periodic potentials), and string theory (D-branes in magnetic fields)."
            ),
            chapter_targets=("12", "30", "54"),
        ),
        NoncommutativeProfile(
            key="cuntz_algebra",
            display_name="O_n — Cuntz algebra (purely infinite simple C*-algebra)",
            algebra_type="cuntz_algebra",
            is_commutative=False,
            is_nuclear=True,
            is_simple=True,
            has_classical_gelfand_dual=False,
            has_spectral_triple=False,
            k0_group="Z/(n-1)Z",
            k1_group="0",
            presentation_layer="main_text",
            focus=(
                "The Cuntz algebra O_n (Cuntz 1977) is the universal C*-algebra generated "
                "by n isometries s_1, ..., s_n with sum_{i=1}^{n} s_i s_i^* = 1 (the "
                "identity). Each s_i satisfies s_i^* s_i = 1 (isometry). "
                "O_n is simple and purely infinite: every nonzero hereditary subalgebra "
                "contains an infinite projection. It is nuclear. "
                "K-theory: K_0(O_n) = Z/(n-1)Z, K_1(O_n) = 0. "
                "The generator of K_0 is [1], and (n-1)[1] = 0 because "
                "sum s_i s_i^* = 1 implies n[s_1 s_1^*] = [1] in K_0, "
                "i.e., n[p] = [1] where [p] = [1] by equivalence, so (n-1)[1] = 0. "
                "O_2 is particularly important: it is the 'infinite-dimensional analogue "
                "of M_{2^infty}'. K_0(O_2) = 0, K_1(O_2) = 0. "
                "O_infty (infinitely many isometries, sum doesn't converge to 1): "
                "K_0(O_infty) = Z, K_1(O_infty) = 0. "
                "Cuntz algebras are classified by the Kirchberg-Phillips theorem (1995, 2000): "
                "purely infinite simple nuclear C*-algebras are classified (in the UCT class) "
                "by their K-theory (K_0, K_1, [1]_{K_0}) — the Elliott invariant for "
                "the Kirchberg algebra category. This is the analogue of the classification "
                "of AF-algebras by Elliott (1976)."
            ),
            chapter_targets=("12", "30"),
        ),
        NoncommutativeProfile(
            key="group_cstar_algebra",
            display_name="C*(G) — group C*-algebra of a locally compact group",
            algebra_type="group_cstar_algebra",
            is_commutative=False,
            is_nuclear=False,
            is_simple=False,
            has_classical_gelfand_dual=False,
            has_spectral_triple=False,
            k0_group="K_0(C*(G))",
            k1_group="K_1(C*(G))",
            presentation_layer="selected_block",
            focus=(
                "For a locally compact group G with Haar measure mu, the group C*-algebra "
                "C*(G) is the completion of L^1(G, mu) in the norm "
                "||f|| = sup{||pi(f)|| : pi unitary representation of G}. "
                "The reduced group C*-algebra C*_r(G) is the completion of L^1(G) in "
                "the left regular representation lambda: G -> B(L^2(G)). "
                "C*(G) = C*_r(G) iff G is amenable (Day 1950): e.g., abelian groups, "
                "compact groups, solvable groups. Non-amenable groups: free groups F_n. "
                "Commutative case: G abelian => C*(G) = C_0(G^) where G^ is the Pontryagin "
                "dual (Fourier transform). E.g., C*(Z) = C(T), C*(R) = C_0(R), "
                "C*(Z^n) = C(T^n). This is Gelfand duality for abelian groups. "
                "Nuclearity: C*(G) is nuclear iff G is amenable. "
                "The Baum-Connes conjecture (proved for large classes of groups): "
                "K_*(C*_r(G)) ≅ K^G_*(EG) where EG is the classifying space for proper "
                "G-actions. This links the K-theory of the group C*-algebra to the "
                "equivariant K-homology of the classifying space — a deep connection "
                "between noncommutative topology and geometric group theory."
            ),
            chapter_targets=("12", "30"),
        ),
        NoncommutativeProfile(
            key="compact_operators",
            display_name="K(H) — compact operators on a Hilbert space",
            algebra_type="compact_operators",
            is_commutative=False,
            is_nuclear=True,
            is_simple=True,
            has_classical_gelfand_dual=False,
            has_spectral_triple=False,
            k0_group="Z",
            k1_group="0",
            presentation_layer="selected_block",
            focus=(
                "The compact operators K(H) on an infinite-dimensional separable Hilbert "
                "space H form a closed two-sided ideal in B(H) — the only proper closed "
                "two-sided ideal in B(H) (which makes B(H)/K(H) = the Calkin algebra). "
                "K(H) is simple (as a C*-algebra without unit): the only closed ideals are "
                "{0} and K(H). K(H) is nuclear: every operator T in K(H) can be approximated "
                "by finite-rank operators (which form a nuclear subalgebra). "
                "K-theory: K_0(K(H)) = Z (generated by any rank-1 projection p: all "
                "rank-1 projections are Murray-von Neumann equivalent). K_1(K(H)) = 0. "
                "Stabilization: A tensor K(H) (the stabilization of A) is Morita equivalent "
                "to A, and K-theory is Morita invariant (stable under tensoring with K(H)). "
                "This is a fundamental tool: K_0(A) = K_0(A tensor K). "
                "The extension 0 -> K(H) -> B(H) -> B(H)/K(H) -> 0 (Calkin extension) "
                "gives the six-term K-theory exact sequence. The Fredholm index: an operator "
                "T in B(H) is Fredholm if its image in the Calkin algebra is invertible; "
                "ind(T) = dim(ker T) - dim(coker T) in Z = K_0(K(H)). Brown-Douglas-Fillmore "
                "theory (1977): extensions of K(H) by C(X) are classified by KK^1(C(X), C) = "
                "K^1(X), the odd K-theory of X."
            ),
            chapter_targets=("12", "30"),
        ),
        NoncommutativeProfile(
            key="af_algebra",
            display_name="AF-algebra — approximately finite-dimensional C*-algebra",
            algebra_type="af_algebra",
            is_commutative=False,
            is_nuclear=True,
            is_simple=False,
            has_classical_gelfand_dual=False,
            has_spectral_triple=False,
            k0_group="ordered_abelian_group",
            k1_group="0",
            presentation_layer="selected_block",
            focus=(
                "An approximately finite-dimensional (AF) C*-algebra is the inductive limit "
                "A = lim_{->} A_n of finite-dimensional C*-algebras A_n (each being a direct "
                "sum of matrix algebras). The connecting maps phi_n: A_n -> A_{n+1} are "
                "unital *-homomorphisms. Key examples: "
                "  - M_{2^infty} = lim_{->} M_{2^n}(C): the 2^infty UHF (uniformly hyper-finite) "
                "    algebra, K_0 = Z[1/2] (dyadic rationals in (0,1]) with order unit 1. "
                "  - The CAR algebra = M_{2^infty}: models creation/annihilation operators "
                "    for fermions (canonical anticommutation relations). "
                "  - The Cantor set C: C(C) is AF (Bratteli diagram = infinite binary tree). "
                "Elliott's classification (1976): AF-algebras are classified up to "
                "isomorphism by their K_0 group as a scaled ordered abelian group "
                "(K_0(A), K_0(A)^+, [1]). The Bratteli diagram encodes the inclusions "
                "A_n -> A_{n+1} and completely determines the algebra. "
                "All AF-algebras are nuclear (inductive limits of nuclear algebras are nuclear). "
                "K-theory: K_1(A) = 0 for all AF-algebras (the identity component of the "
                "unitary group is connected). K_0(A) is a dimension group — a countable "
                "ordered abelian group (G, G^+) that is unperforated (n·g >= 0 implies g >= 0) "
                "and has the Riesz interpolation property. Every such group arises as K_0 "
                "of an AF-algebra (Effros-Handelman-Shen theorem)."
            ),
            chapter_targets=("12", "30"),
        ),
    )


def noncommutative_layer_summary() -> dict[str, int]:
    """Return a count of profiles by presentation_layer."""
    return dict(Counter(
        p.presentation_layer for p in get_named_noncommutative_profiles()
    ))


def noncommutative_chapter_index() -> dict[str, tuple[str, ...]]:
    """Return a mapping from chapter number to profile keys."""
    chapter_map: dict[str, list[str]] = {}
    for p in get_named_noncommutative_profiles():
        for chapter in p.chapter_targets:
            chapter_map.setdefault(chapter, []).append(p.key)
    return {chapter: tuple(keys) for chapter, keys in sorted(chapter_map.items())}


def noncommutative_type_index() -> dict[str, tuple[str, ...]]:
    """Return a mapping from algebra_type to profile keys."""
    index: dict[str, list[str]] = {}
    for p in get_named_noncommutative_profiles():
        index.setdefault(p.algebra_type, []).append(p.key)
    return {k: tuple(v) for k, v in sorted(index.items())}


# ---------------------------------------------------------------------------
# Core analysis functions
# ---------------------------------------------------------------------------

def is_commutative_cstar(space: Any) -> Result:
    """Check whether the C*-algebra is commutative (has a classical Gelfand dual).

    By Gelfand's theorem (1943), a commutative C*-algebra A is isomorphic to C_0(X)
    where X = Spec(A) is the locally compact Hausdorff space of characters. A is unital
    iff X is compact. Key facts:
    - C(X) for compact Hausdorff X is the archetypal commutative C*-algebra.
    - Group C*-algebra C*(G) is commutative iff G is abelian.
    - All commutative C*-algebras are nuclear.
    - Matrix algebras M_n(C) (n >= 2) and the noncommutative torus are NOT commutative.

    Decision layers
    ---------------
    1. Explicit 'commutative_cstar' or 'abelian_cstar' or 'c_of_x' tag -> true.
    2. Gelfand dual / character space tag -> true.
    3. Noncommutative tags (matrix, noncommutative_torus, cuntz, compact_operators) -> false.
    4. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, COMMUTATIVE_CSTAR_TAGS):
        witness = next(t for t in tags if t in COMMUTATIVE_CSTAR_TAGS)
        return Result.true(
            mode="theorem",
            value="commutative_cstar",
            justification=[
                f"Tag {witness!r}: the C*-algebra is commutative — by Gelfand's theorem "
                "it is isomorphic to C_0(X) for some locally compact Hausdorff space X "
                "(the character space / maximal ideal space of the algebra).",
            ],
            metadata={**base, "criterion": "explicit_commutative", "witness": witness},
        )

    if _matches_any(tags, NONCOMMUTATIVE_CSTAR_TAGS | NOT_GELFAND_TAGS):
        blocking = next(t for t in tags if t in (NONCOMMUTATIVE_CSTAR_TAGS | NOT_GELFAND_TAGS))
        return Result.false(
            mode="theorem",
            value="commutative_cstar",
            justification=[
                f"Tag {blocking!r}: the C*-algebra is noncommutative — it cannot be "
                "written as C_0(X). Matrix algebras M_n(C) (n>=2) have no characters; "
                "the noncommutative torus A_theta (theta irrational) is simple with no "
                "classical Gelfand dual.",
            ],
            metadata={**base, "criterion": "noncommutative"},
        )

    return Result.unknown(
        mode="symbolic",
        value="commutative_cstar",
        justification=[
            "Insufficient tags to determine commutativity. "
            "Supply tags such as 'commutative_cstar', 'c_of_x', 'abelian_cstar', "
            "'matrix_algebra', 'noncommutative_torus', or 'cuntz_algebra'.",
        ],
        metadata={**base, "criterion": None},
    )


def is_nuclear_cstar(space: Any) -> Result:
    """Check whether the C*-algebra is nuclear.

    A C*-algebra A is nuclear if the minimal (spatial) tensor product A tensor_min B
    equals the maximal tensor product A tensor_max B for every C*-algebra B. Key facts:
    - All commutative C*-algebras are nuclear.
    - All finite-dimensional C*-algebras (matrix algebras, direct sums) are nuclear.
    - AF-algebras, Cuntz algebras, and the noncommutative torus are nuclear.
    - B(H) (all bounded operators) is NOT nuclear for dim(H) = infty.
    - C*(G) is nuclear iff G is amenable (Day's theorem).
    - Nuclear = amenable in the C*-algebra sense (Connes, Haagerup).

    Decision layers
    ---------------
    1. Explicit 'nuclear_cstar' or nuclear-inducing tags -> true.
    2. Non-nuclear tags (full group algebra of non-amenable group, B(H)) -> false.
    3. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, NUCLEAR_CSTAR_TAGS):
        witness = next(t for t in tags if t in NUCLEAR_CSTAR_TAGS)
        return Result.true(
            mode="theorem",
            value="nuclear_cstar",
            justification=[
                f"Tag {witness!r}: the C*-algebra is nuclear — the minimal and maximal "
                "C*-tensor products with any B coincide. Commutative algebras, AF-algebras, "
                "Cuntz algebras, and group C*-algebras of amenable groups are nuclear.",
            ],
            metadata={**base, "criterion": "explicit_nuclear", "witness": witness},
        )

    not_nuclear = {
        "non_nuclear_cstar",
        "b_of_h",
        "von_neumann_algebra_type_ii",
        "non_amenable_group_cstar",
        "free_group_cstar",
    }
    if _matches_any(tags, not_nuclear):
        blocking = next(t for t in tags if t in not_nuclear)
        return Result.false(
            mode="theorem",
            value="nuclear_cstar",
            justification=[
                f"Tag {blocking!r}: the C*-algebra is NOT nuclear. "
                "B(H) for infinite-dimensional H is not nuclear (the maximal tensor "
                "product strictly exceeds the minimal). Free group algebras C*(F_n) "
                "are not nuclear (F_n is not amenable for n >= 2).",
            ],
            metadata={**base, "criterion": "not_nuclear"},
        )

    return Result.unknown(
        mode="symbolic",
        value="nuclear_cstar",
        justification=[
            "Insufficient tags to determine nuclearity. "
            "Supply tags such as 'nuclear_cstar', 'commutative_cstar', 'af_algebra', "
            "'amenable_group_cstar', 'b_of_h', or 'non_amenable_group_cstar'.",
        ],
        metadata={**base, "criterion": None},
    )


def is_simple_cstar(space: Any) -> Result:
    """Check whether the C*-algebra is simple (no proper closed two-sided ideals).

    A C*-algebra A is simple if its only closed two-sided ideals are {0} and A itself.
    Key facts:
    - M_n(C) is simple for all n >= 1.
    - A_theta (irrational rotation algebra) is simple for theta irrational.
    - Cuntz algebras O_n are purely infinite simple.
    - K(H) is simple (as a non-unital C*-algebra).
    - C(X) is simple iff X is a single point.
    - AF-algebras are generically NOT simple (unless they are the CAR algebra or similar).

    Decision layers
    ---------------
    1. Explicit 'simple_cstar' or known simple classes -> true.
    2. Commutative algebra over non-trivial space, or AF-algebra -> false.
    3. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, SIMPLE_CSTAR_TAGS):
        witness = next(t for t in tags if t in SIMPLE_CSTAR_TAGS)
        return Result.true(
            mode="theorem",
            value="simple_cstar",
            justification=[
                f"Tag {witness!r}: the C*-algebra is simple — no proper closed two-sided "
                "ideals. Irrational rotation algebras, Cuntz algebras, and matrix algebras "
                "M_n(C) are all simple.",
            ],
            metadata={**base, "criterion": "explicit_simple", "witness": witness},
        )

    not_simple = {
        "not_simple_cstar",
        "c_of_compact_space",
        "c_of_x",
        "commutative_cstar",
        "af_algebra",
        "inductive_limit",
        "group_cstar_algebra",
        "reduced_group_cstar",
        "toeplitz_algebra",
    }
    if _matches_any(tags, not_simple):
        blocking = next(t for t in tags if t in not_simple)
        return Result.false(
            mode="theorem",
            value="simple_cstar",
            justification=[
                f"Tag {blocking!r}: the C*-algebra is NOT simple. "
                "C(X) has ideals I_F for every proper closed subset F ⊆ X. "
                "AF-algebras generically have a rich ideal structure (encoded by the "
                "Bratteli diagram). The Toeplitz algebra has K(H) as a proper ideal.",
            ],
            metadata={**base, "criterion": "not_simple"},
        )

    return Result.unknown(
        mode="symbolic",
        value="simple_cstar",
        justification=[
            "Insufficient tags to determine simplicity. "
            "Supply tags such as 'simple_cstar', 'irrational_rotation_algebra', "
            "'cuntz_algebra', 'matrix_algebra', 'commutative_cstar', or 'af_algebra'.",
        ],
        metadata={**base, "criterion": None},
    )


def has_gelfand_dual(space: Any) -> Result:
    """Check whether the C*-algebra has a classical Gelfand dual (is commutative).

    By Gelfand duality, a C*-algebra A has a classical Hausdorff space as its
    'noncommutative space' iff A is commutative. The Gelfand dual is Spec(A) = the
    space of characters (unital *-homomorphisms A -> C). For noncommutative A, Spec(A)
    is empty or trivial, and the 'space' is purely virtual (noncommutative geometry).

    Decision layers
    ---------------
    1. Explicit 'gelfand_dual' or commutative tags -> true.
    2. Noncommutative or no-Gelfand tags -> false.
    3. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, GELFAND_DUAL_TAGS):
        witness = next(t for t in tags if t in GELFAND_DUAL_TAGS)
        return Result.true(
            mode="theorem",
            value="gelfand_dual",
            justification=[
                f"Tag {witness!r}: the algebra has a classical Gelfand dual — it is "
                "commutative and isomorphic to C_0(X) for a locally compact Hausdorff "
                "space X = Spec(A). Points of X correspond to characters of A.",
            ],
            metadata={**base, "criterion": "explicit_gelfand", "witness": witness},
        )

    if _matches_any(tags, NOT_GELFAND_TAGS):
        blocking = next(t for t in tags if t in NOT_GELFAND_TAGS)
        return Result.false(
            mode="theorem",
            value="gelfand_dual",
            justification=[
                f"Tag {blocking!r}: the algebra has NO classical Gelfand dual — it is "
                "noncommutative. Its 'space' exists only in the sense of noncommutative "
                "geometry: the category of A-modules replaces the topology of a space.",
            ],
            metadata={**base, "criterion": "no_gelfand_dual"},
        )

    return Result.unknown(
        mode="symbolic",
        value="gelfand_dual",
        justification=[
            "Insufficient tags to determine Gelfand dual. "
            "Supply tags such as 'gelfand_dual', 'commutative_cstar', 'c_of_x', "
            "'matrix_algebra', 'noncommutative_torus', or 'no_gelfand_dual'.",
        ],
        metadata={**base, "criterion": None},
    )


def has_spectral_triple(space: Any) -> Result:
    """Check whether the algebra carries a spectral triple (Connes' noncommutative geometry).

    A spectral triple (A, H, D) encodes a noncommutative Riemannian geometry:
    - A: a *-algebra (or C*-algebra) acting on a Hilbert space H
    - D: an unbounded self-adjoint operator on H (the 'Dirac operator') with compact
      resolvent (1+D^2)^{-1} in K(H), and [D, a] bounded for all a in A.
    The spectral triple is even if there is a grading operator chi with chi^2 = 1,
    chi D = -D chi, chi a = a chi. Key examples:
    - (C^infty(M), L^2(M, S), D_M): the classical Dirac operator on a spin^c manifold M.
    - (A_theta, L^2(A_theta)^2, D): the noncommutative torus spectral triple.
    - (M_n(C), C^n, D): finite spectral triples encoding finite metric spaces.

    Decision layers
    ---------------
    1. Explicit 'spectral_triple' or Dirac operator tag -> true.
    2. Known classes (spin^c manifold, noncommutative torus, matrix algebra) -> true.
    3. No-spectral-triple or purely-infinite algebras -> false.
    4. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, SPECTRAL_TRIPLE_TAGS):
        witness = next(t for t in tags if t in SPECTRAL_TRIPLE_TAGS)
        return Result.true(
            mode="theorem",
            value="spectral_triple",
            justification=[
                f"Tag {witness!r}: the algebra carries a spectral triple (A, H, D) — "
                "a noncommutative Riemannian geometry. The Dirac operator D encodes "
                "the metric via d(phi, psi) = sup{|phi(a)-psi(a)| : ||[D,a]|| <= 1}.",
            ],
            metadata={**base, "criterion": "explicit_spectral_triple", "witness": witness},
        )

    spectral_triple_classes = {
        "matrix_algebra",
        "noncommutative_torus",
        "irrational_rotation_algebra",
        "spinc_manifold",
        "riemannian_manifold_algebra",
        "c_of_compact_space",
    }
    if _matches_any(tags, spectral_triple_classes):
        witness = next(t for t in tags if t in spectral_triple_classes)
        return Result.true(
            mode="theorem",
            value="spectral_triple",
            justification=[
                f"Tag {witness!r}: this class of algebras canonically carries a spectral "
                "triple. Matrix algebras have finite spectral triples; the noncommutative "
                "torus has a 2-dimensional Dirac spectral triple; commutative C(M) on a "
                "spin^c manifold has the classical Atiyah-Singer Dirac operator.",
            ],
            metadata={**base, "criterion": "known_spectral_triple_class", "witness": witness},
        )

    no_spectral_triple = {
        "no_spectral_triple",
        "purely_infinite_no_trace",
        "cuntz_algebra",
        "af_algebra",
        "group_cstar_algebra",
    }
    if _matches_any(tags, no_spectral_triple):
        blocking = next(t for t in tags if t in no_spectral_triple)
        return Result.false(
            mode="theorem",
            value="spectral_triple",
            justification=[
                f"Tag {blocking!r}: no canonical spectral triple for this class. "
                "Purely infinite algebras (Cuntz, O_n) and general AF-algebras typically "
                "lack a natural Dirac operator with compact resolvent.",
            ],
            metadata={**base, "criterion": "no_spectral_triple"},
        )

    return Result.unknown(
        mode="symbolic",
        value="spectral_triple",
        justification=[
            "Insufficient tags to determine spectral triple. "
            "Supply tags such as 'spectral_triple', 'dirac_operator', 'matrix_algebra', "
            "'noncommutative_torus', 'cuntz_algebra', or 'spinc_manifold'.",
        ],
        metadata={**base, "criterion": None},
    )


def classify_noncommutative(space: Any) -> dict[str, Any]:
    """Classify the noncommutative topology type of the C*-algebra.

    Keys
    ----
    algebra_class : str
        One of ``"commutative"``, ``"simple_nuclear"``, ``"nuclear"``,
        ``"simple"``, ``"general"``, ``"unknown"``.
    is_commutative : Result
    is_nuclear : Result
    is_simple : Result
    has_gelfand_dual : Result
    has_spectral_triple : Result
    key_properties : list[str]
    representation : str
    tags : list[str]
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)

    comm_r = is_commutative_cstar(space)
    nuclear_r = is_nuclear_cstar(space)
    simple_r = is_simple_cstar(space)
    gelfand_r = has_gelfand_dual(space)
    spectral_r = has_spectral_triple(space)

    if comm_r.is_true:
        algebra_class = "commutative"
    elif simple_r.is_true and nuclear_r.is_true:
        algebra_class = "simple_nuclear"
    elif nuclear_r.is_true:
        algebra_class = "nuclear"
    elif simple_r.is_true:
        algebra_class = "simple"
    elif comm_r.is_false or nuclear_r.is_false or simple_r.is_false:
        algebra_class = "general"
    else:
        algebra_class = "unknown"

    key_properties: list[str] = []
    if comm_r.is_true:
        key_properties.append("commutative")
    if comm_r.is_false:
        key_properties.append("noncommutative")
    if nuclear_r.is_true:
        key_properties.append("nuclear")
    if nuclear_r.is_false:
        key_properties.append("non_nuclear")
    if simple_r.is_true:
        key_properties.append("simple")
    if simple_r.is_false:
        key_properties.append("not_simple")
    if gelfand_r.is_true:
        key_properties.append("gelfand_dual_exists")
    if gelfand_r.is_false:
        key_properties.append("no_gelfand_dual")
    if spectral_r.is_true:
        key_properties.append("spectral_triple")
    if _matches_any(tags, KTHEORY_TAGS):
        key_properties.append("ktheory_nontrivial")
    if _matches_any(tags, MORITA_EQUIVALENCE_TAGS):
        key_properties.append("morita_context")

    return {
        "algebra_class": algebra_class,
        "is_commutative": comm_r,
        "is_nuclear": nuclear_r,
        "is_simple": simple_r,
        "has_gelfand_dual": gelfand_r,
        "has_spectral_triple": spectral_r,
        "key_properties": key_properties,
        "representation": representation,
        "tags": sorted(tags),
    }


def noncommutative_profile(space: Any) -> dict[str, Any]:
    """Full noncommutative topology profile combining classification and named examples.

    Keys
    ----
    classification : dict
        Output of :func:`classify_noncommutative`.
    named_profiles : tuple[NoncommutativeProfile, ...]
        Registry of canonical noncommutative topology examples.
    layer_summary : dict[str, int]
        Profile count by presentation_layer.
    """
    return {
        "classification": classify_noncommutative(space),
        "named_profiles": get_named_noncommutative_profiles(),
        "layer_summary": noncommutative_layer_summary(),
    }


# ---------------------------------------------------------------------------
# Computational engines (P8.5)
# ---------------------------------------------------------------------------

def k0_group_matrix_algebra(n: int) -> dict[str, Any]:
    """K₀ group of the matrix algebra M_n(ℚ).

    By Morita invariance of K-theory: K₀(M_n(ℚ)) ≅ K₀(ℚ) ≅ ℤ.
    The generator is [P₁], the class of a rank-1 projection in M_n(ℚ).
    The identity [I_n] = n · [P₁] in K₀(M_n(ℚ)).

    Parameters
    ----------
    n: matrix size (n ≥ 1)

    Returns
    -------
    dict with ``K0_rank``, ``generator_class``, ``identity_class``,
    ``morita_equivalent_to_Q``, ``description``.

    Examples
    --------
    >>> k0_group_matrix_algebra(3)["identity_class"]
    3
    >>> k0_group_matrix_algebra(1)["K0_rank"]
    1
    """
    if n < 1:
        raise ValueError(f"n must be ≥ 1, got {n}")
    return {
        "K0_rank": 1,
        "generator_class": 1,
        "identity_class": n,
        "morita_equivalent_to_Q": True,
        "description": (
            f"K₀(M_{n}(ℚ)) ≅ ℤ  (Morita invariance); "
            f"generator = [rank-1 projector], [I_{n}] = {n}"
        ),
    }


def spectral_dimension_finite(
    eigenvalues: list[float],
    threshold: float = 1e-10,
) -> dict[str, Any]:
    """Estimate spectral dimension d_s from eigenvalue growth of a Dirac operator.

    The spectral dimension satisfies Tr(e^{-tD²}) ~ t^{-d_s/2} as t → 0⁺.
    By Karamata's theorem this is equivalent to the eigenvalue counting function
    N(λ) ~ C · λ^{d_s/2}, so we fit d_s via log-log linear regression on
    {(log λ_k, log k)} pairs (positive eigenvalues only).

    Parameters
    ----------
    eigenvalues: non-negative eigenvalues of |D| or D² (need not be sorted)
    threshold: eigenvalues below this are considered zero and excluded

    Returns
    -------
    dict with ``spectral_dimension``, ``n_positive_eigenvalues``, ``slope``.

    Examples
    --------
    Flat torus (2D): Weyl law gives N(λ) ~ λ, so d_s ≈ 2:

    >>> evs = list(range(1, 50))
    >>> abs(spectral_dimension_finite(evs)["spectral_dimension"] - 2.0) < 0.5
    True
    """
    import math
    pos = sorted(v for v in eigenvalues if v > threshold)
    n = len(pos)
    if n < 2:
        return {"spectral_dimension": 0.0, "n_positive_eigenvalues": n, "slope": 0.0}
    log_lam = [math.log(v) for v in pos]
    log_k = [math.log(k + 1) for k in range(n)]
    sx = sum(log_lam)
    sy = sum(log_k)
    sxx = sum(x * x for x in log_lam)
    sxy = sum(x * y for x, y in zip(log_lam, log_k))
    denom = n * sxx - sx * sx
    slope = (n * sxy - sx * sy) / denom if abs(denom) > 1e-15 else 0.0
    return {
        "spectral_dimension": 2.0 * slope,
        "n_positive_eigenvalues": n,
        "slope": slope,
    }


def k1_group_matrix_algebra(n: int) -> dict[str, Any]:
    """K₁ group of the matrix algebra M_n(ℚ).

    By Morita invariance: K₁(M_n(ℚ)) ≅ K₁(ℚ) ≅ GL₁(ℚ)^{ab} = ℚ*.
    The abelian group ℚ* ≅ ℤ/2 × ⊕_p ℤ  (sign × p-adic valuations).
    The determinant det: GL_n(ℚ)^{ab} → ℚ* is an isomorphism (Whitehead lemma).

    Parameters
    ----------
    n: matrix size (n ≥ 1)

    Returns
    -------
    dict with ``K1_description``, ``torsion_part``, ``free_part_description``,
    ``determinant_isomorphism``, ``morita_invariant``, ``description``.

    Examples
    --------
    >>> k1_group_matrix_algebra(2)["torsion_part"]
    'ℤ/2'
    >>> k1_group_matrix_algebra(5)["morita_invariant"]
    True
    """
    if n < 1:
        raise ValueError(f"n must be ≥ 1, got {n}")
    return {
        "K1_description": "ℚ* ≅ ℤ/2 × (⊕_p ℤ)",
        "torsion_part": "ℤ/2",
        "free_part_description": "one ℤ summand per prime p (p-adic valuation v_p)",
        "determinant_isomorphism": (
            f"det: GL_{n}(ℚ)^{{ab}} → ℚ* is an isomorphism (Whitehead lemma)"
        ),
        "morita_invariant": True,
        "description": f"K₁(M_{n}(ℚ)) ≅ K₁(ℚ) ≅ ℚ*  (Morita invariance)",
    }


__all__ = [
    "NoncommutativeProfile",
    "COMMUTATIVE_CSTAR_TAGS",
    "NONCOMMUTATIVE_CSTAR_TAGS",
    "NUCLEAR_CSTAR_TAGS",
    "SIMPLE_CSTAR_TAGS",
    "SPECTRAL_TRIPLE_TAGS",
    "GELFAND_DUAL_TAGS",
    "NOT_GELFAND_TAGS",
    "MORITA_EQUIVALENCE_TAGS",
    "KTHEORY_TAGS",
    "get_named_noncommutative_profiles",
    "noncommutative_layer_summary",
    "noncommutative_chapter_index",
    "noncommutative_type_index",
    "is_commutative_cstar",
    "is_nuclear_cstar",
    "is_simple_cstar",
    "has_gelfand_dual",
    "has_spectral_triple",
    "classify_noncommutative",
    "noncommutative_profile",
    # P8.5 computational engines
    "k0_group_matrix_algebra",
    "spectral_dimension_finite",
    "k1_group_matrix_algebra",
]
