r"""Operads: symmetric/non-symmetric operads, Koszul duality, bar-cobar constructions,
A-infinity/L-infinity/E-infinity algebras, little disks operads, tree compositions.

Key theorems and constructions implemented
------------------------------------------
- Operad (symmetric): a symmetric operad P is a collection {P(n)}_{n>=0} of S_n-modules
  (right modules over the symmetric group S_n) together with composition maps:
  gamma: P(k) tensor P(n_1) tensor ... tensor P(n_k) -> P(n_1 + ... + n_k),
  a unit 1 in P(1), subject to associativity, unity, and equivariance axioms.
  Equivalently, P is a monoid in the category (Seq, tensor_circ, I) of symmetric sequences
  with respect to the composition product: (P circ Q)(n) = direct_sum_{k>=0} P(k)
  tensor_{S_k} Q^{tensor k}(n). An algebra over P is a vector space (or object) A
  together with maps P(n) tensor_{S_n} A^{tensor n} -> A satisfying unit and
  associativity with respect to the operad structure. Key examples:
  - Ass: the associative operad with Ass(n) = k[S_n] (free S_n-module of rank 1);
    Ass-algebras are exactly associative algebras.
  - Com: the commutative operad with Com(n) = k (trivial S_n-module of rank 1);
    Com-algebras are exactly commutative associative algebras.
  - Lie: the Lie operad encoding the Lie bracket; Lie-algebras are Lie algebras.
  Non-symmetric (planar) operad: same as above but without the S_n-action; algebras
  are algebras with ordered inputs. Non-symmetric Ass encodes associative algebras;
  non-symmetric Com does not make sense (commutativity requires the transposition).

- Koszul duality for operads (Ginzburg-Kapranov, 1994): a binary quadratic operad P
  (generated by binary operations with quadratic relations) has a Koszul dual operad P^!.
  A quadratic operad P = (E, R) is presented by generators E in arity 2 and quadratic
  relations R in E circ E. The Koszul dual: P^! = (E^*, R^\perp) where E^* = Hom(E, k)
  with twisted S_2-action, and R^\perp is the orthogonal complement of R under the
  natural pairing. Fundamental examples:
  - Com^! = Lie, Lie^! = Com (Com and Lie are Koszul dual to each other).
  - Ass^! = Ass (associative operad is self-dual up to twist).
  Koszul operads: P is Koszul if the augmentation epsilon: B(P^!) -> k is a
  quasi-isomorphism, where B denotes the bar construction. Equivalently, the Koszul
  complex P^! circ_kappa P is acyclic (quasi-isomorphic to the unit operad I).
  Consequence: if P is Koszul, then P^{infty} = Omega(P^!) (bar-cobar construction)
  is the minimal resolution of P, whose algebras are P-algebras up to homotopy
  (P_infty-algebras). The main theorem: Ass, Com, and Lie are all Koszul operads.

- Bar-cobar constructions: for an augmented operad P (with augmentation P -> I), the
  bar construction B(P) is a cooperad (graded, with a differential making it a dg-cooperad)
  with B(P) = T^c(s P_+) (cofree cooperad on the suspension of the augmentation ideal).
  The cobar construction Omega(C) of an augmented cooperad C is the operad
  Omega(C) = T(s^{-1} C_+) with differential induced by the coproduct of C.
  Adjunction: (Omega, B) form an adjoint pair between dg-operads and dg-cooperads.
  The counit Omega(B(P)) -> P is a quasi-isomorphism for augmented operads (always),
  and the unit P^! -> B(P)/relations is a quasi-isomorphism iff P is Koszul.
  Applications: the bar construction B(P) is used to define P-infinity algebras
  (via their Maurer-Cartan elements), and the Koszul complex is the twisted composite.

- A-infinity algebras (Stasheff, 1963): an A-infinity algebra (A_infty-algebra) is a
  graded vector space A with a collection of multilinear maps {m_n: A^{tensor n} -> A}_{n>=1}
  of degree 2-n satisfying the A_infty-relations:
  sum_{n=r+s+t} (-1)^{rs+t} m_{r+1+t}(id^r tensor m_s tensor id^t) = 0 for all n>=1.
  For n=1: m_1 circ m_1 = 0 (m_1 is a differential);
  for n=2: m_1 m_2 = m_2(m_1 tensor 1 + 1 tensor m_1) (derivation condition);
  for n=3: the failure of m_2 to be associative is controlled by m_3 (homotopy).
  If m_n = 0 for n>=3: A_infty reduces to a dg-algebra (differential graded associative).
  If additionally m_1 = 0: A_infty reduces to a graded associative algebra.
  A_infty-algebras are the algebras over the A_infty operad = Omega(Ass^!).
  Homotopy transfer theorem: any A_infty algebra structure on a complex (A, d) can be
  transferred to any homotopy retract of A, producing an A_infty structure on the
  cohomology H^*(A). This is fundamental in homological perturbation theory.

- L-infinity algebras: an L_infty-algebra (L_infty = strong homotopy Lie algebra) is a
  graded vector space L with maps {l_n: Lambda^n L -> L}_{n>=1} (alternating, degree 2-n)
  satisfying generalized Jacobi identities:
  sum_{i+j=n+1} sum_{sigma} (-1)^sigma (-1)^{i(j-1)} l_j(l_i(x_{sigma(1)},...), ...) = 0.
  For n=1: l_1^2 = 0 (differential); for n=2: Jacobi up to homotopy controlled by l_3.
  L_infty-algebras are the algebras over L_infty = Omega(Lie^!) = Omega(Com).
  Applications: formal deformation theory (Maurer-Cartan elements of a dgla control
  deformations), derived geometry (L_infty-algebras arise as tangent complexes of
  derived stacks), and string field theory (L_infty-structure on closed string field theory).
  Homotopy transfer: L_infty structures transfer along homotopy retracts; every
  dg-Lie algebra is L_infty-quasi-isomorphic to its cohomology (with transferred structure).

- Little disks operads E_n (Boardman-Vogt, May): the little n-disks operad D_n has
  D_n(k) = space of k disjoint little n-dimensional disks embedded in the unit disk D^n
  (rectilinearly, i.e., affine embeddings). Composition: substitute little disks into disks.
  E_n = D_n as an operad in topological spaces (or its homology H_*(D_n)).
  Key properties:
  - E_1 ≃ Ass (over k, H_*(E_1) ≅ Ass): E_1-algebras ≅ A_infty-algebras.
  - E_infty = colim_n E_n ≃ Com (over k): E_infty-algebras ≅ strictly commutative algebras up to homotopy.
  - E_n-algebras interpolate between A_infty (n=1) and E_infty (n=infty).
  Cohomology of configuration spaces: H_*(D_n(k)) = Poisson_n(k) operad (for n>=2).
  Recognition principle (May): a connected (n-1)-fold loop space Omega^{n-1}X is
  group-complete E_n-algebra. The delooping machine: E_n-algebras are equivalent (up
  to group completion) to n-fold loop spaces.
  Factorization homology (Ayala-Francis): for M an n-manifold, the factorization homology
  int_M A of an E_n-algebra A is a topological invariant, generalizing Hochschild homology.
"""

from __future__ import annotations

from collections import Counter
from dataclasses import dataclass
from typing import Any

from .result import Result

# ---------------------------------------------------------------------------
# OperadProfile dataclass
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class OperadProfile:
    """A curated operad theory example."""

    key: str
    display_name: str
    operad_type: str        # "symmetric", "nonsymmetric", "cyclic", "modular",
                            # "colored", "infinity", "topological"
    algebra_type: str       # "associative", "commutative", "lie", "a_infinity",
                            # "l_infinity", "e_n", "general", "poisson"
    is_koszul: bool         # Koszul operad (Koszul complex is acyclic)
    has_koszul_dual: bool   # has a known Koszul dual operad
    is_binary_quadratic: bool  # generated by binary operations with quadratic relations
    is_self_dual: bool      # P^! ≅ P (up to twist / suspension)
    admits_infinity_version: bool  # has a well-defined P_infty minimal resolution
    presentation_layer: str
    focus: str
    chapter_targets: tuple[str, ...]


# ---------------------------------------------------------------------------
# Tag constants
# ---------------------------------------------------------------------------

ASSOC_OPERAD_TAGS: frozenset[str] = frozenset({
    "assoc_operad",
    "associative_operad",
    "ass_operad",
    "associative_algebra",
    "a_infinity",
    "a_infinity_algebra",
    "stasheff_associahedra",
    "homotopy_associative",
})

COMM_OPERAD_TAGS: frozenset[str] = frozenset({
    "comm_operad",
    "commutative_operad",
    "com_operad",
    "commutative_algebra",
    "e_infinity",
    "e_infinity_algebra",
    "cdga",
    "commutative_dga",
})

LIE_OPERAD_TAGS: frozenset[str] = frozenset({
    "lie_operad",
    "lie_algebra_operad",
    "l_infinity",
    "l_infinity_algebra",
    "homotopy_lie",
    "dgla",
    "differential_graded_lie",
    "maurer_cartan",
})

KOSZUL_DUALITY_TAGS: frozenset[str] = frozenset({
    "koszul_duality",
    "koszul_operad",
    "koszul_dual",
    "koszul_complex",
    "quadratic_dual",
    "ginzburg_kapranov",
    "koszul_resolution",
    "binary_quadratic",
})

INFINITY_ALGEBRA_TAGS: frozenset[str] = frozenset({
    "infinity_algebra",
    "homotopy_algebra",
    "a_infinity",
    "l_infinity",
    "c_infinity",
    "homotopy_transfer",
    "minimal_model",
    "bar_cobar",
})

LITTLE_DISKS_TAGS: frozenset[str] = frozenset({
    "little_disks_operad",
    "little_n_disks",
    "e_n_operad",
    "e1_operad",
    "e2_operad",
    "e_infinity_operad",
    "recognition_principle",
    "loop_space_operad",
    "factorization_homology",
    "boardman_vogt",
})

TREE_COMPOSITION_TAGS: frozenset[str] = frozenset({
    "tree_composition",
    "planar_tree",
    "rooted_tree",
    "operadic_composition",
    "partial_composition",
    "symmetric_sequence",
    "composition_product",
    "operad_axioms",
    "nonsymmetric_operad",
})

BAR_COBAR_TAGS: frozenset[str] = frozenset({
    "bar_construction",
    "cobar_construction",
    "bar_cobar_adjunction",
    "twisting_morphism",
    "dg_operad",
    "dg_cooperad",
    "operadic_homology",
    "augmented_operad",
    "koszul_twisting",
})


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _extract_tags(space: Any) -> set[str]:
    raw = getattr(space, "tags", None) or getattr(space, "_tags", None)
    if isinstance(raw, (set, list, tuple, frozenset)):
        return {str(t).strip().lower() for t in raw}
    return set()


def _representation_of(space: Any) -> str:
    metadata = getattr(space, "metadata", {}) or {}
    if isinstance(metadata, dict) and "representation" in metadata:
        return str(metadata["representation"]).strip().lower()
    rep = getattr(space, "representation", None)
    if rep:
        return str(rep).strip().lower()
    return "symbolic_general"


def _matches_any(tags: set[str], candidates: set[str] | frozenset[str]) -> bool:
    return bool(tags & candidates)


# ---------------------------------------------------------------------------
# Named example registry
# ---------------------------------------------------------------------------

def get_named_operad_profiles() -> tuple[OperadProfile, ...]:
    """Return the registry of canonical operad theory examples."""
    return (
        OperadProfile(
            key="assoc_operad",
            display_name="Ass — associative operad encoding associative algebras",
            operad_type="symmetric",
            algebra_type="associative",
            is_koszul=True,
            has_koszul_dual=True,
            is_binary_quadratic=True,
            is_self_dual=True,
            admits_infinity_version=True,
            presentation_layer="main_text",
            focus=(
                "The associative operad Ass is the operad governing associative algebras. "
                "Concretely: Ass(n) = k[S_n] (the group algebra of S_n, rank n! as a "
                "k-module), with the composition given by block permutations. "
                "An Ass-algebra structure on a k-module A is exactly an associative "
                "multiplication m: A tensor A -> A with m(m tensor 1) = m(1 tensor m). "
                "Presentation: Ass = Free(mu) / (mu(mu, 1) - mu(1, mu)) where mu in "
                "arity 2 is the generating binary operation and the relation is "
                "associativity. As a quadratic operad: E = k[S_2] (one generator mu of "
                "arity 2 in each S_2-orbit), R = mu(mu,1) - mu(1,mu) (associativity). "
                "Koszul: Ass is Koszul (Koszul dual Ass^! = Ass with opposite S_n-action, "
                "i.e., self-dual up to a sign twist). Proof: the Koszul complex "
                "Ass^! circ_kappa Ass is acyclic (Priddy resolution). "
                "Free Ass-algebra: the free Ass-algebra on a set X is the tensor algebra "
                "T(V) = direct_sum_{n>=0} V^{tensor n} for V = k*X. "
                "A_infty-algebras: the minimal resolution Ass_infty = Omega(Ass^!) "
                "is the A_infty operad; Ass_infty-algebras have operations {m_n}_{n>=1} "
                "satisfying the A_infty-relations (Stasheff 1963). The underlying "
                "space of the A_infty operad is the Stasheff associahedra K_n. "
                "Homotopy transfer: every A_infty-algebra structure transfers along "
                "strong deformation retracts; every dg-algebra is quasi-isomorphic to "
                "an A_infty-algebra whose higher operations encode the 'homotopy commutativity'."
            ),
            chapter_targets=("55", "66", "78"),
        ),
        OperadProfile(
            key="comm_operad",
            display_name="Com — commutative operad encoding commutative associative algebras",
            operad_type="symmetric",
            algebra_type="commutative",
            is_koszul=True,
            has_koszul_dual=True,
            is_binary_quadratic=True,
            is_self_dual=False,
            admits_infinity_version=True,
            presentation_layer="main_text",
            focus=(
                "The commutative operad Com is the operad governing commutative "
                "associative algebras. Com(n) = k (the trivial S_n-module, rank 1 for "
                "all n), reflecting that commutative algebras have a unique n-ary "
                "operation (the n-fold product) regardless of input order. "
                "An Com-algebra on A is a commutative associative k-algebra. "
                "Presentation: Com = Free(mu) / (mu(mu,1) - mu(1,mu), mu - mu*tau) "
                "where tau in S_2 is the transposition and the second relation is "
                "commutativity. As a quadratic operad: E = k (one generator, trivial "
                "S_2-action), R = {associativity, commutativity}. "
                "Koszul dual: Com^! = Lie (the Lie operad). This is the fundamental "
                "Ginzburg-Kapranov duality: commutative algebras are Koszul dual to Lie "
                "algebras. The Koszul complex Com^! circ_kappa Com = Lie circ_kappa Com "
                "is the Chevalley-Eilenberg complex. "
                "Koszulness: Com is Koszul. Proof via the distributive law between Ass "
                "and Com (Harrison complex acyclicity). "
                "C_infty-algebras: the minimal resolution Com_infty = Omega(Lie) "
                "gives C_infty-algebras (homotopy commutative associative algebras). "
                "These are formal dgca's up to homotopy: C_infty implies A_infty, and "
                "the additional operations encode commutativity up to homotopy. "
                "Free Com-algebra: the free Com-algebra on V is the polynomial algebra "
                "Sym(V) = direct_sum_{n>=0} Sym^n(V) (symmetric powers of V). "
                "E_infty-algebras: topological E_infty-algebras (algebras over E_infty = "
                "colim E_n) model 'strictly commutative' algebras up to all higher homotopy; "
                "E_infty-ring spectra in stable homotopy theory represent generalized "
                "cohomology theories with cup product."
            ),
            chapter_targets=("55", "66", "78"),
        ),
        OperadProfile(
            key="lie_operad",
            display_name="Lie — Lie operad encoding Lie algebras; Koszul dual of Com",
            operad_type="symmetric",
            algebra_type="lie",
            is_koszul=True,
            has_koszul_dual=True,
            is_binary_quadratic=True,
            is_self_dual=False,
            admits_infinity_version=True,
            presentation_layer="main_text",
            focus=(
                "The Lie operad Lie governs Lie algebras. As a symmetric sequence: "
                "Lie(n) is the module of Lie words in n letters (the multilinear part of "
                "the free Lie algebra on n generators), with dim Lie(n) = (n-1)! as a "
                "k-module (n >= 1). "
                "Presentation: Lie = Free(lambda) / (lambda(lambda,1) + lambda(lambda,1)*sigma + "
                "lambda(lambda,1)*sigma^2, lambda + lambda*tau) where lambda is the bracket "
                "[,], tau is the transposition (anti-commutativity), and the cyclic relation "
                "encodes the Jacobi identity sum [x,[y,z]] + [y,[z,x]] + [z,[x,y]] = 0. "
                "Koszul dual: Lie^! = Com (the commutative operad). "
                "Koszulness: Lie is Koszul (Harrison homology of Com = Chevalley-Eilenberg "
                "homology, proved to be acyclic for the Koszul complex). "
                "Chevalley-Eilenberg complex: for a Lie algebra g, the CE-complex "
                "C_*(g) = (Lambda(g[1]), d_{CE}) computes Lie algebra homology H_*(g, k). "
                "This complex is exactly the bar construction B(Com^!) applied to a "
                "Com-algebra (symmetric algebra), which recovers the CE-complex. "
                "L_infty-algebras: the minimal resolution Lie_infty = Omega(Com) "
                "gives L_infty-algebras with brackets {l_n}_{n>=1} satisfying the "
                "generalized Jacobi identities. These encode 'Lie algebra up to homotopy'. "
                "Deformation theory (Maurer-Cartan): for a dgla (g, d, [,]), Maurer-Cartan "
                "elements are solutions to da + (1/2)[a,a] = 0 in g^1. They parametrize "
                "deformations of the associated algebra; the L_infty-version governs "
                "formal deformation problems via the derived moduli stack."
            ),
            chapter_targets=("55", "66", "78"),
        ),
        OperadProfile(
            key="a_infinity_operad",
            display_name="A_infty — minimal resolution of Ass; homotopy associative algebras",
            operad_type="nonsymmetric",
            algebra_type="a_infinity",
            is_koszul=False,
            has_koszul_dual=False,
            is_binary_quadratic=False,
            is_self_dual=False,
            admits_infinity_version=False,
            presentation_layer="main_text",
            focus=(
                "The A_infty operad is the minimal resolution of the associative operad "
                "Ass, defined as Ass_infty = Omega(Ass^c) where Ass^c = (Ass^!)^* is the "
                "Koszul dual cooperad of Ass. Concretely: Ass_infty(n) = k[S_n] tensor k*[n-2] "
                "(shifted), with generators m_n of arity n and degree 2-n, and differential "
                "given by the sum over (i,j)-splits of m_{i+1+j}(id^i tensor m_k tensor id^j). "
                "A_infty-algebra: a dg-module A with operations {m_n: A^{tensor n} -> A}_{n>=1}, "
                "deg(m_n) = 2-n, satisfying: for each n>=1, "
                "sum_{i+j+k=n} (-1)^{ij+k} m_{i+1+k}(id^i tensor m_j tensor id^k) = 0. "
                "m_1: A -> A is the differential (m_1^2 = 0). "
                "m_2: A tensor A -> A is the multiplication (associative up to m_3). "
                "m_3: A^{tensor 3} -> A is the homotopy for associativity. "
                "Homotopy transfer theorem: let (A, {m_n}) be an A_infty-algebra and "
                "i: H -> A, p: A -> H, h: A -> A a deformation retract of A onto H = H^*(A). "
                "Then H carries an induced A_infty-structure {m_n^H} with "
                "m_n^H = sum_T p m_{|T|} (tensor products of m_k's decorated by h) over "
                "planar binary trees T. The sum formula is exactly the sum over "
                "Stasheff associahedra vertices. "
                "Formality: a dg-algebra A is formal if there is an A_infty quasi-isomorphism "
                "A -> H^*(A) with zero higher multiplications m_{n>=3}. "
                "Hochschild cohomology controls A_infty-deformations: "
                "HH^*(A, A) = Ext_{A-A}^*(A, A) classifies A_infty-deformations of A."
            ),
            chapter_targets=("55", "66", "78"),
        ),
        OperadProfile(
            key="l_infinity_operad",
            display_name="L_infty — minimal resolution of Lie; strong homotopy Lie algebras",
            operad_type="symmetric",
            algebra_type="l_infinity",
            is_koszul=False,
            has_koszul_dual=False,
            is_binary_quadratic=False,
            is_self_dual=False,
            admits_infinity_version=False,
            presentation_layer="main_text",
            focus=(
                "The L_infty operad is the minimal resolution of the Lie operad: "
                "Lie_infty = Omega(Lie^!) = Omega(Com^c). Lie_infty(n) = "
                "(sgn_n)[n-2] (sign representation shifted), with generators l_n in arity n. "
                "L_infty-algebra: a graded vector space L with maps "
                "{l_n: Lambda^n L -> L}_{n>=1}, deg(l_n) = 2-n, alternating, satisfying "
                "for each n: sum_{i+j=n+1} sum_{sigma in S(i;j)} (-1)^sigma epsilon(sigma) "
                "(-1)^{i(j-1)} l_j(l_i(x_{sigma(1)}, ..., x_{sigma(i)}), x_{sigma(i+1)}, ...) = 0. "
                "l_1 = d: L -> L is a differential; l_2 = [,] the Lie bracket; "
                "l_3 is the Jacobiator (homotopy for Jacobi). "
                "Maurer-Cartan equation: for an L_infty-algebra (L, {l_n}), the MC-equation is "
                "sum_{n>=1} (1/n!) l_n(a, ..., a) = 0 for a in L^1 (odd degree). "
                "Solutions are Maurer-Cartan elements; they parametrize deformations. "
                "Derived geometry: L_infty-algebras arise as tangent complexes of derived "
                "Artin stacks; the L_infty-structure on the tangent complex controls the "
                "deformation-obstruction theory of the stack. "
                "Rational homotopy theory: Sullivan minimal models and Quillen's dg-Lie "
                "algebras both model rational homotopy types; L_infty-algebras unify both. "
                "For a simply-connected space X: the rational homotopy groups pi_*(X) tensor Q "
                "form an L_infty-algebra, and X is formal iff its L_infty-structure on "
                "cohomology has l_{n>=3} = 0. "
                "Kontsevich formality: the Kontsevich formality theorem (1997) states that "
                "the Hochschild cochain complex C^*(A, A) is L_infty-quasi-isomorphic to "
                "the Hochschild cohomology HH^*(A, A) (equipped with the Gerstenhaber bracket). "
                "This implies the deformation quantization of Poisson manifolds."
            ),
            chapter_targets=("55", "66", "78"),
        ),
        OperadProfile(
            key="little_disks_e2",
            display_name="E_2 — little 2-disks operad; braided monoidal categories, Gerstenhaber",
            operad_type="topological",
            algebra_type="e_n",
            is_koszul=True,
            has_koszul_dual=True,
            is_binary_quadratic=False,
            is_self_dual=False,
            admits_infinity_version=True,
            presentation_layer="main_text",
            focus=(
                "The little 2-disks operad E_2 = D_2 is the operad of configurations of "
                "k little rectilinear disks inside the standard unit disk D^2 in R^2. "
                "D_2(k) = {(z_1, r_1, ..., z_k, r_k) : |z_i - z_j| > r_i + r_j, |z_i| + r_i < 1}. "
                "The composition gamma: D_2(k) x D_2(n_1) x ... x D_2(n_k) -> D_2(sum n_i) "
                "rescales and inserts the n_i-configurations into the i-th disk. "
                "Homology H_*(D_2): the homology H_*(D_2(k)) is concentrated in degree 0 and "
                "(k choose 2) with generators being the fundamental classes. Over k, "
                "H_*(D_2) is the Gerstenhaber operad (= Poisson_2 = BV without the BV "
                "operator). An algebra over H_*(D_2) is a Gerstenhaber algebra: "
                "a graded commutative algebra with a Lie bracket of degree -1 compatible "
                "via the Leibniz rule. "
                "Koszul: H_*(E_2) is Koszul (Fresse, Tourtchine), and the Koszul dual "
                "is the Poisson_2 operad. "
                "Recognition principle: a 2-fold loop space Omega^2 X carries an E_2-algebra "
                "structure (May's recognition theorem), and conversely every group-complete "
                "E_2-algebra is equivalent to a 2-fold loop space (delooping machine). "
                "Factorization homology int_{S^1} A: for an E_2-algebra A, the factorization "
                "homology over S^1 recovers the Hochschild homology HH_*(A). Over surfaces "
                "Sigma_g, factorization homology gives invariants related to skein algebras "
                "and quantum groups at roots of unity. "
                "Relationship to braids: pi_1(D_2(k)) = PB_k (pure braid group), hence "
                "E_2-algebras have a natural action of the braid groups, making them "
                "equivalent to braided monoidal categories (after group completion). "
                "E_1 = Ass, E_2, ..., E_infty = Com interpolate from strictly associative "
                "to strictly commutative, with E_n controlling n-fold loop spaces."
            ),
            chapter_targets=("55", "66", "78"),
        ),
        OperadProfile(
            key="koszul_duality_example",
            display_name="Koszul duality Com^! = Lie — fundamental duality in operad theory",
            operad_type="symmetric",
            algebra_type="general",
            is_koszul=True,
            has_koszul_dual=True,
            is_binary_quadratic=True,
            is_self_dual=False,
            admits_infinity_version=True,
            presentation_layer="main_text",
            focus=(
                "The Koszul duality for operads, introduced by Ginzburg-Kapranov (1994), "
                "generalizes the classical Koszul duality for associative algebras to the "
                "world of operads. For a binary quadratic operad P = F(E)/(R): "
                "1. Dual generators: E^* = Hom_k(E, k) with twisted S_2-action "
                "(tensored with the sign representation sgn_2). "
                r"2. Dual relations: R^\perp = {f in E^* circ E^* : f|_R = 0}. "
                r"3. Koszul dual operad: P^! = F(E^*[1])/(R^\perp). "
                "The sign shift [1] accounts for the suspension in the bar construction. "
                "Fundamental examples: "
                "Com^! = Lie: taking E = k (trivial S_2-action), R = {associativity + "
                "commutativity}, we get E^*[1] = sgn_2 (sign representation) with "
                r"R^\perp = {Jacobi identity} — exactly the Lie operad. "
                "Lie^! = Com: dualizing back, (Lie)^! = Com. "
                "Ass^! = Ass: E = k[S_2], and E^*[1] = k[S_2] tensor sgn_2 which, as an "
                "S_2-module, is isomorphic to k[S_2] tensor sgn_2 = Ass(2) tensor sgn (the "
                "'opposite' Ass). This gives Ass^! = Ass^{op} ≅ Ass via a twist. "
                "Koszul complex: for a Koszul pair (P, P^!), the complex "
                "P^! circ P (with the natural differential) is acyclic. "
                "This is the operadic analogue of the Koszul complex A circ A^! for Koszul "
                "algebras. The acyclicity is equivalent to P being Koszul. "
                "Consequence for resolutions: if P is Koszul, then Omega(P^!) -> P is a "
                "quasi-isomorphism of operads, giving the minimal resolution P_infty of P. "
                "The algebras over P_infty are exactly the P-algebras up to homotopy. "
                "Bar-cobar: the composite Omega B(P) -> P is always a resolution "
                "(cofibrant replacement), but it is minimal only for Koszul P."
            ),
            chapter_targets=("55", "66", "78"),
        ),
        OperadProfile(
            key="colored_operad",
            display_name="Colored operad (multicategory) — operads with multiple object types",
            operad_type="colored",
            algebra_type="general",
            is_koszul=False,
            has_koszul_dual=False,
            is_binary_quadratic=False,
            is_self_dual=False,
            admits_infinity_version=True,
            presentation_layer="main_text",
            focus=(
                "A colored operad (or multicategory) is a generalization of an operad that "
                "allows operations with inputs of different 'colors' (types). Formally: "
                "a C-colored operad (for a set C of colors) assigns to each tuple "
                "(c_1, ..., c_n; c) a k-module P(c_1,...,c_n; c) of operations taking "
                "n inputs of colors c_1,...,c_n and producing output of color c. "
                "Composition is defined when output colors match input colors, subject "
                "to associativity, unity, and (symmetric) equivariance. "
                "Examples: "
                "1. Any ordinary operad = 1-colored operad. "
                "2. The operad of bimodules: P(A, B) = category of (A,B)-bimodules; "
                "   composition = tensor product over B. "
                "3. Props (not quite an operad): generalize colored operads to allow "
                "   multiple outputs; encode bialgebras, Lie bialgebras, etc. "
                "4. The Boardman-Vogt W-construction: W(P) -> P (cofibrant replacement) "
                "   works for colored operads, giving P_infty-algebras for any P. "
                "Infinity colored operads: in the infinity-categorical setting "
                "(Lurie's 'Higher Algebra'), an infty-operad is a functor O: "
                "Delta^{op} -> Cat_infty satisfying the Segal condition. "
                "This encodes colored operads coherently up to all higher homotopy. "
                "Key example: the infty-operad E_n is modeled by the subcategory of "
                "rectilinear embeddings of disks, and E_n-algebras in any symmetric "
                "monoidal infty-category are defined via this operad. "
                "Applications: "
                "- Duoidal categories: two monoidal structures interacting (colored operad "
                "  with two colors). "
                "- TFT (topological field theory): a fully extended TFT is an infty-functor "
                "  from the infinity-operad Bord_n to some symmetric monoidal category. "
                "- The stable model structure on colored operads (Berger-Moerdijk): "
                "  gives a model for homotopy coherent algebraic structures."
            ),
            chapter_targets=("55", "66", "78"),
        ),
    )


# ---------------------------------------------------------------------------
# Summary / index functions
# ---------------------------------------------------------------------------

def operad_layer_summary() -> dict[str, int]:
    """Return a count of profiles by presentation_layer."""
    return dict(Counter(
        p.presentation_layer for p in get_named_operad_profiles()
    ))


def operad_chapter_index() -> dict[str, tuple[str, ...]]:
    """Return a mapping from chapter number to profile keys."""
    chapter_map: dict[str, list[str]] = {}
    for p in get_named_operad_profiles():
        for chapter in p.chapter_targets:
            chapter_map.setdefault(chapter, []).append(p.key)
    return {ch: tuple(keys) for ch, keys in sorted(chapter_map.items())}


def operad_type_index() -> dict[str, tuple[str, ...]]:
    """Return a mapping from operad_type to profile keys."""
    index: dict[str, list[str]] = {}
    for p in get_named_operad_profiles():
        index.setdefault(p.operad_type, []).append(p.key)
    return {k: tuple(v) for k, v in sorted(index.items())}


# ---------------------------------------------------------------------------
# Core analysis functions
# ---------------------------------------------------------------------------

def is_koszul_operad(space: Any) -> Result:
    """Check whether the operad is Koszul.

    An augmented quadratic operad P is Koszul if the Koszul complex
    P^! circ_kappa P is acyclic (quasi-isomorphic to the unit operad I).
    Equivalently, the bar construction B(P) is quasi-isomorphic to the
    Koszul dual cooperad P^!. Key Koszul operads: Ass, Com, Lie, E_n.

    Decision layers
    ---------------
    1. Explicit Koszul tags -> true.
    2. Known Koszul operads (Ass, Com, Lie, E_n by name/tag) -> true.
    3. Non-quadratic or known non-Koszul operads -> false.
    4. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, KOSZUL_DUALITY_TAGS):
        witness = next(t for t in tags if t in KOSZUL_DUALITY_TAGS)
        return Result.true(
            mode="theorem",
            value="koszul_operad",
            justification=[
                f"Tag {witness!r}: the operad is Koszul — the Koszul complex "
                "P^! circ_kappa P is acyclic, giving the minimal free resolution "
                "P_infty = Omega(P^!) of P.",
            ],
            metadata={**base, "criterion": "explicit_koszul", "witness": witness},
        )

    known_koszul = {
        "assoc_operad", "ass_operad", "comm_operad", "com_operad",
        "lie_operad", "lie_algebra_operad",
        "little_disks_operad", "e_n_operad", "e2_operad", "e1_operad",
        "poisson_operad",
    }
    if _matches_any(tags, known_koszul | ASSOC_OPERAD_TAGS | COMM_OPERAD_TAGS | LIE_OPERAD_TAGS):
        relevant = (known_koszul | ASSOC_OPERAD_TAGS | COMM_OPERAD_TAGS | LIE_OPERAD_TAGS) & tags
        witness = next(iter(relevant))
        return Result.true(
            mode="theorem",
            value="koszul_operad",
            justification=[
                f"Tag {witness!r}: Ass, Com, and Lie are Koszul operads "
                "(Ginzburg-Kapranov 1994). Little n-disks E_n are Koszul for all n. "
                "Their Koszul resolutions give A_infty, C_infty, and L_infty algebras.",
            ],
            metadata={**base, "criterion": "known_koszul_operad", "witness": witness},
        )

    non_koszul = {
        "non_koszul", "non_quadratic_operad", "not_koszul",
        "non_binary", "arity_greater_than_2_only",
    }
    if _matches_any(tags, non_koszul):
        witness = next(t for t in tags if t in non_koszul)
        return Result.false(
            mode="theorem",
            value="not_koszul",
            justification=[
                f"Tag {witness!r}: the operad is not Koszul. "
                "Non-binary or non-quadratic operads cannot be Koszul in the classical "
                "sense (Koszulness requires a binary quadratic presentation).",
            ],
            metadata={**base, "criterion": "explicit_non_koszul", "witness": witness},
        )

    return Result.unknown(
        mode="symbolic",
        value="unknown",
        justification=[
            "No tags indicate Koszulness or its failure. "
            "Cannot determine whether the operad is Koszul.",
        ],
        metadata={**base, "criterion": "insufficient_data"},
    )


def has_infinity_algebra_structure(space: Any) -> Result:
    """Check whether the space admits a homotopy algebra structure.

    A P_infty-algebra (A_infty, L_infty, C_infty, E_infty, ...) is an algebra over
    the minimal resolution P_infty = Omega(P^!) of a Koszul operad P. Key cases:
    A_infty (homotopy associative), L_infty (homotopy Lie), E_infty (commutative
    up to all higher homotopy coherence).

    Decision layers
    ---------------
    1. Explicit infinity-algebra tags (a_infinity, l_infinity, ...) -> true.
    2. Bar-cobar construction tags (which produce minimal resolutions) -> true.
    3. Strictly algebras over Koszul operads (which have infinity versions) -> true.
    4. Strict (non-homotopy) only tags -> false.
    5. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, INFINITY_ALGEBRA_TAGS):
        witness = next(t for t in tags if t in INFINITY_ALGEBRA_TAGS)
        return Result.true(
            mode="theorem",
            value="infinity_algebra",
            justification=[
                f"Tag {witness!r}: the space is a homotopy algebra — "
                "operations satisfying the classical axioms only up to coherent homotopy. "
                "The classical algebra structure is a special case with higher operations = 0.",
            ],
            metadata={**base, "criterion": "explicit_infinity_algebra", "witness": witness},
        )

    if _matches_any(tags, BAR_COBAR_TAGS):
        witness = next(t for t in tags if t in BAR_COBAR_TAGS)
        return Result.true(
            mode="theorem",
            value="infinity_algebra",
            justification=[
                f"Tag {witness!r}: bar-cobar constructions produce P_infty-algebra "
                "structures. The cobar construction Omega(C) of a cooperad C models "
                "P_infty-algebras as Maurer-Cartan elements in the bar complex.",
            ],
            metadata={**base, "criterion": "bar_cobar_construction", "witness": witness},
        )

    koszul_strict = {
        "associative_algebra", "commutative_algebra", "lie_algebra_operad",
        "assoc_operad", "comm_operad", "lie_operad",
    }
    if _matches_any(tags, koszul_strict | ASSOC_OPERAD_TAGS | COMM_OPERAD_TAGS | LIE_OPERAD_TAGS):
        relevant = (koszul_strict | ASSOC_OPERAD_TAGS | COMM_OPERAD_TAGS | LIE_OPERAD_TAGS) & tags
        witness = next(iter(relevant))
        return Result.true(
            mode="theorem",
            value="infinity_algebra",
            justification=[
                f"Tag {witness!r}: every strict Ass/Com/Lie-algebra is trivially an "
                "A_infty/C_infty/L_infty-algebra (with all higher operations m_n = 0 for n>=3). "
                "The homotopy transfer theorem then gives a genuine P_infty-structure "
                "on any homotopy retract.",
            ],
            metadata={**base, "criterion": "strict_implies_infinity", "witness": witness},
        )

    strict_only = {"strict_algebra_only", "no_higher_operations", "not_homotopy_algebra"}
    if _matches_any(tags, strict_only):
        witness = next(t for t in tags if t in strict_only)
        return Result.false(
            mode="theorem",
            value="no_infinity_structure",
            justification=[
                f"Tag {witness!r}: the algebra is strictly classical — no higher "
                "homotopy operations. It does not admit a non-trivial P_infty-structure.",
            ],
            metadata={**base, "criterion": "strict_only", "witness": witness},
        )

    return Result.unknown(
        mode="symbolic",
        value="unknown",
        justification=[
            "No tags indicate a homotopy algebra structure or its absence. "
            "Cannot determine P_infty-algebra status.",
        ],
        metadata={**base, "criterion": "insufficient_data"},
    )


def admits_koszul_dual(space: Any) -> Result:
    r"""Check whether the operad has a well-defined Koszul dual.

    The Koszul dual P^! of a binary quadratic operad P = F(E)/(R) is defined as
    P^! = F(E^*[1])/(R^\perp). The Koszul dual is well-defined for binary quadratic
    operads. Examples: Com^! = Lie, Lie^! = Com, Ass^! = Ass (up to twist).

    Decision layers
    ---------------
    1. Explicit Koszul duality tags -> true.
    2. Known binary quadratic operads (Ass, Com, Lie) -> true.
    3. Non-quadratic / colored / modular operads (no standard Koszul dual) -> false.
    4. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    if _matches_any(tags, KOSZUL_DUALITY_TAGS):
        witness = next(t for t in tags if t in KOSZUL_DUALITY_TAGS)
        return Result.true(
            mode="theorem",
            value="koszul_dual_exists",
            justification=[
                rf"Tag {witness!r}: the operad has a Koszul dual P^! = F(E^*[1])/(R^\perp). "
                "For Koszul operads, the bar construction B(P) is quasi-isomorphic to P^!.",
            ],
            metadata={**base, "criterion": "explicit_koszul_dual", "witness": witness},
        )

    binary_quadratic = {
        "assoc_operad", "ass_operad", "comm_operad", "com_operad",
        "lie_operad", "lie_algebra_operad", "binary_quadratic",
        "poisson_operad", "pre_lie_operad", "zinbiel_operad",
    }
    if _matches_any(tags, binary_quadratic | ASSOC_OPERAD_TAGS | COMM_OPERAD_TAGS
                    | LIE_OPERAD_TAGS):
        relevant = (binary_quadratic | ASSOC_OPERAD_TAGS | COMM_OPERAD_TAGS | LIE_OPERAD_TAGS) & tags
        witness = next(iter(relevant))
        return Result.true(
            mode="theorem",
            value="koszul_dual_exists",
            justification=[
                f"Tag {witness!r}: binary quadratic operads have a well-defined Koszul dual. "
                "Specifically: Com^! = Lie, Lie^! = Com, Ass^! = Ass (twisted). "
                "The dual is the operad presented by the orthogonal complement of the "
                "original relations.",
            ],
            metadata={**base, "criterion": "binary_quadratic_has_dual", "witness": witness},
        )

    no_koszul_dual = {
        "colored_operad", "modular_operad", "prop_operad",
        "non_binary", "non_quadratic_operad", "cyclic_operad_non_quadratic",
    }
    if _matches_any(tags, no_koszul_dual):
        witness = next(t for t in tags if t in no_koszul_dual)
        return Result.false(
            mode="theorem",
            value="no_koszul_dual",
            justification=[
                f"Tag {witness!r}: colored, modular, and prop-type operads do not have "
                "a standard Koszul dual in the binary quadratic sense. Extensions (colored "
                "Koszul duality, Koszul duality for props) exist but are more involved.",
            ],
            metadata={**base, "criterion": "no_standard_koszul_dual", "witness": witness},
        )

    return Result.unknown(
        mode="symbolic",
        value="unknown",
        justification=[
            "No tags indicate whether a Koszul dual exists. "
            "Cannot determine Koszul dual status.",
        ],
        metadata={**base, "criterion": "insufficient_data"},
    )


def is_binary_quadratic_operad(space: Any) -> Result:
    """Check whether the operad is binary quadratic.

    A binary quadratic operad is generated by binary operations (arity-2 generators E)
    with quadratic relations (R subset E circ E, involving two binary operations composed
    in arity 3). This class includes Ass, Com, Lie, Poisson, pre-Lie, and many others.
    Binary quadratic operads are the natural input for Koszul duality.

    Decision layers
    ---------------
    1. Explicit binary quadratic or tree composition tags -> true.
    2. Known binary quadratic operads (Ass, Com, Lie) -> true.
    3. Higher arity, colored, or modular operads -> false.
    4. Unknown otherwise.
    """
    tags = _extract_tags(space)
    representation = _representation_of(space)
    base: dict[str, Any] = {"representation": representation, "tags": sorted(tags)}

    explicit_bq = {"binary_quadratic", "quadratic_operad", "binary_operad"}
    if _matches_any(tags, explicit_bq | TREE_COMPOSITION_TAGS):
        witness = next(t for t in tags if t in (explicit_bq | TREE_COMPOSITION_TAGS))
        return Result.true(
            mode="theorem",
            value="binary_quadratic",
            justification=[
                f"Tag {witness!r}: the operad is binary quadratic — generated by "
                "binary operations with quadratic (arity-3) relations. This makes it "
                "amenable to Koszul duality theory.",
            ],
            metadata={**base, "criterion": "explicit_binary_quadratic", "witness": witness},
        )

    known_bq = {
        "assoc_operad", "ass_operad", "comm_operad", "com_operad",
        "lie_operad", "lie_algebra_operad", "poisson_operad",
        "pre_lie_operad", "zinbiel_operad", "dendriform_operad",
    }
    if _matches_any(tags, known_bq | ASSOC_OPERAD_TAGS | COMM_OPERAD_TAGS | LIE_OPERAD_TAGS):
        relevant = (known_bq | ASSOC_OPERAD_TAGS | COMM_OPERAD_TAGS | LIE_OPERAD_TAGS) & tags
        witness = next(iter(relevant))
        return Result.true(
            mode="theorem",
            value="binary_quadratic",
            justification=[
                f"Tag {witness!r}: Ass, Com, Lie, Poisson, pre-Lie, and dendriform operads "
                "are all binary quadratic operads with standard generators and relations. "
                "Their Koszul duals are also binary quadratic operads.",
            ],
            metadata={**base, "criterion": "known_binary_quadratic", "witness": witness},
        )

    non_bq = {
        "colored_operad", "modular_operad", "a_infinity_operad",
        "l_infinity_operad", "non_binary", "higher_arity",
        "cyclic_operad_non_binary",
    }
    if _matches_any(tags, non_bq):
        witness = next(t for t in tags if t in non_bq)
        return Result.false(
            mode="theorem",
            value="not_binary_quadratic",
            justification=[
                f"Tag {witness!r}: the operad is not binary quadratic. "
                "A_infty and L_infty operads have generators in all arities; colored and "
                "modular operads have multi-colored inputs; higher-arity operads have "
                "generators of arity > 2.",
            ],
            metadata={**base, "criterion": "explicit_non_binary_quadratic", "witness": witness},
        )

    return Result.unknown(
        mode="symbolic",
        value="unknown",
        justification=[
            "No tags indicate binary quadratic structure or its absence. "
            "Cannot determine binary quadratic status.",
        ],
        metadata={**base, "criterion": "insufficient_data"},
    )


# ---------------------------------------------------------------------------
# Facade functions
# ---------------------------------------------------------------------------

def classify_operad(space: Any) -> dict[str, Any]:
    """Run all operad analysis functions and return a combined result dict."""
    return {
        "is_koszul_operad":             is_koszul_operad(space),
        "has_infinity_algebra_structure": has_infinity_algebra_structure(space),
        "admits_koszul_dual":           admits_koszul_dual(space),
        "is_binary_quadratic_operad":   is_binary_quadratic_operad(space),
    }


def operad_profile_report(space: Any) -> dict[str, Any]:
    """Return a comprehensive operad profile of the space."""
    classification = classify_operad(space)
    return {
        "space": space,
        "tags": sorted(_extract_tags(space)),
        "representation": _representation_of(space),
        "classification": classification,
        "summary": {
            k: r.value for k, r in classification.items()
        },
    }


# ---------------------------------------------------------------------------
# Computational engines (P8.3)
# ---------------------------------------------------------------------------

def _full_binary_trees(n: int) -> list[Any]:
    """All full binary trees with n leaves. Leaf = None, node = (left, right)."""
    if n == 1:
        return [None]
    trees: list[Any] = []
    for i in range(1, n):
        for left in _full_binary_trees(i):
            for right in _full_binary_trees(n - i):
                trees.append((left, right))
    return trees


def _one_step_rotations(tree: Any) -> list[Any]:
    """All trees obtainable by one tree rotation from ``tree``."""
    if tree is None:
        return []
    left, right = tree
    rotations: list[Any] = []
    # Right rotation at root: (X, (Y, Z)) → ((X, Y), Z)
    if isinstance(right, tuple):
        y, z = right
        rotations.append(((left, y), z))
    # Left rotation at root: ((X, Y), Z) → (X, (Y, Z))
    if isinstance(left, tuple):
        x, y = left
        rotations.append((x, (y, right)))
    # Recursive rotations in subtrees
    for rot in _one_step_rotations(left):
        rotations.append((rot, right))
    for rot in _one_step_rotations(right):
        rotations.append((left, rot))
    return rotations


def associahedron_complex(n: int) -> Any:
    """Stasheff associahedron K_n as a simplicial complex.

    Vertices = full binary trees with n leaves (Catalan number C_{n-1}).
    1-simplices = pairs connected by one tree rotation.
    K₃ = interval (2 vertices, 1 edge).
    K₄ = pentagon (5 vertices, 5 edges, homeomorphic to S¹).

    Parameters
    ----------
    n: number of leaves (n ≥ 2)

    Returns
    -------
    SimplicialComplex whose 1-skeleton is the rotation graph of K_n.

    Examples
    --------
    >>> K4 = associahedron_complex(4)
    >>> sum(1 for s in K4.simplexes if len(s.vertices) == 1)  # 5 vertices
    5
    """
    from .simplices import Simplex
    from .simplicial_complexes import SimplicialComplex
    if n < 2:
        raise ValueError("n must be ≥ 2")
    trees = _full_binary_trees(n)
    # Deduplicate while preserving order (trees are hashable tuples/None)
    seen: set[Any] = set()
    unique: list[Any] = []
    for t in trees:
        key = repr(t)
        if key not in seen:
            seen.add(key)
            unique.append(t)
    idx: dict[str, int] = {repr(t): i for i, t in enumerate(unique)}
    simplices: list[Simplex] = [Simplex([i]) for i in range(len(unique))]
    edge_set: set[tuple[int, int]] = set()
    for t in unique:
        i = idx[repr(t)]
        for rot in _one_step_rotations(t):
            key = repr(rot)
            if key in idx:
                j = idx[key]
                edge = (min(i, j), max(i, j))
                if edge not in edge_set:
                    edge_set.add(edge)
                    simplices.append(Simplex(list(edge)))
    return SimplicialComplex(simplices)


def operad_composition_check(
    mu: list[list[int]],
) -> dict[str, Any]:
    """Verify the operad associativity axiom for a binary composition map.

    The composition µ: A ⊗ A → A (given as a matrix µ[i][j] = index of µ(eᵢ, eⱼ))
    must satisfy the associativity pentagon: µ(µ(a,b), c) = µ(a, µ(b,c)).

    Parameters
    ----------
    mu: square n×n matrix of non-negative integers (< n); mu[i][j] is the
        index of µ(eᵢ, eⱼ) in the basis

    Returns
    -------
    dict with ``associative``, ``n_violations``, ``is_operad_composition``.

    Examples
    --------
    Constant composition µ(i,j) = 0 is trivially associative:

    >>> operad_composition_check([[0, 0], [0, 0]])["associative"]
    True
    """
    n = len(mu)
    if n == 0:
        return {"associative": True, "n_violations": 0, "is_operad_composition": True}
    violations = 0
    for i in range(n):
        for j in range(n):
            ij = mu[i][j] if 0 <= i < n and 0 <= j < n else -1
            for k in range(n):
                jk = mu[j][k] if 0 <= j < n and 0 <= k < n else -1
                lhs = mu[ij][k] if 0 <= ij < n else -1
                rhs = mu[i][jk] if 0 <= jk < n else -1
                if lhs != rhs:
                    violations += 1
    return {
        "associative": violations == 0,
        "n_violations": violations,
        "is_operad_composition": violations == 0,
    }


def bar_construction_sc(
    n_generators: int,
    n_relations: int = 0,
) -> Any:
    """Bar construction B(A) of an algebra with given generators and relations.

    The bar complex B(A) has B(A)_k = A^{⊗k+2}. Its 1-skeleton over the
    generators produces a complete graph; relations introduce 2-simplices.

    Parameters
    ----------
    n_generators: number of algebra generators (= dimension of A)
    n_relations: number of relations (introduces 2-simplices for the first
        ``n_relations`` consecutive generator triples)

    Returns
    -------
    SimplicialComplex with n_generators vertices, edges for each pair,
    and 2-simplices for compatible relation triples.

    Examples
    --------
    Free algebra on 2 generators (no relations):

    >>> sc = bar_construction_sc(2, 0)
    >>> sum(1 for s in sc.simplexes if len(s.vertices) == 1)
    2
    """
    from .simplices import Simplex
    from .simplicial_complexes import SimplicialComplex
    if n_generators < 1:
        raise ValueError("n_generators must be ≥ 1")
    simplices: list[Simplex] = [Simplex([i]) for i in range(n_generators)]
    for i in range(n_generators):
        for j in range(i + 1, n_generators):
            simplices.append(Simplex([i, j]))
    for r in range(min(n_relations, max(0, n_generators - 2))):
        simplices.append(Simplex([r, r + 1, r + 2]))
    return SimplicialComplex(simplices)


# ---------------------------------------------------------------------------
# __all__
# ---------------------------------------------------------------------------

__all__ = [
    "OperadProfile",
    "ASSOC_OPERAD_TAGS",
    "COMM_OPERAD_TAGS",
    "LIE_OPERAD_TAGS",
    "KOSZUL_DUALITY_TAGS",
    "INFINITY_ALGEBRA_TAGS",
    "LITTLE_DISKS_TAGS",
    "TREE_COMPOSITION_TAGS",
    "BAR_COBAR_TAGS",
    "get_named_operad_profiles",
    "operad_layer_summary",
    "operad_chapter_index",
    "operad_type_index",
    "is_koszul_operad",
    "has_infinity_algebra_structure",
    "admits_koszul_dual",
    "is_binary_quadratic_operad",
    "classify_operad",
    "operad_profile_report",
    # P8.3 computational engines
    "associahedron_complex",
    "operad_composition_check",
    "bar_construction_sc",
]
