"""Random and semi-random generators for foundational mathematical structures.

Provides:
- ``random_set``      — frozenset with size control, element type, and ordering mode
- ``LazyTopology``    — subbasis-backed topology with bitmask UID; no full enumeration
- ``random_topology`` — random topology (exact for small carriers, lazy for large)
- ``random_relation`` — random binary relation via density sampling
- ``random_function`` — random function as a plain dict
"""

from __future__ import annotations

import string
from collections.abc import Iterable
from dataclasses import dataclass, field
from random import Random
from typing import Any

from .finite_spaces import FiniteTopologicalSpace
from .sets import power_set
from .subbases import generate_topology_from_subbasis


class RandomGeneratorError(ValueError):
    """Raised when a random generator receives invalid parameters."""


# ---------------------------------------------------------------------------
# Internal pools
# ---------------------------------------------------------------------------

_INT_POOL: list[int] = list(range(1, 100))
_CHAR_POOL: list[str] = list(string.ascii_lowercase)
_STR_POOL: list[str] = [a + b for a in string.ascii_lowercase for b in string.ascii_lowercase]


def _build_pool(element_type: str, pool: list[Any] | None) -> list[Any]:
    if pool is not None:
        return pool
    if element_type == "int":
        return list(_INT_POOL)
    if element_type == "char":
        return list(_CHAR_POOL)
    if element_type == "str":
        return list(_STR_POOL)
    raise RandomGeneratorError(
        f"Unknown element_type {element_type!r}. Use 'int', 'char', or 'str'."
    )


# ---------------------------------------------------------------------------
# random_set
# ---------------------------------------------------------------------------

def random_set(
    max_size: int | None = None,
    *,
    min_size: int = 0,
    size: int | None = None,
    element_type: str = "int",
    pool: Iterable[Any] | None = None,
    random_order: bool = True,
    seed: int | None = None,
) -> frozenset[Any]:
    """Return a random frozenset of elements.

    Parameters
    ----------
    max_size:
        Upper bound on the number of elements.  Ignored when *size* is given.
    min_size:
        Lower bound (default 0).  Used only when *max_size* is given.
    size:
        Exact number of elements.  Takes priority over *min_size*/*max_size*.
    element_type:
        ``"int"`` (default, draws from 1–99), ``"char"`` (a–z),
        or ``"str"`` (two-letter combinations aa–zz).
        Ignored when *pool* is given.
    pool:
        Custom iterable of elements to draw from.
    random_order:
        ``True`` (default): pool is shuffled — elements are chosen randomly.
        ``False``: first *k* elements of the pool are taken in order.
    seed:
        Integer seed for reproducibility.

    Examples
    --------
    >>> random_set(max_size=5, seed=0)
    frozenset({...})
    >>> random_set(size=3, element_type='char', random_order=False)
    frozenset({'a', 'b', 'c'})
    """
    rng = Random(seed)
    full_pool = _build_pool(element_type, list(pool) if pool is not None else None)

    # Determine number of elements to draw
    if size is not None:
        k = size
    elif max_size is not None:
        lo = max(0, min_size)
        hi = max_size
        if lo > hi:
            raise RandomGeneratorError(f"min_size ({lo}) > max_size ({hi}).")
        k = rng.randint(lo, hi)
    else:
        raise RandomGeneratorError("Provide at least one of: size, max_size.")

    if k < 0:
        raise RandomGeneratorError(f"Element count cannot be negative (got {k}).")
    if k > len(full_pool):
        raise RandomGeneratorError(
            f"Requested {k} elements but pool has only {len(full_pool)}."
        )

    if random_order:
        chosen = rng.sample(full_pool, k)
    else:
        chosen = full_pool[:k]

    return frozenset(chosen)


# ---------------------------------------------------------------------------
# LazyTopology helpers
# ---------------------------------------------------------------------------

def _compute_basis(subbasis: frozenset[frozenset[Any]], carrier: frozenset[Any]) -> frozenset[frozenset[Any]]:
    """Compute the intersection-closed basis generated by a subbasis.

    Uses a pairwise fixpoint instead of enumerating all 2^|subbasis| subsets,
    so it stays efficient even for larger subbases.
    """
    # Seed with subbasis elements and the full carrier (empty-intersection convention)
    elements: set[frozenset[Any]] = set(subbasis)
    elements.add(carrier)

    # Close under pairwise intersections until fixpoint
    changed = True
    while changed:
        changed = False
        current = list(elements)
        for i, a in enumerate(current):
            for b in current[i:]:
                inter = a & b
                if inter and inter not in elements:
                    elements.add(inter)
                    changed = True

    # Remove empty set (∅ is open but not a basis element)
    elements.discard(frozenset())
    return frozenset(elements)


def _is_union_of_basis_elements(U: frozenset[Any], basis: frozenset[frozenset[Any]]) -> bool:
    """Return True iff every point of U is covered by a basis element ⊆ U."""
    for x in U:
        if not any(x in B and B.issubset(U) for B in basis):
            return False
    return True


# ---------------------------------------------------------------------------
# LazyTopology
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class LazyTopology:
    """A topology represented by its subbasis — no full open-set enumeration.

    Any collection of subsets generates a valid topology (the smallest one
    containing those sets), so LazyTopology is always mathematically correct
    by construction regardless of the subbasis chosen.

    Each (carrier, subbasis) pair receives a **unique integer UID** built as
    a bitmask over the power set of the carrier::

        Canonical order: carrier elements sorted by repr().
        S_i = {carrier[j] : bit j of i = 1}   (the i-th subset in bitmask order)
        UID = Σ  2^i  for all i where S_i ∈ subbasis

    Parameters
    ----------
    carrier:
        The underlying set X.
    subbasis:
        Generating collection of subsets of X.
    """

    carrier: frozenset[Any]
    subbasis: frozenset[frozenset[Any]]
    # Computed in __post_init__ — not constructor parameters:
    uid: int = field(init=False, repr=True, compare=True, hash=True)
    _carrier_sorted: tuple[Any, ...] = field(
        init=False, repr=False, compare=False, hash=False
    )
    _basis_cache: frozenset[frozenset[Any]] = field(
        init=False, repr=False, compare=False, hash=False
    )

    def __post_init__(self) -> None:
        cs: tuple[Any, ...] = tuple(sorted(self.carrier, key=repr))
        object.__setattr__(self, "_carrier_sorted", cs)
        uid = LazyTopology._compute_uid(cs, self.subbasis)
        object.__setattr__(self, "uid", uid)
        basis = _compute_basis(self.subbasis, self.carrier)
        object.__setattr__(self, "_basis_cache", basis)

    # ------------------------------------------------------------------
    # Open-set queries
    # ------------------------------------------------------------------

    def is_open(self, subset: Iterable[Any]) -> bool:
        """Return True iff *subset* is open in this topology.

        U is open iff every point in U is covered by a basis element ⊆ U.
        No full enumeration of open sets is performed.
        """
        U = frozenset(subset)
        if not U or U == self.carrier:
            return True
        if not U.issubset(self.carrier):
            return False
        return _is_union_of_basis_elements(U, self._basis_cache)

    def contains_open(self, subset: Iterable[Any]) -> bool:
        """Alias for :meth:`is_open`."""
        return self.is_open(subset)

    # ------------------------------------------------------------------
    # Random open sets
    # ------------------------------------------------------------------

    def random_open_set(self, seed: int | None = None) -> frozenset[Any]:
        """Return a random open set (union of basis elements).

        Any union of basis elements is open by definition, so no
        verification is needed.  The empty set (k=0) is a possible outcome.
        """
        rng = Random(seed)
        basis_list = list(self._basis_cache)
        k = rng.randint(0, len(basis_list))
        if k == 0:
            return frozenset()
        chosen = rng.sample(basis_list, k)
        return frozenset().union(*chosen)

    def sample_open_sets(self, k: int, seed: int | None = None) -> list[frozenset[Any]]:
        """Return *k* independent random open sets."""
        rng = Random(seed)
        return [self.random_open_set(seed=rng.randint(0, 2**32)) for _ in range(k)]

    # ------------------------------------------------------------------
    # UID machinery
    # ------------------------------------------------------------------

    @staticmethod
    def _compute_uid(
        carrier_sorted: tuple[Any, ...],
        subbasis: frozenset[frozenset[Any]],
    ) -> int:
        """Compute the bitmask UID.

        Bit i of the UID is set iff the i-th subset of *carrier_sorted*
        (in bitmask enumeration order) belongs to the subbasis.
        """
        elem_to_bit: dict[Any, int] = {x: (1 << j) for j, x in enumerate(carrier_sorted)}
        uid = 0
        for subset in subbasis:
            subset_idx = 0
            for x in subset:
                subset_idx |= elem_to_bit.get(x, 0)
            uid |= (1 << subset_idx)
        return uid

    @staticmethod
    def from_uid(carrier: Iterable[Any], uid: int) -> LazyTopology:
        """Reconstruct a LazyTopology from its carrier and UID.

        Parameters
        ----------
        carrier:
            Must contain the same elements as when the UID was produced.
        uid:
            The integer UID from a previous :class:`LazyTopology` instance.
        """
        carrier_list = list(carrier)
        n = len(carrier_list)
        if n > 25:
            raise RandomGeneratorError(
                f"from_uid supports carriers with at most 25 elements (got {n})."
            )
        carrier_sorted = tuple(sorted(carrier_list, key=repr))
        num_subsets = 1 << n

        subbasis: set[frozenset[Any]] = set()
        for subset_idx in range(num_subsets):
            if (uid >> subset_idx) & 1:
                subset = frozenset(
                    carrier_sorted[j] for j in range(n) if (subset_idx >> j) & 1
                )
                subbasis.add(subset)

        return LazyTopology(
            carrier=frozenset(carrier_list),
            subbasis=frozenset(subbasis),
        )

    def __repr__(self) -> str:
        return (
            f"LazyTopology(carrier_size={len(self.carrier)}, "
            f"subbasis_size={len(self.subbasis)}, "
            f"uid={self.uid})"
        )


# ---------------------------------------------------------------------------
# random_topology
# ---------------------------------------------------------------------------

def random_topology(
    carrier: Iterable[Any],
    seed: int | None = None,
    max_subbasis_size: int | None = None,
) -> FiniteTopologicalSpace | LazyTopology:
    """Return a random topology on *carrier*.

    For small carriers (|X| ≤ 5) all open sets are enumerated and a
    :class:`FiniteTopologicalSpace` is returned.  For larger carriers a
    :class:`LazyTopology` is returned — no full enumeration.

    Parameters
    ----------
    carrier:
        Elements of the underlying set.
    seed:
        Random seed for reproducibility.
    max_subbasis_size:
        Cap on the number of subbasis generators (default: uncapped).
    """
    rng = Random(seed)
    carrier_set = frozenset(carrier)
    n = len(carrier_set)

    # Candidate generator sets: all proper non-empty subsets of X
    all_subsets = list(power_set(carrier_set))
    candidates: list[frozenset[Any]] = [
        s for s in all_subsets if s and s != carrier_set
    ]

    if not candidates:
        subbasis: frozenset[frozenset[Any]] = frozenset()
    else:
        cap = min(max_subbasis_size or len(candidates), len(candidates))
        k = rng.randint(0, cap)
        subbasis = frozenset(rng.sample(candidates, k))

    if n <= 5:
        if not subbasis:
            tau = frozenset([frozenset(), carrier_set])
            return FiniteTopologicalSpace(carrier=carrier_set, topology=tau)
        return generate_topology_from_subbasis(carrier_set, list(subbasis))

    return LazyTopology(carrier=carrier_set, subbasis=subbasis)


# ---------------------------------------------------------------------------
# random_relation
# ---------------------------------------------------------------------------

def random_relation(
    carrier: Iterable[Any],
    seed: int | None = None,
    density: float = 0.5,
) -> set[tuple[Any, Any]]:
    """Return a random binary relation on *carrier*.

    Each pair (x, y) in carrier × carrier is included independently with
    probability *density*.

    Parameters
    ----------
    carrier:
        Elements of the underlying set.
    density:
        Inclusion probability per pair, in [0.0, 1.0] (default 0.5).
    seed:
        Random seed for reproducibility.

    Examples
    --------
    >>> random_relation([1, 2, 3], density=1.0)
    {(1,1),(1,2),(1,3),(2,1),(2,2),(2,3),(3,1),(3,2),(3,3)}
    """
    if not (0.0 <= density <= 1.0):
        raise RandomGeneratorError(f"density must be in [0.0, 1.0], got {density}.")
    rng = Random(seed)
    carrier_list = list(carrier)
    relation: set[tuple[Any, Any]] = set()
    for x in carrier_list:
        for y in carrier_list:
            if rng.random() < density:
                relation.add((x, y))
    return relation


# ---------------------------------------------------------------------------
# random_function
# ---------------------------------------------------------------------------

def random_function(
    domain: Iterable[Any],
    codomain: Iterable[Any],
    seed: int | None = None,
) -> dict[Any, Any]:
    """Return a random function from *domain* to *codomain* as a dict.

    Each domain element is assigned a uniformly random codomain element.
    Pass the result to :func:`pytop.maps.make_function` to obtain a
    :class:`~pytop.maps.FiniteMap`.

    Parameters
    ----------
    domain:
        Elements of the domain set.
    codomain:
        Elements of the codomain set (must be non-empty).
    seed:
        Random seed for reproducibility.
    """
    rng = Random(seed)
    domain_list = list(domain)
    codomain_list = list(codomain)
    if not codomain_list:
        raise RandomGeneratorError("Codomain must be non-empty.")
    return {x: rng.choice(codomain_list) for x in domain_list}


__all__ = [
    "RandomGeneratorError",
    "random_set",
    "LazyTopology",
    "random_topology",
    "random_relation",
    "random_function",
]
