"""Subbasis and basis helpers for explicit foundational computations.

The functions in this module stay deliberately finite and concrete. They are
intended for Chapter 04 notebooks, worked examples, and lightweight internal
validation around basis criteria, subbasis generation, and local-base checks.
"""

from __future__ import annotations

from itertools import combinations
from typing import Any, Iterable, Mapping

from .families import normalize_family
from .finite_spaces import FiniteTopologicalSpace
from .spaces import TopologicalSpace


class BasisConstructionError(ValueError):
    """Raised when a finite basis or subbasis construction is invalid."""


def is_basis_for_some_topology(
    carrier: Iterable[Any],
    basis_family: Mapping[Any, Iterable[Any]] | Iterable[Iterable[Any]],
) -> bool:
    """Return whether *basis_family* is a basis for some topology on *carrier*.

    The criterion used is the standard finite Chapter 04 criterion: the basis
    must cover the carrier, and intersections around any common point must be
    locally refinable by another basis element.
    """

    carrier_set = _normalize_carrier(carrier)
    basis = _normalize_subset_family(basis_family, carrier_set)
    if not basis:
        return len(carrier_set) == 0
    if frozenset().union(*basis) != carrier_set:
        return False
    for left in basis:
        for right in basis:
            overlap = left & right
            if not overlap:
                continue
            for point in overlap:
                if not any(point in candidate and candidate.issubset(overlap) for candidate in basis):
                    return False
    return True


def is_basis_for_topology(
    carrier_or_space: Iterable[Any] | TopologicalSpace,
    basis_family: Mapping[Any, Iterable[Any]] | Iterable[Iterable[Any]],
    topology: Mapping[Any, Iterable[Any]] | Iterable[Iterable[Any]] | None = None,
) -> bool:
    """Return whether *basis_family* is a basis for the given topology.

    The function accepts either ``(carrier, basis_family, topology=...)`` or a
    finite ``TopologicalSpace`` instance as the first argument.
    """

    carrier_set, topology_family = _resolve_space_inputs(carrier_or_space, topology)
    basis = _normalize_subset_family(basis_family, carrier_set)
    topology_sets = _normalize_topology(topology_family, carrier_set)
    if not _is_topology(topology_sets, carrier_set):
        return False
    if any(member not in topology_sets for member in basis):
        return False
    for open_set in topology_sets:
        for point in open_set:
            if not any(point in member and member.issubset(open_set) for member in basis):
                return False
    return True


def finite_intersection_basis(
    carrier: Iterable[Any],
    subbasis_family: Mapping[Any, Iterable[Any]] | Iterable[Iterable[Any]],
) -> list[set[Any]]:
    """Return the basis obtained from finite intersections of a subbasis.

    The empty intersection is interpreted as the full carrier, so the output
    always contains ``X``. Members are returned as a deduplicated list of sets.
    """

    carrier_set = _normalize_carrier(carrier)
    subbasis = _normalize_subset_family(subbasis_family, carrier_set)
    intersections: set[frozenset[Any]] = {carrier_set}
    members = list(subbasis)
    for r in range(1, len(members) + 1):
        for combo in combinations(members, r):
            current = carrier_set
            for member in combo:
                current = current & member
            intersections.add(current)
    return _to_sorted_set_list(intersections)


def generate_topology_from_basis(
    carrier: Iterable[Any],
    basis_family: Mapping[Any, Iterable[Any]] | Iterable[Iterable[Any]],
    *,
    description: str | None = None,
) -> FiniteTopologicalSpace:
    """Construct the finite topology generated by a basis.

    The construction is exact: every union of basis members is enumerated
    explicitly. The result is returned as a ``FiniteTopologicalSpace``.
    """

    carrier_set = _normalize_carrier(carrier)
    basis = _normalize_subset_family(basis_family, carrier_set)
    if not is_basis_for_some_topology(carrier_set, basis):
        raise BasisConstructionError(
            'The supplied family does not satisfy the basis criterion on the given carrier.'
        )

    topology_sets: set[frozenset[Any]] = {frozenset()}
    members = list(basis)
    if carrier_set:
        topology_sets.add(carrier_set)
    for r in range(1, len(members) + 1):
        for combo in combinations(members, r):
            union = frozenset().union(*combo)
            topology_sets.add(union)
    metadata = {
        'description': description or 'A finite topology generated from a basis.',
        'construction': 'basis_generated',
        'basis_size': len(basis),
    }
    return FiniteTopologicalSpace(
        carrier=tuple(_sorted_points(carrier_set)),
        topology=_to_sorted_set_list(topology_sets),
        metadata=metadata,
        tags={'basis-generated', 'chapter-04'},
    )


def generate_topology_from_subbasis(
    carrier: Iterable[Any],
    subbasis_family: Mapping[Any, Iterable[Any]] | Iterable[Iterable[Any]],
    *,
    description: str | None = None,
) -> FiniteTopologicalSpace:
    """Construct the finite topology generated by a subbasis."""

    carrier_set = _normalize_carrier(carrier)
    basis = finite_intersection_basis(carrier_set, subbasis_family)
    space = generate_topology_from_basis(
        carrier_set,
        basis,
        description=description or 'A finite topology generated from a subbasis.',
    )
    space.add_tags('subbasis-generated')
    space.metadata['construction'] = 'subbasis_generated'
    space.metadata['subbasis_size'] = len(_normalize_subset_family(subbasis_family, carrier_set))
    return space


def is_local_base_at(
    carrier_or_space: Iterable[Any] | TopologicalSpace,
    point: Any,
    candidate_family: Mapping[Any, Iterable[Any]] | Iterable[Iterable[Any]],
    topology: Mapping[Any, Iterable[Any]] | Iterable[Iterable[Any]] | None = None,
) -> bool:
    """Return whether *candidate_family* is a local base at *point*.

    The function accepts either ``(space, point, candidate_family)`` or
    ``(carrier, point, candidate_family, topology=...)``.
    """

    carrier_set, topology_family = _resolve_space_inputs(carrier_or_space, topology)
    if point not in carrier_set:
        return False
    topology_sets = _normalize_topology(topology_family, carrier_set)
    if not _is_topology(topology_sets, carrier_set):
        return False
    local_family = _normalize_subset_family(candidate_family, carrier_set)
    if any(point not in member for member in local_family):
        return False
    neighborhoods = [open_set for open_set in topology_sets if point in open_set]
    for neighborhood in neighborhoods:
        if not any(member.issubset(neighborhood) for member in local_family):
            return False
    return True


def _resolve_space_inputs(
    carrier_or_space: Iterable[Any] | TopologicalSpace,
    topology: Mapping[Any, Iterable[Any]] | Iterable[Iterable[Any]] | None,
) -> tuple[frozenset[Any], tuple[frozenset[Any], ...]]:
    if isinstance(carrier_or_space, TopologicalSpace):
        carrier_set = _normalize_carrier(carrier_or_space.carrier or ())
        topology_source = carrier_or_space.topology if topology is None else topology
        return carrier_set, _normalize_topology(topology_source or (), carrier_set)
    if topology is None:
        raise BasisConstructionError('Topology data must be supplied when no space object is given.')
    carrier_set = _normalize_carrier(carrier_or_space)
    return carrier_set, _normalize_topology(topology, carrier_set)


def _normalize_carrier(carrier: Iterable[Any]) -> frozenset[Any]:
    try:
        return frozenset(carrier)
    except TypeError as exc:
        raise BasisConstructionError('The carrier must be a finite iterable of hashable points.') from exc


def _normalize_subset_family(
    family: Mapping[Any, Iterable[Any]] | Iterable[Iterable[Any]],
    carrier_set: frozenset[Any],
) -> tuple[frozenset[Any], ...]:
    normalized: list[frozenset[Any]] = []
    seen: set[frozenset[Any]] = set()
    members = family.values() if isinstance(family, Mapping) else family
    for member in members:
        frozen = frozenset(member)
        if not frozen.issubset(carrier_set):
            raise BasisConstructionError('Every family member must be a subset of the carrier.')
        if frozen not in seen:
            seen.add(frozen)
            normalized.append(frozen)
    return tuple(normalized)


def _normalize_topology(
    topology: Mapping[Any, Iterable[Any]] | Iterable[Iterable[Any]],
    carrier_set: frozenset[Any],
) -> tuple[frozenset[Any], ...]:
    return _normalize_subset_family(topology, carrier_set)


def _is_topology(topology: tuple[frozenset[Any], ...], carrier_set: frozenset[Any]) -> bool:
    topology_set = set(topology)
    if frozenset() not in topology_set or carrier_set not in topology_set:
        return False
    for left in topology:
        for right in topology:
            if (left | right) not in topology_set or (left & right) not in topology_set:
                return False
    return True


def _sorted_points(carrier_set: frozenset[Any]) -> list[Any]:
    return sorted(carrier_set, key=repr)


def _to_sorted_set_list(family: Iterable[frozenset[Any]]) -> list[set[Any]]:
    return [set(member) for member in sorted(set(family), key=lambda block: (len(block), repr(tuple(sorted(block, key=repr)))))]


__all__ = [
    'BasisConstructionError',
    'is_basis_for_some_topology',
    'is_basis_for_topology',
    'finite_intersection_basis',
    'generate_topology_from_basis',
    'generate_topology_from_subbasis',
    'is_local_base_at',
]
