"""High-level topology builders for finite carriers.

Convenience constructors that hide frozenset plumbing and let users build
standard topologies with clean mathematical syntax:

    discrete_topology(1, 2, 3)
    make_topology({1, 2, 3}, {1}, {2, 3})
    sierpinski_space()
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import Any

from .finite_spaces import FiniteTopologicalSpace
from .sets import power_set
from .subbases import generate_topology_from_basis, generate_topology_from_subbasis


def make_topology(carrier: Iterable[Any], *open_sets: Iterable[Any]) -> FiniteTopologicalSpace:
    """Build a topology on *carrier* from the given explicit open sets.

    ∅ and X are added automatically — you only need to list the
    non-trivial open sets.

    Parameters
    ----------
    carrier:
        Elements of the underlying set X.
    *open_sets:
        Additional open sets (besides ∅ and X).  Each may be any
        iterable of elements from *carrier*.

    Examples
    --------
    >>> sp = make_topology({0, 1, 2}, {0}, {1, 2})
    >>> len(sp.topology)  # {∅, {0}, {1,2}, X} = 4
    4
    """
    x = frozenset(carrier)
    tau: set[frozenset[Any]] = {frozenset(), x}
    for s in open_sets:
        tau.add(frozenset(s))
    sp = FiniteTopologicalSpace(carrier=x, topology=frozenset(tau))
    return sp


def discrete_topology(*elements: Any) -> FiniteTopologicalSpace:
    """Return the discrete topology on the given elements.

    Every subset is open.

    Parameters
    ----------
    *elements:
        Elements of the underlying set.  Pass them as separate arguments:
        ``discrete_topology(1, 2, 3)``.
    """
    x = frozenset(elements)
    tau = frozenset(power_set(x))
    sp = FiniteTopologicalSpace(
        carrier=x,
        topology=tau,
        metadata={"name": "Ayrık topoloji", "description": "Discrete topology — every subset is open."},
        tags={"discrete", "hausdorff", "regular", "normal", "metrizable"},
    )
    return sp


def indiscrete_topology(*elements: Any) -> FiniteTopologicalSpace:
    """Return the indiscrete (trivial) topology on the given elements.

    Only ∅ and X are open.

    Parameters
    ----------
    *elements:
        Elements of the underlying set.
    """
    x = frozenset(elements)
    tau = frozenset([frozenset(), x])
    sp = FiniteTopologicalSpace(
        carrier=x,
        topology=tau,
        metadata={"name": "İndirgenmiş topoloji", "description": "Indiscrete topology — only ∅ and X are open."},
        tags={"indiscrete", "compact", "connected"},
    )
    return sp


def cofinite_topology(*elements: Any) -> FiniteTopologicalSpace:
    """Return the cofinite topology on the given elements.

    A set U ⊆ X is open iff U = ∅ or X \\ U is finite.
    For finite X every subset satisfies this, so the result equals the
    discrete topology — but it is tagged as cofinite for educational
    distinction.

    Parameters
    ----------
    *elements:
        Elements of the underlying set.
    """
    x = frozenset(elements)
    tau = frozenset(power_set(x))
    sp = FiniteTopologicalSpace(
        carrier=x,
        topology=tau,
        metadata={
            "name": "Kosonlu topoloji",
            "description": (
                "Cofinite topology: U is open iff U = ∅ or X \\ U is finite. "
                "For finite X this coincides with the discrete topology."
            ),
        },
        tags={"cofinite", "t1", "compact"},
    )
    return sp


def sierpinski_space() -> FiniteTopologicalSpace:
    """Return the Sierpiński space: X = {0, 1}, τ = {∅, {1}, {0, 1}}.

    The point 1 is open; the point 0 is not.
    """
    x = frozenset({0, 1})
    tau = frozenset([frozenset(), frozenset({1}), x])
    sp = FiniteTopologicalSpace(
        carrier=x,
        topology=tau,
        metadata={"name": "Sierpiński uzayı", "description": "Sierpiński space: X={0,1}, τ={∅,{1},X}."},
        tags={"t0", "connected", "compact"},
    )
    return sp


def topology_from_basis(
    carrier: Iterable[Any],
    basis: Iterable[Iterable[Any]],
) -> FiniteTopologicalSpace:
    """Construct the topology generated by a basis.

    Delegates to :func:`pytop.subbases.generate_topology_from_basis`.

    Parameters
    ----------
    carrier:
        Elements of the underlying set X.
    basis:
        A collection of subsets of X satisfying the basis axioms:
        (B1) covers X; (B2) intersections are locally refinable.
    """
    return generate_topology_from_basis(carrier, basis)


def topology_from_subbasis(
    carrier: Iterable[Any],
    subbasis: Iterable[Iterable[Any]],
) -> FiniteTopologicalSpace:
    """Construct the topology generated by a subbasis.

    The topology is the smallest topology containing all subbasis members.
    Delegates to :func:`pytop.subbases.generate_topology_from_subbasis`.

    Parameters
    ----------
    carrier:
        Elements of the underlying set X.
    subbasis:
        A collection of subsets of X.  Finite intersections of these sets
        form a basis, and their unions form the topology.
    """
    return generate_topology_from_subbasis(carrier, subbasis)


__all__ = [
    "make_topology",
    "discrete_topology",
    "indiscrete_topology",
    "cofinite_topology",
    "sierpinski_space",
    "topology_from_basis",
    "topology_from_subbasis",
]
